apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - cronjob.yaml

configMapGenerator:
  - name: dd-scheduled-task-digest
    files:
      - shared.mjs=shared.mjs
      - github.mjs=github.mjs
      - kubernetes.mjs=kubernetes.mjs
      - digest.mjs=digest.mjs
      - main.mjs=main.mjs

generatorOptions:
  disableNameSuffixHash: true
