#!/bin/bash
set -e

BASE="$HOME/codes"
LOGFILE="$BASE/ores/k8s-cluster/.gemini-clone-results.log"
> "$LOGFILE"

MISSING_REPOS=(
  "dancing-dragons/dd-next-1"
  "dancing-dragons/dd-monorepo"
  "dancing-dragons/dd-live"
  "dancing-dragons/Company-Job-Descriptions"
  "dancing-dragons/Meeting-SOP"
  "dancing-dragons/supabase-branches"
  "dancing-dragons/Updated-Organizational-Flowchart-CAO-09112025"
  "dancing-dragons/dancing-dragons.github.io"
  "sonus-auris/sonus-auris-api-server.rs"
  "sonus-auris/sonus-auris-e2e"
  "3FA-app/3fa-app.github.io"
  "3FA-app/3fa-web-server.rs"
  "3FA-app/threefa-monorepo"
  "3FA-app/3fa-app-sync"
  "akrion-sim/akrion-soccer-engine-rs"
  "fiducia-cloud/fiducia-customer.rs"
  "fiducia-cloud/fiducia-marketing.web"
  "fiducia-cloud/fiducia-routing.rs"
  "fiducia-cloud/fiducia-node.rs"
  "fiducia-cloud/fiducia-brain.rs"
  "fiducia-cloud/fiducia-load-balance.rs"
  "fiducia-cloud/fiducia-node-sidecar.rs"
  "fiducia-cloud/fiducia-edge"
  "fiducia-cloud/fiducia-clients"
  "fiducia-cloud/fiducia-infra"
  "fiducia-cloud/fiducia-auth.rs"
  "fiducia-cloud/fiducia-telemetry.rs"
  "fiducia-cloud/fiducia-admin.rs"
  "fiducia-cloud/fiducia-interfaces"
  "fiducia-cloud/fiducia-cli.rs"
  "fiducia-cloud/fiducia-customer-ui.web"
  "fiducia-cloud/fiducia-monorepo"
  "fiducia-cloud/fiducia-test-config"
  "fiducia-cloud/fiducia-sync"
  "fiducia-cloud/fiducia-ai-agent-control-plane"
  "fiducia-cloud/fiducia-operations-control-plane"
  "fiducia-cloud/fiducia-ai-agent-bridge.rs"
  "fiducia-cloud/fiducia-e2e"
  "fiducia-cloud/fiducia-memory"
  "fiducia-cloud/fiducia-messaging"
  "fiducia-cloud/fiducia-memory.rs"
  "fiducia-cloud/fiducia-messaging.rs"
  "fiducia-cloud/fiducia-ai-agent-manager.rs"
  "fiducia-cloud/fiducia-lambda-service.rs"
  "fiducia-cloud/fiducia-mcp-server.rs"
  "fiducia-cloud/fiducia-cloud.github.io"
  "fiducia-cloud/fiducia-payments.rs"
  "declarative-migrations/declarative-postgres-migrate.rs"
  "declarative-migrations/declarative-migrations.github.io"
  "declarative-migrations/homebrew-tap"
  "quaestor-ledger/quaestor-ledger-server.rs"
  "quaestor-ledger/quaestor-ledger.github.io"
  "quaestor-ledger/quaestor-ledger-sync"
  "quaestor-ledger/quaestor-ledger-e2e"
  "quaestor-ledger/quaestor-executor"
  "sagitta-stack/dart-server"
  "claritas-viz/data-viz-server.rs"
  "discrete-event-systems/discrete-event-systems.github.io"
  "drone-mngr/laser-ptr-ctrl-server.rs"
  "drone-mngr/laser-ptr-ctrl-web-server.rs"
  "drone-mngr/laser-ptr-ctrl-embedded.rs"
  "drone-mngr/laser-ptr-ctrl-embedded.c"
  "drone-mngr/laser-ptr-ctrl-infra"
  "drone-mngr/laser-ptr-ctrl-monorepo"
  "drone-mngr/laser-ptr-ctrl-mcp-server.rs"
  "fifa-math/fifa-math.github.io"
  "zed-pkg-test/node-lib"
  "zed-pkg-test/node-app"
  "zed-pkg-test/rust-lib"
  "zed-pkg-test/rust-app"
  "zed-pkg-test/polyglot-lib"
  "zed-pkg-test/polyglot-go-app"
  "zed-pkg-test/polyglot-node-app"
  "zed-pkg-test/go-lib"
  "zed-pkg-test/go-app"
  "zed-pkg-test/python-lib"
  "zed-pkg-test/python-app"
  "zed-pkg-test/zed-pkg-e2e"
  "zed-pkg-test/dart-lib"
  "zed-pkg-test/dart-app"
  "zed-pkg-test/gleam-lib"
  "zed-pkg-test/gleam-app"
  "zed-pkg-test/awkward-lib"
  "zed-pkg-test/multiversion-lib"
  "zed-pkg-test/workspace-monorepo"
  "zed-pkg-test/shared-schema"
  "zed-pkg-test/submodule-consumer"
  "zed-pkg-test/subtree-consumer"
  "networking-components/ncc-dns-server"
  "networking-components/ncc-vpn"
  "networking-components/ncc-load-balancer"
  "networking-components/ncc-switch"
  "networking-components/ncc-router"
  "networking-components/ncc-e2e"
)

TOTAL=${#MISSING_REPOS[@]}
SUCCESS=0
FAIL=0
i=0

for entry in "${MISSING_REPOS[@]}"; do
  org="${entry%%/*}"
  repo="${entry#*/}"
  target="$BASE/$org/$repo"
  i=$((i + 1))

  # Create org directory if needed
  mkdir -p "$BASE/$org"

  echo "[$i/$TOTAL] Cloning $org/$repo -> $target"

  if git clone "https://github.com/$org/$repo.git" "$target" 2>&1; then
    echo "  OK: $org/$repo" | tee -a "$LOGFILE"
    SUCCESS=$((SUCCESS + 1))
  else
    echo "  FAIL: $org/$repo" | tee -a "$LOGFILE"
    FAIL=$((FAIL + 1))
  fi
done

echo ""
echo "========================================="
echo "Clone complete: $SUCCESS succeeded, $FAIL failed out of $TOTAL"
echo "========================================="
echo "SUMMARY: $SUCCESS/$TOTAL succeeded, $FAIL/$TOTAL failed" >> "$LOGFILE"
