-- Declarative Postgres schema contract for Athlet-O commerce services.
--
-- NAMESPACE: this targets the `athleto` database on the shared RDS instance,
-- not the shared pg-defs database in ../../schema.sql. Application processes
-- never run DDL at boot. Generate and review a dpm diff before applying it.
--
-- Rust consumers use hand-written SeaORM entities in the source-of-truth
-- athlet-o/athleto-app-rs repository. The numbered SQL migrations there are a
-- frozen audit trail; this file is the current desired schema.

create type product_format as enum ('cup', 'powder');
create type customer_type as enum ('b2c', 'b2b');
create type order_kind as enum ('one_time', 'recurring');
create type order_frequency as enum ('weekly', 'biweekly', 'monthly', 'quarterly');
create type order_status as enum ('placed', 'processing', 'fulfilled', 'cancelled');
create type order_channel as enum ('d2c_web', 'b2b_portal', 'b2b_api', 'edi');
create type trade_item_level as enum ('each', 'inner', 'case', 'pallet');
create type shipment_status as enum ('packing', 'shipped', 'delivered');
create type ship_method as enum ('standard', 'expedited', 'freight');
create type payment_provider as enum ('stripe', 'paypal', 'square', 'invoice');
create type payment_status as enum ('pending', 'processing', 'paid', 'invoiced', 'failed', 'refunded');
create type payment_kind as enum ('charge', 'subscription_cycle', 'refund');
create type subscription_status as enum ('pending', 'active', 'past_due', 'cancelled');

create table products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  subname text,
  description text not null,
  format product_format not null,
  calories integer not null,
  protein_g integer not null,
  price_cents integer not null,
  created_at timestamptz not null default now()
);

create table carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique,
  anon_id uuid unique,
  created_at timestamptz not null default now(),
  constraint carts_owner_present check (user_id is not null or anon_id is not null)
);

create table cart_items (
  id bigint generated by default as identity primary key,
  cart_id uuid not null references carts (id) on delete cascade,
  product_id bigint not null references products (id) on delete cascade,
  qty integer not null default 1 check (qty > 0),
  created_at timestamptz not null default now(),
  constraint cart_items_cart_product_uniq unique (cart_id, product_id)
);

create index cart_items_cart_id_idx on cart_items (cart_id);

create table customer_profiles (
  user_id uuid primary key,
  customer_type customer_type not null default 'b2c',
  company_name text,
  erp_contact_email text,
  b2b_approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint b2b_requires_company check (customer_type <> 'b2b' or company_name is not null)
);

create index customer_profiles_b2b_approval_idx
  on customer_profiles (b2b_approved_at)
  where b2b_approved_at is not null;

create table login_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text not null,
  aal text not null default 'aal1',
  created_at timestamptz not null default now()
);

create index login_events_user_idx on login_events (user_id, created_at desc);

create table inventory (
  product_id bigint primary key references products (id) on delete cascade,
  on_hand integer not null default 0 check (on_hand >= 0),
  updated_at timestamptz not null default now()
);

create table stock_holds (
  id bigint generated by default as identity primary key,
  cart_id uuid not null references carts (id) on delete cascade,
  product_id bigint not null references products (id) on delete cascade,
  qty integer not null check (qty > 0),
  held_until timestamptz not null,
  created_at timestamptz not null default now(),
  constraint stock_holds_cart_product_uniq unique (cart_id, product_id)
);

create index stock_holds_active_idx on stock_holds (product_id, held_until);

create table lots (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products (id),
  lot_number text not null,
  produced_at date,
  expiry_date date,
  qty_produced integer not null default 0,
  qty_available integer not null default 0,
  created_at timestamptz not null default now(),
  constraint lots_product_number_uniq unique (product_id, lot_number)
);

create table orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  kind order_kind not null default 'one_time',
  frequency order_frequency,
  status order_status not null default 'placed',
  channel order_channel not null default 'd2c_web',
  po_number text,
  ship_method ship_method not null default 'standard',
  subtotal_cents bigint not null default 0,
  shipping_cents bigint not null default 0,
  tax_cents bigint not null default 0,
  total_cents bigint not null default 0,
  next_run_at timestamptz,
  recurs_from uuid references orders (id),
  payment_provider payment_provider,
  payment_status payment_status not null default 'pending',
  payment_ref text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  constraint recurring_has_frequency check (kind <> 'recurring' or frequency is not null)
);

create index orders_user_idx on orders (user_id, created_at desc);

create table order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references orders (id) on delete cascade,
  product_id bigint not null references products (id),
  qty integer not null check (qty > 0),
  unit_price_cents integer not null,
  lot_id bigint references lots (id)
);

create index order_items_order_idx on order_items (order_id);

create table b2b_api_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  name text not null,
  key_hash text not null unique,
  prefix text not null,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create index b2b_api_keys_user_idx on b2b_api_keys (user_id);

create table trade_items (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products (id) on delete cascade,
  level trade_item_level not null,
  gtin text unique,
  qty_of_child integer,
  net_weight_g integer,
  gross_weight_g integer,
  length_mm integer,
  width_mm integer,
  height_mm integer,
  ti integer,
  hi integer,
  created_at timestamptz not null default now(),
  constraint trade_items_product_level_uniq unique (product_id, level)
);

create table shipments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders (id),
  status shipment_status not null default 'packing',
  carrier text,
  tracking_number text,
  ship_date date,
  eta_earliest date,
  eta_latest date,
  delivered_at timestamptz,
  asn_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index shipments_order_idx on shipments (order_id);

create table shipment_cartons (
  id bigint generated by default as identity primary key,
  shipment_id uuid not null references shipments (id) on delete cascade,
  sscc text unique,
  trade_item_id bigint references trade_items (id),
  lot_id bigint references lots (id),
  qty integer not null check (qty > 0)
);

create table edi_messages (
  id bigint generated by default as identity primary key,
  direction text not null check (direction in ('in', 'out')),
  doc_type text not null,
  partner text,
  order_id uuid references orders (id),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'received',
  created_at timestamptz not null default now()
);

create table payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references orders (id) on delete set null,
  user_id uuid not null,
  provider payment_provider not null,
  kind payment_kind not null default 'charge',
  provider_ref text not null,
  amount_cents bigint not null,
  currency text not null default 'USD',
  status payment_status not null default 'paid',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payments_provider_ref_uniq unique (provider, provider_ref)
);

create index payments_order_idx on payments (order_id);
create index payments_user_idx on payments (user_id);

create table payment_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  order_id uuid references orders (id) on delete set null,
  provider payment_provider not null,
  provider_ref text not null,
  status subscription_status not null default 'pending',
  frequency order_frequency not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_subscriptions_provider_ref_uniq unique (provider, provider_ref)
);

create index payment_subscriptions_user_idx on payment_subscriptions (user_id);

create table payment_events (
  provider payment_provider not null,
  event_id text not null,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  primary key (provider, event_id)
);

-- The service connects as the database owner and bypasses RLS. No table is
-- exposed directly as a public CRUD API, so no end-user policies are defined.
alter table products enable row level security;
alter table carts enable row level security;
alter table cart_items enable row level security;
alter table customer_profiles enable row level security;
alter table login_events enable row level security;
alter table inventory enable row level security;
alter table stock_holds enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table b2b_api_keys enable row level security;
alter table trade_items enable row level security;
alter table lots enable row level security;
alter table shipments enable row level security;
alter table shipment_cartons enable row level security;
alter table edi_messages enable row level security;
alter table payments enable row level security;
alter table payment_subscriptions enable row level security;
alter table payment_events enable row level security;
