apiVersion: v1
kind: ConfigMap
metadata:
  name: dd-promtail-config
  namespace: observability
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://dd-loki.observability.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-containers
        static_configs:
          - targets:
              - localhost
            labels:
              job: kubernetes-containers
              __path__: /var/log/containers/*.log
        pipeline_stages:
          - cri: {}
