use std::sync::atomic::Ordering;

use axum::{
    extract::{Form, Path, State},
    http::{header, HeaderMap, StatusCode},
    response::{Html, IntoResponse, Response},
    Json,
};
use maud::html;
use serde_json::json;

use crate::{
    ai::generate_ai_draft,
    auth::{auth_failure_response, require_auth, ui_auth_failure_response},
    claims::{audit_claims, ClaimCheckRequest},
    deadlines::{analyze_deadlines, DeadlineRequest},
    fees::{estimate_fees, Entity, FeeEstimateRequest},
    package::{build_package, build_search_plan, evaluate_readiness, intake_from_form},
    state::{get_package, package_snapshot, store_package, AppState},
    types::{
        example_request, finding, PackageReviewRequest, PackageReviewResponse,
        PatentIntakeRequest, UiPackageForm,
    },
    ui::{render_home, render_package_fragment},
    util::normalize_track,
    FEE_EFFECTIVE_DATE, SCHEMA_VERSION, SERVICE_NAME,
};

pub(crate) async fn root() -> Html<String> {
    Html(render_home().into_string())
}

pub(crate) async fn descriptor(State(state): State<AppState>) -> impl IntoResponse {
    Json(json!({
        "ok": true,
        "service": SERVICE_NAME,
        "schemaVersion": SCHEMA_VERSION,
        "patentCenterUrl": state.config.patent_center_url,
        "routes": {
            "home": "/",
            "package": "/packages/provisional",
            "readiness": "/readiness",
            "searchPlan": "/search/plan",
            "review": "/review/package",
            "claimsCheck": "/claims/check",
            "feesEstimate": "/fees/estimate",
            "deadlines": "/deadlines",
            "draftAi": "/draft/ai",
            "docs": "/docs/api"
        },
        "feeScheduleEffectiveDate": FEE_EFFECTIVE_DATE,
        "aiConfigured": state.config.anthropic_api_key.is_some(),
        "aiModel": state.config.ai_model,
        "stance": "preparation-only"
    }))
}

pub(crate) async fn schema() -> impl IntoResponse {
    Json(json!({
        "ok": true,
        "schemaVersion": SCHEMA_VERSION,
        "request": {
            "title": "string",
            "inventorNames": ["string"],
            "applicant": "string?",
            "inventionSummary": "string",
            "technicalField": "string?",
            "problem": "string",
            "solution": "string",
            "noveltyClaims": ["string"],
            "embodiments": ["string"],
            "alternatives": ["string"],
            "advantages": ["string"],
            "publicDisclosureDate": "YYYY-MM-DD?",
            "provisionalFilingDate": "YYYY-MM-DD?",
            "foreignPriorityDate": "YYYY-MM-DD?",
            "targetFiling": "provisional|non-provisional|design|pct",
            "entityStatus": "large|small|micro",
            "knownPriorArt": [{ "title": "string", "url": "string?", "notes": "string?" }],
            "attachments": [{ "name": "string", "kind": "string?", "url": "string?", "notes": "string?" }]
        },
        "response": {
            "readiness": "score, blockers, warnings, strengths, nextActions",
            "draft": "abstract, sections, claimSeeds, drawingPlan",
            "searchPlan": "queries, sources, classificationHints",
            "claimAudit": "claim counts, dependency validity, antecedent-basis advisories, abstract length",
            "feeEstimate": "USPTO fee line items by entity status (effective 2025-01-19)",
            "deadlines": "provisional/Paris/grace-period milestones with days remaining",
            "filingChecklist": "operator handoff checklist"
        },
        "auxiliaryEndpoints": {
            "claimsCheck": { "claims": ["string"], "abstract": "string?" },
            "feesEstimate": {
                "entityStatus": "large|small|micro",
                "filingTrack": "provisional|non-provisional|design|pct",
                "totalClaims": "number",
                "independentClaims": "number",
                "hasMultipleDependentClaim": "bool"
            },
            "deadlines": {
                "provisionalFilingDate": "YYYY-MM-DD?",
                "publicDisclosureDate": "YYYY-MM-DD?",
                "foreignPriorityDate": "YYYY-MM-DD?",
                "today": "YYYY-MM-DD?"
            },
            "draftAi": {
                "request": "same intake contract as /packages/provisional",
                "response": "abstract, claims, sections generated by Claude, then re-checked by /claims/check and priced; one automatic repair pass if the checker finds blockers",
                "requires": "ANTHROPIC_API_KEY"
            }
        }
    }))
}

pub(crate) async fn example() -> impl IntoResponse {
    Json(json!(example_request()))
}

pub(crate) async fn matters(State(state): State<AppState>, headers: HeaderMap) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    let matters = package_snapshot(&state);
    Json(json!({ "ok": true, "count": matters.len(), "matters": matters })).into_response()
}

pub(crate) async fn matter(
    State(state): State<AppState>,
    headers: HeaderMap,
    Path(matter_id): Path<String>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    match get_package(&state, &matter_id) {
        Some(package) => Json(package).into_response(),
        None => (
            StatusCode::NOT_FOUND,
            Json(json!({ "ok": false, "error": "matter not found" })),
        )
            .into_response(),
    }
}

pub(crate) async fn package_json(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<PatentIntakeRequest>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    match build_package(&state.config, request) {
        Ok(package) => {
            state
                .metrics
                .package_requests_total
                .fetch_add(1, Ordering::Relaxed);
            store_package(&state, package.clone());
            Json(package).into_response()
        }
        Err(error) => {
            state.metrics.errors_total.fetch_add(1, Ordering::Relaxed);
            (
                StatusCode::BAD_REQUEST,
                Json(json!({ "ok": false, "error": error })),
            )
                .into_response()
        }
    }
}

pub(crate) async fn package_form(
    State(state): State<AppState>,
    headers: HeaderMap,
    Form(form): Form<UiPackageForm>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return ui_auth_failure_response(&state, failure);
    }
    match build_package(&state.config, intake_from_form(form)) {
        Ok(package) => {
            state
                .metrics
                .package_requests_total
                .fetch_add(1, Ordering::Relaxed);
            store_package(&state, package.clone());
            Html(render_package_fragment(&package).into_string()).into_response()
        }
        Err(error) => {
            state.metrics.errors_total.fetch_add(1, Ordering::Relaxed);
            (
                StatusCode::BAD_REQUEST,
                Html(
                    html! {
                        div class="result error" { strong { "Package error" } p { (error) } }
                    }
                    .into_string(),
                ),
            )
                .into_response()
        }
    }
}

pub(crate) async fn readiness_json(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<PatentIntakeRequest>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    state
        .metrics
        .readiness_requests_total
        .fetch_add(1, Ordering::Relaxed);
    Json(json!({ "ok": true, "readiness": evaluate_readiness(&request) })).into_response()
}

pub(crate) async fn search_plan_json(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<PatentIntakeRequest>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    state
        .metrics
        .search_plan_requests_total
        .fetch_add(1, Ordering::Relaxed);
    Json(json!({ "ok": true, "searchPlan": build_search_plan(&request) })).into_response()
}

pub(crate) async fn claims_check_json(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<ClaimCheckRequest>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    state
        .metrics
        .claim_checks_total
        .fetch_add(1, Ordering::Relaxed);
    let audit = audit_claims(&request.claims, request.abstract_text.as_deref());
    Json(json!({ "ok": true, "claimAudit": audit })).into_response()
}

pub(crate) async fn fees_estimate_json(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<FeeEstimateRequest>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    state
        .metrics
        .fee_estimates_total
        .fetch_add(1, Ordering::Relaxed);
    let entity = Entity::parse(request.entity_status.as_deref());
    let track = normalize_track(request.filing_track.as_ref());
    let total_claims = request.total_claims.unwrap_or(0);
    let independent_claims = request.independent_claims.unwrap_or(1);
    let estimate = estimate_fees(
        entity,
        &track,
        total_claims,
        independent_claims,
        request.has_multiple_dependent_claim.unwrap_or(false),
    );
    Json(json!({ "ok": true, "feeEstimate": estimate })).into_response()
}

pub(crate) async fn deadlines_json(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<DeadlineRequest>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    state
        .metrics
        .deadline_requests_total
        .fetch_add(1, Ordering::Relaxed);
    let report = analyze_deadlines(
        request.provisional_filing_date.as_deref(),
        request.public_disclosure_date.as_deref(),
        request.foreign_priority_date.as_deref(),
        request.today.as_deref(),
    );
    Json(json!({ "ok": true, "deadlines": report })).into_response()
}

pub(crate) async fn draft_ai_json(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<PatentIntakeRequest>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    if state.config.anthropic_api_key.is_none() {
        return (
            StatusCode::SERVICE_UNAVAILABLE,
            Json(json!({
                "ok": false,
                "error": "AI drafting is not configured; set ANTHROPIC_API_KEY (or PATENT_FILING_ANTHROPIC_API_KEY)."
            })),
        )
            .into_response();
    }
    // Bound concurrent outbound model calls: caps resource use and Anthropic
    // spend, and stops a burst of expensive long-lived requests from piling up.
    let _permit = match state.ai_permits.try_acquire() {
        Ok(permit) => permit,
        Err(_) => {
            state
                .metrics
                .ai_throttled_total
                .fetch_add(1, Ordering::Relaxed);
            return (
                StatusCode::TOO_MANY_REQUESTS,
                [(header::RETRY_AFTER, "30")],
                Json(json!({
                    "ok": false,
                    "error": "AI drafting is at capacity; retry shortly."
                })),
            )
                .into_response();
        }
    };
    match generate_ai_draft(&state, request).await {
        Ok(response) => {
            state.metrics.ai_drafts_total.fetch_add(1, Ordering::Relaxed);
            Json(response).into_response()
        }
        Err(error) => {
            state
                .metrics
                .ai_draft_errors_total
                .fetch_add(1, Ordering::Relaxed);
            // 400 for validation problems, 502 for upstream model failures.
            let status = if error.contains("model") || error.contains("request to model") {
                StatusCode::BAD_GATEWAY
            } else {
                StatusCode::BAD_REQUEST
            };
            (status, Json(json!({ "ok": false, "error": error }))).into_response()
        }
    }
}

pub(crate) async fn review_package_json(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<PackageReviewRequest>,
) -> Response {
    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);
    if let Err(failure) = require_auth(&headers, &state) {
        return auth_failure_response(&state, failure);
    }
    let response = review_package(&state, request);
    state
        .metrics
        .package_reviews_total
        .fetch_add(1, Ordering::Relaxed);
    Json(response).into_response()
}

pub(crate) fn review_package(state: &AppState, request: PackageReviewRequest) -> PackageReviewResponse {
    let package = request
        .matter_id
        .as_deref()
        .and_then(|matter_id| get_package(state, matter_id));
    let input = request.package;
    let readiness_score = package
        .as_ref()
        .map(|package| package.readiness.score)
        .or_else(|| input.as_ref().and_then(|item| item.readiness_score))
        .unwrap_or(0);
    let blocker_count = package
        .as_ref()
        .map(|package| package.readiness.blockers.len())
        .or_else(|| input.as_ref().and_then(|item| item.blocker_count))
        .unwrap_or(0);
    let section_count = package
        .as_ref()
        .map(|package| package.draft.sections.len())
        .or_else(|| input.as_ref().and_then(|item| item.section_count))
        .unwrap_or(0);
    let checklist_open_count = package
        .as_ref()
        .map(|package| {
            package
                .filing_checklist
                .iter()
                .filter(|item| item.status == "open")
                .count()
        })
        .or_else(|| input.as_ref().and_then(|item| item.checklist_open_count))
        .unwrap_or(0);

    let mut findings = Vec::new();
    let mut next_actions = Vec::new();
    if blocker_count > 0 {
        findings.push(finding(
            "readiness-blockers",
            "blocker",
            "Resolve readiness blockers before package release.",
        ));
    }
    if readiness_score < 70 {
        findings.push(finding(
            "low-readiness-score",
            "warning",
            "Readiness score is below the drafting threshold.",
        ));
        next_actions.push("Expand the invention disclosure before counsel review.".to_string());
    }
    if section_count < 5 {
        findings.push(finding(
            "thin-specification",
            "warning",
            "Draft specification has fewer than five sections.",
        ));
    }
    if checklist_open_count > 0 {
        findings.push(finding(
            "open-checklist",
            "warning",
            "One or more filing checklist items remain open.",
        ));
    }
    next_actions.push("Review package with patent counsel before filing.".to_string());

    let release_gate = if blocker_count == 0 && readiness_score >= 82 && checklist_open_count <= 1 {
        "attorney-review-ready"
    } else if blocker_count == 0 && readiness_score >= 65 {
        "draft-revision-needed"
    } else {
        "blocked"
    };
    PackageReviewResponse {
        ok: true,
        status: if findings.iter().any(|item| item.severity == "blocker") {
            "blocked".to_string()
        } else {
            "reviewed".to_string()
        },
        release_gate: release_gate.to_string(),
        findings,
        next_actions,
    }
}

pub(crate) async fn healthz(State(state): State<AppState>) -> impl IntoResponse {
    let count = state
        .store
        .read()
        .unwrap_or_else(|lock| lock.into_inner())
        .matters
        .len();
    Json(json!({ "ok": true, "service": SERVICE_NAME, "matterCount": count }))
}

pub(crate) async fn readyz(State(state): State<AppState>) -> impl IntoResponse {
    Json(json!({
        "ok": state.config.allow_unauthenticated || state.config.server_auth_secret.is_some(),
        "service": SERVICE_NAME,
        "authConfigured": state.config.server_auth_secret.is_some(),
        "allowUnauthenticated": state.config.allow_unauthenticated,
        "patentCenterUrl": state.config.patent_center_url,
        "aiConfigured": state.config.anthropic_api_key.is_some()
    }))
}

pub(crate) async fn metrics(State(state): State<AppState>) -> Response {
    let matter_count = state
        .store
        .read()
        .unwrap_or_else(|lock| lock.into_inner())
        .matters
        .len();
    let body = format!(
        "# HELP dd_patent_filing_http_requests_total HTTP requests observed by the patent filing service.\n\
         # TYPE dd_patent_filing_http_requests_total counter\n\
         dd_patent_filing_http_requests_total {}\n\
         # HELP dd_patent_filing_package_requests_total Filing package generation requests accepted.\n\
         # TYPE dd_patent_filing_package_requests_total counter\n\
         dd_patent_filing_package_requests_total {}\n\
         # HELP dd_patent_filing_readiness_requests_total Readiness review requests accepted.\n\
         # TYPE dd_patent_filing_readiness_requests_total counter\n\
         dd_patent_filing_readiness_requests_total {}\n\
         # HELP dd_patent_filing_search_plan_requests_total Prior-art search plan requests accepted.\n\
         # TYPE dd_patent_filing_search_plan_requests_total counter\n\
         dd_patent_filing_search_plan_requests_total {}\n\
         # HELP dd_patent_filing_package_reviews_total Package review requests accepted.\n\
         # TYPE dd_patent_filing_package_reviews_total counter\n\
         dd_patent_filing_package_reviews_total {}\n\
         # HELP dd_patent_filing_claim_checks_total Claim formality check requests accepted.\n\
         # TYPE dd_patent_filing_claim_checks_total counter\n\
         dd_patent_filing_claim_checks_total {}\n\
         # HELP dd_patent_filing_fee_estimates_total Fee estimate requests accepted.\n\
         # TYPE dd_patent_filing_fee_estimates_total counter\n\
         dd_patent_filing_fee_estimates_total {}\n\
         # HELP dd_patent_filing_deadline_requests_total Filing deadline requests accepted.\n\
         # TYPE dd_patent_filing_deadline_requests_total counter\n\
         dd_patent_filing_deadline_requests_total {}\n\
         # HELP dd_patent_filing_ai_drafts_total AI drafting requests completed.\n\
         # TYPE dd_patent_filing_ai_drafts_total counter\n\
         dd_patent_filing_ai_drafts_total {}\n\
         # HELP dd_patent_filing_ai_draft_errors_total AI drafting requests that failed.\n\
         # TYPE dd_patent_filing_ai_draft_errors_total counter\n\
         dd_patent_filing_ai_draft_errors_total {}\n\
         # HELP dd_patent_filing_ai_throttled_total AI drafting requests rejected at the concurrency limit.\n\
         # TYPE dd_patent_filing_ai_throttled_total counter\n\
         dd_patent_filing_ai_throttled_total {}\n\
         # HELP dd_patent_filing_auth_failures_total Rejected requests with missing or invalid auth.\n\
         # TYPE dd_patent_filing_auth_failures_total counter\n\
         dd_patent_filing_auth_failures_total {}\n\
         # HELP dd_patent_filing_errors_total Request or package generation errors.\n\
         # TYPE dd_patent_filing_errors_total counter\n\
         dd_patent_filing_errors_total {}\n\
         # HELP dd_patent_filing_current_matters Current retained patent matter packages.\n\
         # TYPE dd_patent_filing_current_matters gauge\n\
         dd_patent_filing_current_matters {}\n",
        state.metrics.http_requests_total.load(Ordering::Relaxed),
        state.metrics.package_requests_total.load(Ordering::Relaxed),
        state.metrics.readiness_requests_total.load(Ordering::Relaxed),
        state.metrics.search_plan_requests_total.load(Ordering::Relaxed),
        state.metrics.package_reviews_total.load(Ordering::Relaxed),
        state.metrics.claim_checks_total.load(Ordering::Relaxed),
        state.metrics.fee_estimates_total.load(Ordering::Relaxed),
        state.metrics.deadline_requests_total.load(Ordering::Relaxed),
        state.metrics.ai_drafts_total.load(Ordering::Relaxed),
        state.metrics.ai_draft_errors_total.load(Ordering::Relaxed),
        state.metrics.ai_throttled_total.load(Ordering::Relaxed),
        state.metrics.auth_failures_total.load(Ordering::Relaxed),
        state.metrics.errors_total.load(Ordering::Relaxed),
        matter_count,
    );
    (
        [(
            axum::http::header::CONTENT_TYPE,
            "text/plain; version=0.0.4",
        )],
        body,
    )
        .into_response()
}

pub(crate) async fn api_docs_html() -> Html<&'static str> {
    Html(include_str!("../generated/api-docs.html"))
}

pub(crate) async fn api_docs_json() -> impl IntoResponse {
    (
        [("content-type", "application/json; charset=utf-8")],
        include_str!("../generated/api-docs.json"),
    )
}
