//! Build script for dd-soccer-rs.
//!
//! Embeds the vendored mermaid docs (`docs/*.md`) into the binary so the server
//! can serve them with zero runtime filesystem dependency. The docs are vendored
//! copies of `soccer-sim-game-engine.rs/docs/*.md`; refresh them with
//! `cp ../../submodules/soccer-sim-game-engine.rs/docs/*.md docs/` (or from the
//! engine working tree). New `*.md` files dropped in `docs/` are picked up
//! automatically — no code change required.
//!
//! It generates `docs_registry.rs` in `OUT_DIR`, exposing
//! `pub static DOC_PAGES: &[(&str /* slug */, &str /* markdown */)]`, each entry
//! `include_str!`-ing a copy staged in `OUT_DIR` (so the path is stable).

use std::{env, fs, path::Path};

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let docs_dir = Path::new(&manifest).join("docs");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    println!("cargo:rerun-if-changed=docs");

    let mut files: Vec<_> = fs::read_dir(&docs_dir)
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("md"))
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    files.sort();

    let mut registry = String::from(
        "/// (slug, markdown) for every vendored doc page, generated by build.rs.\n\
         pub static DOC_PAGES: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        let stem = path.file_stem().unwrap().to_string_lossy().into_owned();
        let file_name = path.file_name().unwrap().to_string_lossy().into_owned();
        let staged = Path::new(&out_dir).join(&file_name);
        fs::copy(path, &staged).expect("stage doc into OUT_DIR");
        println!("cargo:rerun-if-changed=docs/{file_name}");
        registry.push_str(&format!(
            "    ({stem:?}, include_str!(concat!(env!(\"OUT_DIR\"), \"/{file_name}\"))),\n"
        ));
    }
    registry.push_str("];\n");

    fs::write(Path::new(&out_dir).join("docs_registry.rs"), registry)
        .expect("write docs_registry.rs");
}
