package com.oresoftware.dd.sparkpipeline.handlers;

import com.oresoftware.dd.sparkpipeline.db.PgDb;
import dd.pgdefs.jooq.Tables;
import io.vertx.core.Handler;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.RoutingContext;
import org.jooq.DSLContext;
import org.jooq.Record;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * {@code GET /v1/repos} — list known git repositories from the canonical {@code known_git_repos}
 * table in the {@code dd_pg_defs} database.
 *
 * <p>Demonstrates how the spark-pipeline-server consumes the jOOQ {@code Tables} bindings
 * generated by {@code remote/libs/pg-defs}: every column referenced below comes from the
 * generated {@link dd.pgdefs.jooq.Tables} constants, so a schema change that drops or renames
 * a column fails the build instead of crashing at runtime.
 *
 * <p>Returns {@code 503} if {@code RDS_DATABASE_URL} was unset at startup — the service
 * intentionally degrades gracefully rather than crash-loop when Postgres is not configured.
 */
public final class ListReposHandler implements Handler<RoutingContext> {

  private static final Logger log = LoggerFactory.getLogger(ListReposHandler.class);

  private final Vertx vertx;
  private final PgDb pg;

  public ListReposHandler(final Vertx vertx, final PgDb pg) {
    this.vertx = vertx;
    this.pg = pg;
  }

  @Override
  public void handle(final RoutingContext ctx) {

    if (pg == null || pg.context().isEmpty()) {
      ctx.response()
          .setStatusCode(503)
          .putHeader("content-type", "application/json")
          .end("{\"error\":\"postgres_not_configured\"}");
      return;
    }

    final DSLContext dsl = pg.context().get();

    vertx.<JsonArray>executeBlocking((Promise<JsonArray> p) -> {
      try {
        // jOOQ's typed select(...) returns Result<RecordN<...>>; we iterate as Record so the
        // JSON serialisation logic below can treat every row uniformly.
        final JsonArray out = new JsonArray();
        dsl.select(
                Tables.KNOWN_GIT_REPOS_ID,
                Tables.KNOWN_GIT_REPOS_REPO_URL,
                Tables.KNOWN_GIT_REPOS_DISPLAY_NAME,
                Tables.KNOWN_GIT_REPOS_PROVIDER,
                Tables.KNOWN_GIT_REPOS_DEFAULT_BRANCH,
                Tables.KNOWN_GIT_REPOS_STATUS,
                Tables.KNOWN_GIT_REPOS_LAST_VERIFIED_AT,
                Tables.KNOWN_GIT_REPOS_CREATED_AT)
            .from(Tables.KNOWN_GIT_REPOS)
            .where(Tables.KNOWN_GIT_REPOS_IS_SOFT_DELETED.isFalse()
                .or(Tables.KNOWN_GIT_REPOS_IS_SOFT_DELETED.isNull()))
            .orderBy(Tables.KNOWN_GIT_REPOS_CREATED_AT.desc())
            .limit(500)
            .forEach((Record r) -> out.add(repoRowToJson(r)));
        p.complete(out);
      } catch (Exception e) {
        p.fail(e);
      }
    }, false).onComplete(ar -> {
      if (ar.succeeded()) {
        ctx.response()
            .putHeader("content-type", "application/json")
            .end(new JsonObject().put("repos", ar.result()).encode());
      } else {
        log.error("GET /v1/repos failed", ar.cause());
        ctx.response()
            .setStatusCode(500)
            .putHeader("content-type", "application/json")
            .end("{\"error\":\"db_query_failed\"}");
      }
    });
  }

  private static JsonObject repoRowToJson(final Record r) {
    final UUID id = r.get(Tables.KNOWN_GIT_REPOS_ID);
    final OffsetDateTime lastVerifiedAt = r.get(Tables.KNOWN_GIT_REPOS_LAST_VERIFIED_AT);
    final OffsetDateTime createdAt = r.get(Tables.KNOWN_GIT_REPOS_CREATED_AT);
    return new JsonObject()
        .put("id", id == null ? null : id.toString())
        .put("repoUrl", r.get(Tables.KNOWN_GIT_REPOS_REPO_URL))
        .put("displayName", r.get(Tables.KNOWN_GIT_REPOS_DISPLAY_NAME))
        .put("provider", r.get(Tables.KNOWN_GIT_REPOS_PROVIDER))
        .put("defaultBranch", r.get(Tables.KNOWN_GIT_REPOS_DEFAULT_BRANCH))
        .put("status", r.get(Tables.KNOWN_GIT_REPOS_STATUS))
        .put("lastVerifiedAt", lastVerifiedAt == null ? null : lastVerifiedAt.toString())
        .put("createdAt", createdAt == null ? null : createdAt.toString());
  }
}
