apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - dd-vpn.serviceaccount.yaml
  - dd-vpn.configmap.yaml
  - dd-vpn-secrets.externalsecret.yaml
  - dd-vpn.pv.yaml
  - dd-vpn.pvc.yaml
  - dd-vpn.deployment.yaml
  - dd-vpn-ui.service.yaml
  - dd-vpn.networkpolicy.yaml
  - dd-bastion-rbac.yaml
  - dd-bastion-secrets.externalsecret.yaml
  - dd-bastion.deployment.yaml
  - dd-bastion.service.yaml
  - dd-bastion.networkpolicy.yaml
