use std::sync::atomic::{AtomicU64, Ordering};

#[derive(Default)]
pub struct Metrics {
    pub http_requests_total: Counter,
    pub audit_submitted_total: Counter,
    pub audit_completed_total: Counter,
    pub audit_failed_total: Counter,
    pub standards_evaluated_total: Counter,
    pub findings_total: Counter,
    pub diagrams_generated_total: Counter,
    pub malware_scans_total: Counter,
    pub dependency_audits_total: Counter,
    pub secret_scans_total: Counter,
    pub fraud_checks_total: Counter,
    pub bot_checks_total: Counter,
    pub login_anomaly_checks_total: Counter,
    pub risk_findings_total: Counter,
    pub analyses_rejected_total: Counter,
    pub auth_failures_total: Counter,
    pub errors_total: Counter,
}

#[derive(Default)]
pub struct Counter(AtomicU64);

impl Counter {
    pub fn fetch_add(&self, value: u64) -> u64 {
        self.0.fetch_add(value, Ordering::Relaxed)
    }

    pub fn get(&self) -> u64 {
        self.0.load(Ordering::Relaxed)
    }
}

impl Metrics {
    pub fn render_prometheus(&self) -> String {
        let values = [
            (
                "dd_compliance_http_requests_total",
                "HTTP requests handled by dd-compliance-rs.",
                self.http_requests_total.get(),
            ),
            (
                "dd_compliance_audit_submitted_total",
                "Compliance audit jobs accepted.",
                self.audit_submitted_total.get(),
            ),
            (
                "dd_compliance_audit_completed_total",
                "Compliance audit jobs completed.",
                self.audit_completed_total.get(),
            ),
            (
                "dd_compliance_audit_failed_total",
                "Compliance audit jobs failed.",
                self.audit_failed_total.get(),
            ),
            (
                "dd_compliance_standards_evaluated_total",
                "Compliance standards evaluated across audit jobs.",
                self.standards_evaluated_total.get(),
            ),
            (
                "dd_compliance_findings_total",
                "Compliance findings emitted across audit jobs.",
                self.findings_total.get(),
            ),
            (
                "dd_compliance_diagrams_generated_total",
                "Infrastructure diagrams generated by dd-compliance-rs.",
                self.diagrams_generated_total.get(),
            ),
            (
                "dd_compliance_malware_scans_total",
                "Malware indicator scans performed.",
                self.malware_scans_total.get(),
            ),
            (
                "dd_compliance_dependency_audits_total",
                "Dependency manifest audits performed.",
                self.dependency_audits_total.get(),
            ),
            (
                "dd_compliance_secret_scans_total",
                "Secret leak scans performed.",
                self.secret_scans_total.get(),
            ),
            (
                "dd_compliance_fraud_checks_total",
                "Transaction fraud screens performed.",
                self.fraud_checks_total.get(),
            ),
            (
                "dd_compliance_bot_checks_total",
                "Automated-traffic (bot) screens performed.",
                self.bot_checks_total.get(),
            ),
            (
                "dd_compliance_login_anomaly_checks_total",
                "Login anomaly screens performed.",
                self.login_anomaly_checks_total.get(),
            ),
            (
                "dd_compliance_risk_findings_total",
                "Risk findings emitted across scanner and behavioral analyzers.",
                self.risk_findings_total.get(),
            ),
            (
                "dd_compliance_analyses_rejected_total",
                "Scanner/behavioral analysis requests rejected because the concurrency gate was saturated.",
                self.analyses_rejected_total.get(),
            ),
            (
                "dd_compliance_auth_failures_total",
                "Rejected authenticated requests.",
                self.auth_failures_total.get(),
            ),
            (
                "dd_compliance_errors_total",
                "Unhandled or internal service errors.",
                self.errors_total.get(),
            ),
        ];
        let mut output = String::new();
        for (name, help, value) in values {
            output.push_str("# HELP ");
            output.push_str(name);
            output.push(' ');
            output.push_str(help);
            output.push('\n');
            output.push_str("# TYPE ");
            output.push_str(name);
            output.push_str(" counter\n");
            output.push_str(name);
            output.push(' ');
            output.push_str(&value.to_string());
            output.push('\n');
        }
        output
    }
}
