use serde::Serialize;

use crate::util::normalize_key;

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ControlDef {
    pub id: &'static str,
    pub name: &'static str,
    pub family: &'static str,
    pub keywords: &'static [&'static str],
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StandardDef {
    pub id: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub jurisdiction: &'static str,
    pub description: &'static str,
    pub aliases: &'static [&'static str],
    pub controls: &'static [&'static str],
}

pub const CONTROL_CATALOG: &[ControlDef] = &[
    ControlDef {
        id: "governance_policy",
        name: "Governance and policy ownership",
        family: "governance",
        keywords: &[
            "policy",
            "board",
            "governance",
            "owner",
            "management review",
        ],
    },
    ControlDef {
        id: "risk_assessment",
        name: "Risk assessment and treatment",
        family: "governance",
        keywords: &[
            "risk assessment",
            "risk register",
            "threat model",
            "risk treatment",
        ],
    },
    ControlDef {
        id: "asset_inventory",
        name: "Asset, system, and data inventory",
        family: "inventory",
        keywords: &[
            "asset inventory",
            "cmdb",
            "data inventory",
            "system inventory",
        ],
    },
    ControlDef {
        id: "data_classification",
        name: "Data classification and handling",
        family: "data",
        keywords: &[
            "classification",
            "confidential",
            "restricted data",
            "sensitive data",
        ],
    },
    ControlDef {
        id: "access_control",
        name: "Access control and least privilege",
        family: "identity",
        keywords: &[
            "least privilege",
            "access review",
            "rbac",
            "mfa",
            "role based",
        ],
    },
    ControlDef {
        id: "identity_lifecycle",
        name: "Identity lifecycle and joiner-mover-leaver controls",
        family: "identity",
        keywords: &[
            "provisioning",
            "deprovisioning",
            "joiner",
            "mover",
            "leaver",
        ],
    },
    ControlDef {
        id: "encryption",
        name: "Encryption and key management",
        family: "cryptography",
        keywords: &[
            "encryption",
            "kms",
            "tls",
            "key rotation",
            "at rest",
            "in transit",
        ],
    },
    ControlDef {
        id: "logging_monitoring",
        name: "Logging, monitoring, and alerting",
        family: "observability",
        keywords: &[
            "logging",
            "monitoring",
            "alert",
            "audit log",
            "siem",
            "loki",
        ],
    },
    ControlDef {
        id: "incident_response",
        name: "Incident response and breach handling",
        family: "operations",
        keywords: &[
            "incident response",
            "breach",
            "postmortem",
            "runbook",
            "tabletop",
        ],
    },
    ControlDef {
        id: "vulnerability_management",
        name: "Vulnerability and patch management",
        family: "security",
        keywords: &[
            "vulnerability",
            "patch",
            "cve",
            "dependency scan",
            "sast",
            "dast",
        ],
    },
    ControlDef {
        id: "secure_sdlc",
        name: "Secure SDLC and change review",
        family: "engineering",
        keywords: &[
            "secure sdlc",
            "code review",
            "pull request",
            "ci",
            "change control",
        ],
    },
    ControlDef {
        id: "vendor_management",
        name: "Vendor and third-party risk management",
        family: "third_party",
        keywords: &[
            "vendor",
            "third party",
            "subprocessor",
            "supplier",
            "due diligence",
        ],
    },
    ControlDef {
        id: "privacy_notices",
        name: "Privacy notices and lawful basis disclosure",
        family: "privacy",
        keywords: &["privacy notice", "privacy policy", "lawful basis", "notice"],
    },
    ControlDef {
        id: "data_subject_rights",
        name: "Data subject and consumer rights workflow",
        family: "privacy",
        keywords: &[
            "data subject",
            "dsar",
            "delete request",
            "access request",
            "opt out",
        ],
    },
    ControlDef {
        id: "consent_basis",
        name: "Consent, authorization, and processing basis",
        family: "privacy",
        keywords: &[
            "consent",
            "authorization",
            "processing basis",
            "purpose limitation",
        ],
    },
    ControlDef {
        id: "retention_deletion",
        name: "Retention, deletion, and minimization",
        family: "privacy",
        keywords: &["retention", "deletion", "minimization", "data lifecycle"],
    },
    ControlDef {
        id: "backup_recovery",
        name: "Backup, restore, and recovery testing",
        family: "resilience",
        keywords: &["backup", "restore", "recovery", "rpo", "rto"],
    },
    ControlDef {
        id: "business_continuity",
        name: "Business continuity and disaster recovery",
        family: "resilience",
        keywords: &[
            "business continuity",
            "disaster recovery",
            "bcdr",
            "continuity",
        ],
    },
    ControlDef {
        id: "change_management",
        name: "Change management and release controls",
        family: "operations",
        keywords: &[
            "change management",
            "release",
            "approval",
            "deployment gate",
        ],
    },
    ControlDef {
        id: "audit_trail",
        name: "Audit trail and evidence retention",
        family: "audit",
        keywords: &["audit trail", "evidence", "retention", "traceability"],
    },
    ControlDef {
        id: "network_security",
        name: "Network security and segmentation",
        family: "network",
        keywords: &[
            "network policy",
            "segmentation",
            "firewall",
            "waf",
            "ingress",
        ],
    },
    ControlDef {
        id: "physical_security",
        name: "Physical and environmental security",
        family: "facilities",
        keywords: &["physical security", "badge", "visitor", "datacenter"],
    },
    ControlDef {
        id: "training_awareness",
        name: "Security and compliance training",
        family: "people",
        keywords: &["training", "awareness", "phishing", "workforce"],
    },
    ControlDef {
        id: "financial_controls",
        name: "Financial reporting and control integrity",
        family: "finance",
        keywords: &[
            "financial controls",
            "reconciliation",
            "segregation of duties",
            "sox",
        ],
    },
    ControlDef {
        id: "payment_security",
        name: "Payment-card and transaction security",
        family: "payments",
        keywords: &["pci", "cardholder", "payment", "pan", "tokenization"],
    },
    ControlDef {
        id: "healthcare_phi",
        name: "Protected health information safeguards",
        family: "healthcare",
        keywords: &[
            "phi",
            "hipaa",
            "patient",
            "covered entity",
            "business associate",
        ],
    },
    ControlDef {
        id: "clinical_safety",
        name: "Clinical, medical-device, and regulated records safety",
        family: "healthcare",
        keywords: &[
            "clinical",
            "medical device",
            "part 11",
            "validation",
            "electronic record",
        ],
    },
    ControlDef {
        id: "government_boundary",
        name: "Government authorization boundary and controlled systems",
        family: "government",
        keywords: &["ato", "authorization boundary", "fisma", "fedramp", "cjis"],
    },
    ControlDef {
        id: "export_controls",
        name: "Export-controlled technology handling",
        family: "government",
        keywords: &["itar", "ear", "export control", "controlled technology"],
    },
    ControlDef {
        id: "ai_risk_management",
        name: "AI risk management and impact assessment",
        family: "ai",
        keywords: &["ai risk", "impact assessment", "high-risk ai", "model card"],
    },
    ControlDef {
        id: "model_governance",
        name: "Model governance, monitoring, and human oversight",
        family: "ai",
        keywords: &["model governance", "human oversight", "drift", "evaluation"],
    },
    ControlDef {
        id: "quality_management",
        name: "Quality management system",
        family: "quality",
        keywords: &[
            "quality management",
            "qms",
            "corrective action",
            "customer satisfaction",
        ],
    },
    ControlDef {
        id: "service_management",
        name: "IT service management",
        family: "operations",
        keywords: &[
            "service management",
            "sla",
            "service desk",
            "incident queue",
        ],
    },
    ControlDef {
        id: "environmental_management",
        name: "Environmental management system",
        family: "environment",
        keywords: &[
            "environmental management",
            "emissions",
            "waste",
            "iso 14001",
        ],
    },
    ControlDef {
        id: "sustainability_reporting",
        name: "Sustainability and ESG reporting",
        family: "environment",
        keywords: &[
            "sustainability",
            "esg",
            "tcfd",
            "gri",
            "climate risk",
            "csrd",
        ],
    },
];

pub const STANDARDS: &[StandardDef] = &[
    StandardDef {
        id: "hipaa",
        name: "HIPAA",
        category: "healthcare",
        jurisdiction: "United States",
        description: "US healthcare privacy and security regulation for protected health information.",
        aliases: &["health insurance portability and accountability act"],
        controls: &["governance_policy", "risk_assessment", "access_control", "encryption", "logging_monitoring", "incident_response", "vendor_management", "healthcare_phi", "audit_trail", "training_awareness"],
    },
    StandardDef {
        id: "soc-2",
        name: "SOC 2",
        category: "security",
        jurisdiction: "Global / US audit market",
        description: "Trust Services Criteria reporting framework for service organizations.",
        aliases: &["soc2", "soc ii"],
        controls: &["governance_policy", "risk_assessment", "access_control", "logging_monitoring", "incident_response", "vulnerability_management", "secure_sdlc", "vendor_management", "backup_recovery", "audit_trail"],
    },
    StandardDef {
        id: "fedramp",
        name: "FedRAMP",
        category: "government",
        jurisdiction: "United States",
        description: "US federal cloud authorization program based on NIST SP 800-53 controls.",
        aliases: &["federal risk and authorization management program"],
        controls: &["governance_policy", "risk_assessment", "asset_inventory", "access_control", "encryption", "logging_monitoring", "incident_response", "vulnerability_management", "network_security", "government_boundary", "audit_trail"],
    },
    StandardDef {
        id: "nist-csf",
        name: "NIST Cybersecurity Framework",
        category: "security",
        jurisdiction: "United States / global",
        description: "NIST security framework organized around identify, protect, detect, respond, and recover outcomes.",
        aliases: &["nist", "nist csf", "cybersecurity framework"],
        controls: &["governance_policy", "risk_assessment", "asset_inventory", "access_control", "logging_monitoring", "incident_response", "vulnerability_management", "network_security", "backup_recovery"],
    },
    StandardDef {
        id: "nist-800-53",
        name: "NIST SP 800-53",
        category: "government",
        jurisdiction: "United States",
        description: "Security and privacy control catalog used by US federal systems and FedRAMP baselines.",
        aliases: &["nist sp 800-53", "800-53"],
        controls: &["governance_policy", "risk_assessment", "asset_inventory", "access_control", "identity_lifecycle", "encryption", "logging_monitoring", "incident_response", "vulnerability_management", "network_security", "physical_security", "audit_trail"],
    },
    StandardDef {
        id: "gdpr",
        name: "GDPR",
        category: "privacy",
        jurisdiction: "European Union",
        description: "EU privacy regulation for personal data processing.",
        aliases: &["eu gdpr", "general data protection regulation"],
        controls: &["governance_policy", "data_classification", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "vendor_management", "incident_response", "encryption", "audit_trail"],
    },
    StandardDef {
        id: "iso-27001",
        name: "ISO/IEC 27001",
        category: "security",
        jurisdiction: "Global",
        description: "Information security management system standard.",
        aliases: &["iso iec 27001", "iso27001"],
        controls: &["governance_policy", "risk_assessment", "asset_inventory", "access_control", "encryption", "logging_monitoring", "incident_response", "vulnerability_management", "vendor_management", "business_continuity", "audit_trail"],
    },
    StandardDef {
        id: "iso-27017",
        name: "ISO/IEC 27017",
        category: "security",
        jurisdiction: "Global",
        description: "Cloud-specific information security controls.",
        aliases: &["iso iec 27017", "iso27017"],
        controls: &["governance_policy", "asset_inventory", "access_control", "encryption", "logging_monitoring", "vendor_management", "network_security", "secure_sdlc"],
    },
    StandardDef {
        id: "iso-27018",
        name: "ISO/IEC 27018",
        category: "privacy",
        jurisdiction: "Global",
        description: "Personal data protection controls for public cloud processors.",
        aliases: &["iso iec 27018", "iso27018"],
        controls: &["governance_policy", "data_classification", "privacy_notices", "consent_basis", "retention_deletion", "vendor_management", "encryption", "audit_trail"],
    },
    StandardDef {
        id: "iso-27701",
        name: "ISO/IEC 27701",
        category: "privacy",
        jurisdiction: "Global",
        description: "Privacy information management extension to ISO/IEC 27001.",
        aliases: &["iso iec 27701", "iso27701"],
        controls: &["governance_policy", "risk_assessment", "data_classification", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "vendor_management", "audit_trail"],
    },
    StandardDef {
        id: "cis-controls",
        name: "CIS Controls",
        category: "security",
        jurisdiction: "Global",
        description: "Prioritized cybersecurity safeguards from the Center for Internet Security.",
        aliases: &["cis", "cis critical security controls"],
        controls: &["asset_inventory", "access_control", "encryption", "logging_monitoring", "vulnerability_management", "secure_sdlc", "network_security", "backup_recovery"],
    },
    StandardDef {
        id: "cyber-essentials",
        name: "Cyber Essentials",
        category: "security",
        jurisdiction: "United Kingdom",
        description: "UK baseline cybersecurity certification scheme.",
        aliases: &["uk cyber essentials"],
        controls: &["asset_inventory", "access_control", "vulnerability_management", "network_security", "secure_sdlc"],
    },
    StandardDef {
        id: "essential-eight",
        name: "Essential Eight",
        category: "security",
        jurisdiction: "Australia",
        description: "Australian baseline mitigation strategies for cyber resilience.",
        aliases: &["australian essential eight", "e8"],
        controls: &["access_control", "vulnerability_management", "secure_sdlc", "backup_recovery", "logging_monitoring"],
    },
    StandardDef {
        id: "tisax",
        name: "TISAX",
        category: "security",
        jurisdiction: "Automotive / Europe",
        description: "Automotive-sector information security assessment exchange.",
        aliases: &["trusted information security assessment exchange"],
        controls: &["governance_policy", "risk_assessment", "access_control", "vendor_management", "physical_security", "audit_trail", "training_awareness"],
    },
    StandardDef {
        id: "cmmc",
        name: "CMMC",
        category: "government",
        jurisdiction: "United States defense industrial base",
        description: "Cybersecurity Maturity Model Certification for defense contractors.",
        aliases: &["cybersecurity maturity model certification"],
        controls: &["governance_policy", "risk_assessment", "access_control", "logging_monitoring", "incident_response", "vulnerability_management", "network_security", "government_boundary", "training_awareness"],
    },
    StandardDef {
        id: "ccpa",
        name: "CCPA",
        category: "privacy",
        jurisdiction: "California",
        description: "California consumer privacy law.",
        aliases: &["california consumer privacy act"],
        controls: &["privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "vendor_management", "audit_trail"],
    },
    StandardDef {
        id: "cpra",
        name: "CPRA",
        category: "privacy",
        jurisdiction: "California",
        description: "California Privacy Rights Act amendments and obligations.",
        aliases: &["california privacy rights act"],
        controls: &["privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "data_classification", "vendor_management", "audit_trail"],
    },
    StandardDef {
        id: "lgpd",
        name: "LGPD",
        category: "privacy",
        jurisdiction: "Brazil",
        description: "Brazilian general personal data protection law.",
        aliases: &["lei geral de protecao de dados"],
        controls: &["governance_policy", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "incident_response", "vendor_management"],
    },
    StandardDef {
        id: "pipeda",
        name: "PIPEDA",
        category: "privacy",
        jurisdiction: "Canada",
        description: "Canadian private-sector personal information protection law.",
        aliases: &["personal information protection and electronic documents act"],
        controls: &["governance_policy", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "vendor_management", "training_awareness"],
    },
    StandardDef {
        id: "pdpa-sg",
        name: "PDPA (Singapore)",
        category: "privacy",
        jurisdiction: "Singapore",
        description: "Singapore personal data protection law.",
        aliases: &["pdpa singapore", "singapore pdpa"],
        controls: &["governance_policy", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "incident_response", "vendor_management"],
    },
    StandardDef {
        id: "pdpa-th",
        name: "PDPA (Thailand)",
        category: "privacy",
        jurisdiction: "Thailand",
        description: "Thailand personal data protection law.",
        aliases: &["pdpa thailand", "thailand pdpa"],
        controls: &["governance_policy", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "incident_response", "vendor_management"],
    },
    StandardDef {
        id: "privacy-act-1988",
        name: "Privacy Act 1988",
        category: "privacy",
        jurisdiction: "Australia",
        description: "Australian privacy law and Australian Privacy Principles.",
        aliases: &["australian privacy act"],
        controls: &["governance_policy", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "vendor_management"],
    },
    StandardDef {
        id: "uk-gdpr",
        name: "UK GDPR",
        category: "privacy",
        jurisdiction: "United Kingdom",
        description: "UK retained GDPR privacy obligations.",
        aliases: &["united kingdom gdpr"],
        controls: &["governance_policy", "data_classification", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "vendor_management", "incident_response", "encryption"],
    },
    StandardDef {
        id: "data-protection-act-2018",
        name: "Data Protection Act 2018",
        category: "privacy",
        jurisdiction: "United Kingdom",
        description: "UK data protection legislation complementing UK GDPR.",
        aliases: &["uk data protection act"],
        controls: &["governance_policy", "privacy_notices", "data_subject_rights", "consent_basis", "retention_deletion", "incident_response", "vendor_management"],
    },
    StandardDef {
        id: "pci-dss",
        name: "PCI DSS",
        category: "payments",
        jurisdiction: "Global payment-card ecosystem",
        description: "Payment Card Industry Data Security Standard.",
        aliases: &["pci", "payment card industry data security standard"],
        controls: &["asset_inventory", "access_control", "encryption", "logging_monitoring", "vulnerability_management", "network_security", "payment_security", "audit_trail"],
    },
    StandardDef {
        id: "swift-csp",
        name: "SWIFT CSP",
        category: "payments",
        jurisdiction: "Global financial messaging",
        description: "SWIFT Customer Security Programme controls.",
        aliases: &["swift customer security programme", "swift customer security program"],
        controls: &["governance_policy", "access_control", "logging_monitoring", "vulnerability_management", "network_security", "incident_response", "financial_controls"],
    },
    StandardDef {
        id: "psd2",
        name: "PSD2",
        category: "payments",
        jurisdiction: "European Union",
        description: "EU payment services directive.",
        aliases: &["payment services directive 2"],
        controls: &["governance_policy", "access_control", "encryption", "incident_response", "payment_security", "privacy_notices", "audit_trail"],
    },
    StandardDef {
        id: "sox",
        name: "SOX",
        category: "financial-services",
        jurisdiction: "United States",
        description: "Sarbanes-Oxley financial reporting controls.",
        aliases: &["sarbanes oxley", "sarbanes-oxley"],
        controls: &["governance_policy", "access_control", "change_management", "audit_trail", "financial_controls", "vendor_management"],
    },
    StandardDef {
        id: "glba",
        name: "GLBA",
        category: "financial-services",
        jurisdiction: "United States",
        description: "US financial privacy and safeguards law.",
        aliases: &["gramm leach bliley act"],
        controls: &["governance_policy", "risk_assessment", "privacy_notices", "access_control", "encryption", "incident_response", "vendor_management", "financial_controls"],
    },
    StandardDef {
        id: "basel-iii",
        name: "Basel III",
        category: "financial-services",
        jurisdiction: "Global banking",
        description: "Banking capital, liquidity, and operational risk framework.",
        aliases: &["basel 3"],
        controls: &["governance_policy", "risk_assessment", "financial_controls", "business_continuity", "audit_trail"],
    },
    StandardDef {
        id: "hitech",
        name: "HITECH Act",
        category: "healthcare",
        jurisdiction: "United States",
        description: "US health information technology and breach notification law.",
        aliases: &["hitech act"],
        controls: &["healthcare_phi", "incident_response", "access_control", "encryption", "audit_trail", "vendor_management"],
    },
    StandardDef {
        id: "hitrust-csf",
        name: "HITRUST CSF",
        category: "healthcare",
        jurisdiction: "Global healthcare market",
        description: "Healthcare-focused certifiable security and privacy control framework.",
        aliases: &["hitrust"],
        controls: &["governance_policy", "risk_assessment", "access_control", "encryption", "logging_monitoring", "incident_response", "vulnerability_management", "healthcare_phi", "vendor_management", "audit_trail"],
    },
    StandardDef {
        id: "fda-21-cfr-part-11",
        name: "FDA 21 CFR Part 11",
        category: "healthcare",
        jurisdiction: "United States",
        description: "US FDA electronic records and signatures rule.",
        aliases: &["21 cfr part 11", "part 11"],
        controls: &["governance_policy", "access_control", "identity_lifecycle", "audit_trail", "change_management", "clinical_safety", "training_awareness"],
    },
    StandardDef {
        id: "mdr",
        name: "MDR",
        category: "healthcare",
        jurisdiction: "European Union",
        description: "EU Medical Device Regulation.",
        aliases: &["medical device regulation", "eu mdr"],
        controls: &["governance_policy", "risk_assessment", "quality_management", "clinical_safety", "incident_response", "audit_trail", "vendor_management"],
    },
    StandardDef {
        id: "nis2",
        name: "NIS2",
        category: "government-critical-infrastructure",
        jurisdiction: "European Union",
        description: "EU network and information security directive for essential and important entities.",
        aliases: &["nis 2", "network and information security directive"],
        controls: &["governance_policy", "risk_assessment", "access_control", "incident_response", "vulnerability_management", "business_continuity", "network_security", "vendor_management"],
    },
    StandardDef {
        id: "fisma",
        name: "FISMA",
        category: "government",
        jurisdiction: "United States",
        description: "US federal information security management requirements.",
        aliases: &["federal information security management act"],
        controls: &["governance_policy", "risk_assessment", "asset_inventory", "access_control", "logging_monitoring", "incident_response", "government_boundary", "audit_trail"],
    },
    StandardDef {
        id: "cjis-security-policy",
        name: "CJIS Security Policy",
        category: "government",
        jurisdiction: "United States",
        description: "Criminal Justice Information Services security policy.",
        aliases: &["cjis", "cjis policy"],
        controls: &["governance_policy", "access_control", "encryption", "logging_monitoring", "network_security", "physical_security", "training_awareness", "government_boundary"],
    },
    StandardDef {
        id: "itar",
        name: "ITAR",
        category: "government",
        jurisdiction: "United States",
        description: "International Traffic in Arms Regulations for defense articles and technical data.",
        aliases: &["international traffic in arms regulations"],
        controls: &["governance_policy", "access_control", "data_classification", "export_controls", "physical_security", "audit_trail", "training_awareness"],
    },
    StandardDef {
        id: "ear",
        name: "EAR",
        category: "government",
        jurisdiction: "United States",
        description: "Export Administration Regulations for dual-use items and technology.",
        aliases: &["export administration regulations"],
        controls: &["governance_policy", "access_control", "data_classification", "export_controls", "vendor_management", "audit_trail", "training_awareness"],
    },
    StandardDef {
        id: "eu-ai-act",
        name: "EU AI Act",
        category: "ai",
        jurisdiction: "European Union",
        description: "EU risk-based artificial intelligence regulation.",
        aliases: &["ai act", "european union ai act"],
        controls: &["governance_policy", "risk_assessment", "data_classification", "ai_risk_management", "model_governance", "audit_trail", "privacy_notices"],
    },
    StandardDef {
        id: "iso-42001",
        name: "ISO/IEC 42001",
        category: "ai",
        jurisdiction: "Global",
        description: "AI management system standard.",
        aliases: &["iso iec 42001", "iso42001"],
        controls: &["governance_policy", "risk_assessment", "ai_risk_management", "model_governance", "quality_management", "audit_trail"],
    },
    StandardDef {
        id: "nist-ai-rmf",
        name: "NIST AI RMF",
        category: "ai",
        jurisdiction: "United States / global",
        description: "NIST artificial intelligence risk management framework.",
        aliases: &["ai rmf", "nist artificial intelligence risk management framework"],
        controls: &["governance_policy", "risk_assessment", "ai_risk_management", "model_governance", "logging_monitoring", "audit_trail"],
    },
    StandardDef {
        id: "iso-9001",
        name: "ISO 9001",
        category: "quality",
        jurisdiction: "Global",
        description: "Quality management system standard.",
        aliases: &["iso9001"],
        controls: &["governance_policy", "quality_management", "training_awareness", "change_management", "audit_trail", "vendor_management"],
    },
    StandardDef {
        id: "iso-22301",
        name: "ISO 22301",
        category: "resilience",
        jurisdiction: "Global",
        description: "Business continuity management system standard.",
        aliases: &["iso22301"],
        controls: &["governance_policy", "risk_assessment", "business_continuity", "backup_recovery", "incident_response", "training_awareness", "audit_trail"],
    },
    StandardDef {
        id: "iso-31000",
        name: "ISO 31000",
        category: "risk",
        jurisdiction: "Global",
        description: "Risk management guidelines.",
        aliases: &["iso31000"],
        controls: &["governance_policy", "risk_assessment", "audit_trail", "training_awareness"],
    },
    StandardDef {
        id: "iso-20000",
        name: "ISO 20000",
        category: "service-management",
        jurisdiction: "Global",
        description: "IT service management standard.",
        aliases: &["iso20000", "iso iec 20000"],
        controls: &["governance_policy", "service_management", "incident_response", "change_management", "business_continuity", "audit_trail"],
    },
    StandardDef {
        id: "iso-14001",
        name: "ISO 14001",
        category: "environment",
        jurisdiction: "Global",
        description: "Environmental management system standard.",
        aliases: &["iso14001"],
        controls: &["governance_policy", "risk_assessment", "environmental_management", "sustainability_reporting", "audit_trail", "training_awareness"],
    },
    StandardDef {
        id: "csrd",
        name: "CSRD",
        category: "environment",
        jurisdiction: "European Union",
        description: "EU corporate sustainability reporting directive.",
        aliases: &["corporate sustainability reporting directive"],
        controls: &["governance_policy", "risk_assessment", "sustainability_reporting", "audit_trail", "vendor_management"],
    },
    StandardDef {
        id: "tcfd",
        name: "TCFD",
        category: "environment",
        jurisdiction: "Global",
        description: "Climate-related financial disclosure recommendations.",
        aliases: &["task force on climate-related financial disclosures"],
        controls: &["governance_policy", "risk_assessment", "sustainability_reporting", "financial_controls", "audit_trail"],
    },
    StandardDef {
        id: "gri",
        name: "GRI Standards",
        category: "environment",
        jurisdiction: "Global",
        description: "Global sustainability reporting standards.",
        aliases: &["global reporting initiative", "gri standards"],
        controls: &["governance_policy", "sustainability_reporting", "environmental_management", "vendor_management", "audit_trail"],
    },
];

pub fn control_by_id(id: &str) -> Option<&'static ControlDef> {
    let id = normalize_key(id).replace('-', "_");
    CONTROL_CATALOG.iter().find(|control| control.id == id)
}

pub fn standard_by_id_or_alias(value: &str) -> Option<&'static StandardDef> {
    let key = normalize_key(value);
    STANDARDS.iter().find(|standard| {
        normalize_key(standard.id) == key
            || normalize_key(standard.name) == key
            || standard
                .aliases
                .iter()
                .any(|alias| normalize_key(alias) == key)
    })
}

pub fn all_standard_ids() -> Vec<&'static str> {
    STANDARDS.iter().map(|standard| standard.id).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_contains_every_requested_standard_family() {
        for id in [
            "hipaa",
            "soc-2",
            "fedramp",
            "nist-csf",
            "nist-800-53",
            "gdpr",
            "iso-27001",
            "iso-27017",
            "iso-27018",
            "iso-27701",
            "cis-controls",
            "cyber-essentials",
            "essential-eight",
            "tisax",
            "cmmc",
            "ccpa",
            "cpra",
            "lgpd",
            "pipeda",
            "pdpa-sg",
            "pdpa-th",
            "privacy-act-1988",
            "uk-gdpr",
            "data-protection-act-2018",
            "pci-dss",
            "swift-csp",
            "psd2",
            "sox",
            "glba",
            "basel-iii",
            "hitech",
            "hitrust-csf",
            "fda-21-cfr-part-11",
            "mdr",
            "nis2",
            "fisma",
            "cjis-security-policy",
            "itar",
            "ear",
            "eu-ai-act",
            "iso-42001",
            "nist-ai-rmf",
            "iso-9001",
            "iso-22301",
            "iso-31000",
            "iso-20000",
            "iso-14001",
            "csrd",
            "tcfd",
            "gri",
        ] {
            assert!(standard_by_id_or_alias(id).is_some(), "missing {id}");
        }
    }

    #[test]
    fn aliases_resolve_common_user_input() {
        assert_eq!(standard_by_id_or_alias("SOC 2").unwrap().id, "soc-2");
        assert_eq!(standard_by_id_or_alias("NIST").unwrap().id, "nist-csf");
        assert_eq!(standard_by_id_or_alias("PCI DSS").unwrap().id, "pci-dss");
    }
}
