apiVersion: v1
kind: Service
metadata:
  name: gha-executor-router
  namespace: gha-continuity
  labels:
    app: gha-executor-router
spec:
  selector:
    app: gha-executor-router
  ports:
    - name: http
      port: 8126
      targetPort: http
