apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: dd-cluster-secrets
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    dd.dev/cloud-provider: aws
    dd.dev/secret-backend: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
