apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - master-deployment.yaml
  - master-service.yaml
  - island-deployment.yaml
  - island-service.yaml
  - island-scaledobject.yaml

labels:
  - pairs:
      app.kubernetes.io/name: dd-evolution-optimizer
      app.kubernetes.io/part-of: des-distributed-solver
    includeSelectors: true
