use std::{
    env,
    fmt::Write as _,
    net::SocketAddr,
    sync::Arc,
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};

use aws_config::meta::region::RegionProviderChain;
use aws_sdk_s3::{config::Region, primitives::ByteStream, types::ServerSideEncryption};
use axum::{
    body::Bytes,
    extract::{Path, Query, State},
    http::{header, HeaderMap, StatusCode},
    response::{Html, IntoResponse, Redirect, Response},
    routing::{get, post},
    Json, Router,
};
use chrono::Utc;
use dd_nats_subject_defs::{
    MUSIC_GENERATION_REQUESTS_QUEUE_GROUP, MUSIC_GENERATION_REQUESTS_SUBJECT,
    MUSIC_GENERATION_RESULTS_SUBJECT, MUSIC_SONGS_PUBLISHED_SUBJECT, MUSIC_VOTES_EVENTS_SUBJECT,
};
use des_engine::des::general::music_production::{
    generate_microtonal_song, generate_track_structure_plan, ArrangementSummary, AudioBuffer,
    MusicGenre, SongSpec, StylePalette, DEFAULT_SAMPLE_RATE,
};
use futures_util::StreamExt;
use once_cell::sync::Lazy;
use prometheus::{Encoder, IntCounterVec, IntGauge, Opts, TextEncoder};
use redis::AsyncCommands;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use tokio::sync::Mutex;
use tokio_postgres::types::ToSql;
use uuid::Uuid;

mod pg_contract {
    pub use dd_pg_defs::{MUSIC_SONGS_TABLE, MUSIC_SONG_VOTES_TABLE};
}

static STARTED_AT: Lazy<Instant> = Lazy::new(Instant::now);
static HTTP_REQUESTS: Lazy<IntCounterVec> = Lazy::new(|| {
    let counter = IntCounterVec::new(
        Opts::new(
            "dd_music_rs_http_requests_total",
            "HTTP requests observed by dd-music-rs.",
        ),
        &["method", "path", "status"],
    )
    .expect("failed to create dd_music_rs_http_requests_total");
    prometheus::default_registry()
        .register(Box::new(counter.clone()))
        .expect("failed to register dd_music_rs_http_requests_total");
    counter
});
static UPTIME_SECONDS: Lazy<IntGauge> = Lazy::new(|| {
    let gauge = IntGauge::new(
        "dd_music_rs_uptime_seconds",
        "dd-music-rs process uptime in seconds.",
    )
    .expect("failed to create dd_music_rs_uptime_seconds");
    prometheus::default_registry()
        .register(Box::new(gauge.clone()))
        .expect("failed to register dd_music_rs_uptime_seconds");
    gauge
});
static SONG_GENERATIONS: Lazy<IntCounterVec> = Lazy::new(|| {
    let counter = IntCounterVec::new(
        Opts::new(
            "dd_music_rs_song_generations_total",
            "Songs generated by dd-music-rs by result.",
        ),
        &["result"],
    )
    .expect("failed to create dd_music_rs_song_generations_total");
    prometheus::default_registry()
        .register(Box::new(counter.clone()))
        .expect("failed to register dd_music_rs_song_generations_total");
    counter
});
static SONG_VOTES: Lazy<IntCounterVec> = Lazy::new(|| {
    let counter = IntCounterVec::new(
        Opts::new("dd_music_rs_votes_total", "Song votes accepted by value."),
        &["value"],
    )
    .expect("failed to create dd_music_rs_votes_total");
    prometheus::default_registry()
        .register(Box::new(counter.clone()))
        .expect("failed to register dd_music_rs_votes_total");
    counter
});

const DEFAULT_REDIS_URL: &str = "redis://dd-redis-cache.default.svc.cluster.local:6379/0";
const SERVICE_NAME: &str = "dd-music-rs";
const EVENT_SCHEMA_VERSION: &str = "dd.music.v1";
const MAX_NATS_PAYLOAD_BYTES: usize = 1024 * 1024;
const DEFAULT_DAILY_TARGET_MIN: i64 = 3;
const DEFAULT_DAILY_TARGET_MAX: i64 = 5;
const DEFAULT_GENERATOR_INTERVAL_SECONDS: u64 = 3600;
const DEFAULT_GENERATOR_MAX_PER_SWEEP: i64 = 2;
const DEFAULT_GENERATION_MAX_ATTEMPTS: i64 = 8;
const DEFAULT_SONG_DURATION_SECONDS: f64 = 180.0;
const MIN_SONG_DURATION_SECONDS: f64 = 10.0;
const MAX_SONG_DURATION_SECONDS: f64 = 600.0;
const DEFAULT_MIN_LISTENABILITY_SCORE: f64 = 0.55;
const DEFAULT_VOTE_THROTTLE_SECONDS: u64 = 5;
const MAX_LIST_LIMIT: i64 = 100;

#[derive(Clone)]
struct AppState {
    config: Arc<Config>,
    redis: Option<redis::Client>,
    redis_connection: Arc<Mutex<Option<redis::aio::MultiplexedConnection>>>,
    s3: Option<aws_sdk_s3::Client>,
    nats: Option<async_nats::Client>,
}

#[derive(Clone)]
struct Config {
    database_url: Option<String>,
    server_auth_secret: Option<String>,
    allow_unauthenticated_internal: bool,
    generator_enabled: bool,
    generator_interval: Duration,
    generator_initial_delay: Duration,
    generator_max_per_sweep: i64,
    generation_max_attempts: i64,
    daily_target_min: i64,
    daily_target_max: i64,
    song_duration_seconds: f64,
    min_listenability_score: f64,
    redis_prefix: String,
    vote_hash_salt: String,
    vote_hash_salt_configured: bool,
    vote_throttle_seconds: u64,
    storage: StorageConfig,
}

#[derive(Clone)]
enum StorageConfig {
    S3(S3StorageConfig),
    Local(LocalStorageConfig),
}

#[derive(Clone)]
struct S3StorageConfig {
    bucket: String,
    public_base_url: String,
    key_prefix: String,
}

#[derive(Clone)]
struct LocalStorageConfig {
    root: String,
    public_base_url: String,
}

#[derive(Debug)]
enum ServiceError {
    BadRequest(String),
    Unauthorized,
    NotFound(String),
    TooManyRequests(String),
    Unavailable(String),
    Internal(String),
}

impl IntoResponse for ServiceError {
    fn into_response(self) -> Response {
        let (status, message) = match self {
            ServiceError::BadRequest(message) => (StatusCode::BAD_REQUEST, message),
            ServiceError::Unauthorized => (StatusCode::UNAUTHORIZED, "unauthorized".to_string()),
            ServiceError::NotFound(message) => (StatusCode::NOT_FOUND, message),
            ServiceError::TooManyRequests(message) => (StatusCode::TOO_MANY_REQUESTS, message),
            ServiceError::Unavailable(message) => (StatusCode::SERVICE_UNAVAILABLE, message),
            ServiceError::Internal(message) => (StatusCode::INTERNAL_SERVER_ERROR, message),
        };
        (status, Json(json!({ "ok": false, "error": message }))).into_response()
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct HealthResponse {
    ok: bool,
    service: &'static str,
    mode: &'static str,
    postgres_configured: bool,
    redis_configured: bool,
    storage_provider: String,
    generator_enabled: bool,
}

#[derive(Deserialize)]
struct SongsQuery {
    limit: Option<i64>,
}

#[derive(Deserialize)]
struct VoteQuery {
    value: Option<i32>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct VoteRequest {
    value: i32,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct GenerateRequest {
    count: Option<i64>,
    min_score: Option<f64>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct SongsResponse {
    ok: bool,
    generated_at_ms: u128,
    songs: Vec<SongRow>,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct SongRow {
    id: String,
    title: String,
    slug: String,
    genre: String,
    status: String,
    audio_url: Option<String>,
    content_type: Option<String>,
    duration_seconds: f64,
    bpm: f64,
    listenability_score: f64,
    vote_score: i32,
    up_votes: i32,
    down_votes: i32,
    play_count: i32,
    summary: Value,
    published_at: Option<String>,
    created_at: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct VoteResponse {
    ok: bool,
    song: SongRow,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct GenerateResponse {
    ok: bool,
    requested: i64,
    published: usize,
    discarded: usize,
    attempts: usize,
    songs: Vec<SongRow>,
}

struct GeneratedSong {
    id: String,
    title: String,
    slug: String,
    seed: i64,
    genre: String,
    audio_bytes: Vec<u8>,
    summary: ArrangementSummary,
    summary_json: Value,
    listenability_score: f64,
}

struct StoredObject {
    provider: String,
    bucket: Option<String>,
    key: String,
    url: String,
}

fn first_env(keys: &[&str]) -> Option<String> {
    keys.iter()
        .find_map(|key| env::var(key).ok())
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty())
}

fn env_bool(name: &str, default: bool) -> bool {
    env::var(name)
        .ok()
        .map(|value| {
            matches!(
                value.trim().to_ascii_lowercase().as_str(),
                "1" | "true" | "yes" | "on"
            )
        })
        .unwrap_or(default)
}

fn env_i64(name: &str, default: i64) -> i64 {
    env::var(name)
        .ok()
        .and_then(|value| value.trim().parse::<i64>().ok())
        .filter(|value| *value > 0)
        .unwrap_or(default)
}

fn env_u64(name: &str, default: u64) -> u64 {
    env::var(name)
        .ok()
        .and_then(|value| value.trim().parse::<u64>().ok())
        .filter(|value| *value > 0)
        .unwrap_or(default)
}

fn env_f64(name: &str, default: f64) -> f64 {
    env::var(name)
        .ok()
        .and_then(|value| value.trim().parse::<f64>().ok())
        .filter(|value| value.is_finite() && *value > 0.0)
        .unwrap_or(default)
}

fn config_from_env() -> Config {
    let storage_provider = first_env(&["MUSIC_STORAGE_PROVIDER", "DEFAULT_STORAGE_PROVIDER"])
        .unwrap_or_else(|| "s3".to_string())
        .to_ascii_lowercase();
    let storage = if storage_provider == "local" {
        StorageConfig::Local(LocalStorageConfig {
            root: first_env(&["MUSIC_LOCAL_STORAGE_ROOT", "LOCAL_STORAGE_ROOT"])
                .unwrap_or_else(|| "/tmp/dd-music-rs/audio".to_string()),
            public_base_url: first_env(&[
                "MUSIC_LOCAL_PUBLIC_BASE_URL",
                "LOCAL_STORAGE_PUBLIC_BASE_URL",
            ])
            .unwrap_or_else(|| "/local-audio".to_string()),
        })
    } else {
        StorageConfig::S3(S3StorageConfig {
            bucket: first_env(&["MUSIC_S3_BUCKET", "S3_BUCKET"]).unwrap_or_default(),
            public_base_url: first_env(&["MUSIC_S3_PUBLIC_BASE_URL", "S3_PUBLIC_BASE_URL"])
                .unwrap_or_default(),
            key_prefix: first_env(&["MUSIC_S3_KEY_PREFIX", "S3_KEY_PREFIX"])
                .unwrap_or_else(|| "music/generated".to_string()),
        })
    };

    let daily_target_min = env_i64("MUSIC_DAILY_TARGET_MIN", DEFAULT_DAILY_TARGET_MIN);
    let daily_target_max =
        env_i64("MUSIC_DAILY_TARGET_MAX", DEFAULT_DAILY_TARGET_MAX).max(daily_target_min);
    let vote_hash_salt = first_env(&["MUSIC_VOTE_HASH_SALT", "SERVER_AUTH_SECRET"]);
    let vote_hash_salt_configured = vote_hash_salt.is_some();
    let vote_hash_salt =
        vote_hash_salt.unwrap_or_else(|| format!("dd-music-rs-local-{}", Uuid::new_v4()));

    Config {
        database_url: first_env(&[
            "MUSIC_RDS_DATABASE_URL",
            "AGENT_TASKS_RDS_DATABASE_URL",
            "RDS_DATABASE_URL",
            "DATABASE_URL",
            "PG_DATABASE_URL",
        ]),
        server_auth_secret: first_env(&["MUSIC_SERVER_AUTH_SECRET", "SERVER_AUTH_SECRET"]),
        allow_unauthenticated_internal: env_bool("MUSIC_ALLOW_UNAUTHENTICATED_INTERNAL", false),
        generator_enabled: env_bool("MUSIC_GENERATOR_ENABLED", false),
        generator_interval: Duration::from_secs(env_u64(
            "MUSIC_GENERATOR_INTERVAL_SECONDS",
            DEFAULT_GENERATOR_INTERVAL_SECONDS,
        )),
        generator_initial_delay: Duration::from_secs(env_u64(
            "MUSIC_GENERATOR_INITIAL_DELAY_SECONDS",
            20,
        )),
        generator_max_per_sweep: env_i64(
            "MUSIC_GENERATOR_MAX_PER_SWEEP",
            DEFAULT_GENERATOR_MAX_PER_SWEEP,
        ),
        generation_max_attempts: env_i64(
            "MUSIC_GENERATION_MAX_ATTEMPTS",
            DEFAULT_GENERATION_MAX_ATTEMPTS,
        ),
        daily_target_min,
        daily_target_max,
        song_duration_seconds: env_f64(
            "MUSIC_SONG_DURATION_SECONDS",
            DEFAULT_SONG_DURATION_SECONDS,
        )
        .clamp(MIN_SONG_DURATION_SECONDS, MAX_SONG_DURATION_SECONDS),
        min_listenability_score: env_f64(
            "MUSIC_MIN_LISTENABILITY_SCORE",
            DEFAULT_MIN_LISTENABILITY_SCORE,
        )
        .min(1.0),
        redis_prefix: first_env(&["MUSIC_REDIS_PREFIX"]).unwrap_or_else(|| {
            dd_redis_interfaces::MUSIC_DAILY_GENERATION_TARGET_KEY_DEFAULT_PREFIX.to_string()
        }),
        vote_hash_salt,
        vote_hash_salt_configured,
        vote_throttle_seconds: env_u64(
            "MUSIC_VOTE_THROTTLE_SECONDS",
            DEFAULT_VOTE_THROTTLE_SECONDS,
        ),
        storage,
    }
}

async fn state_from_config(config: Config) -> Result<AppState, String> {
    let redis = first_env(&["MUSIC_REDIS_URL", "REDIS_URL"])
        .or_else(|| Some(DEFAULT_REDIS_URL.to_string()))
        .and_then(|url| redis::Client::open(url).ok());

    let s3 = match &config.storage {
        StorageConfig::S3(s3_config) if !s3_config.bucket.is_empty() => {
            let region = first_env(&[
                "MUSIC_S3_REGION",
                "S3_REGION",
                "AWS_REGION",
                "AWS_DEFAULT_REGION",
            ]);
            let region_provider = RegionProviderChain::first_try(region.map(Region::new))
                .or_default_provider()
                .or_else("us-east-1");
            let shared_config = aws_config::defaults(aws_config::BehaviorVersion::latest())
                .region(region_provider)
                .load()
                .await;
            let mut builder = aws_sdk_s3::config::Builder::from(&shared_config);
            if let Some(endpoint) = first_env(&["MUSIC_S3_ENDPOINT", "S3_ENDPOINT"]) {
                builder = builder.endpoint_url(endpoint);
            }
            Some(aws_sdk_s3::Client::from_conf(builder.build()))
        }
        _ => None,
    };

    let nats = match first_env(&["MUSIC_NATS_URL", "NATS_URL"]) {
        Some(url) => match async_nats::connect(&url).await {
            Ok(client) => Some(client),
            Err(error) => {
                eprintln!("dd-music-rs NATS connect failed ({url}): {error}");
                None
            }
        },
        None => None,
    };

    Ok(AppState {
        config: Arc::new(config),
        redis,
        redis_connection: Arc::new(Mutex::new(None)),
        s3,
        nats,
    })
}

impl AppState {
    async fn redis_connection(&self) -> Result<redis::aio::MultiplexedConnection, ServiceError> {
        let Some(client) = &self.redis else {
            return Err(ServiceError::Unavailable(
                "redis is not configured".to_string(),
            ));
        };
        let mut guard = self.redis_connection.lock().await;
        if let Some(connection) = guard.as_ref() {
            return Ok(connection.clone());
        }
        let connection = client
            .get_multiplexed_async_connection()
            .await
            .map_err(|error| {
                eprintln!("dd-music-rs redis connection failed: {error}");
                ServiceError::Unavailable("redis connection failed".to_string())
            })?;
        *guard = Some(connection.clone());
        Ok(connection)
    }
}

fn record_request(method: &str, path: &str, status: StatusCode) {
    HTTP_REQUESTS
        .with_label_values(&[method, path, status.as_str()])
        .inc();
}

fn now_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

async fn connect_postgres(config: &Config) -> Result<tokio_postgres::Client, ServiceError> {
    let database_url = config
        .database_url
        .as_deref()
        .ok_or_else(|| ServiceError::Unavailable("music service is not ready".to_string()))?;
    let mut root_store = rustls::RootCertStore::empty();
    root_store.extend(webpki_roots::TLS_SERVER_ROOTS.iter().cloned());
    let tls_config = rustls::ClientConfig::builder()
        .with_root_certificates(root_store)
        .with_no_client_auth();
    let tls = tokio_postgres_rustls::MakeRustlsConnect::new(tls_config);
    let (client, connection) =
        tokio_postgres::connect(database_url, tls)
            .await
            .map_err(|error| {
                eprintln!("dd-music-rs postgres connect failed: {error}");
                ServiceError::Unavailable("postgres connect failed".to_string())
            })?;
    tokio::spawn(async move {
        if let Err(error) = connection.await {
            eprintln!("dd-music-rs postgres connection error: {error}");
        }
    });
    Ok(client)
}

fn require_server_auth(headers: &HeaderMap, config: &Config) -> Result<(), ServiceError> {
    if config.allow_unauthenticated_internal {
        return Ok(());
    }
    let expected = config
        .server_auth_secret
        .as_deref()
        .ok_or(ServiceError::Unauthorized)?;
    let presented = headers
        .get("X-Server-Auth")
        .or_else(|| headers.get("Auth"))
        .and_then(|value| value.to_str().ok())
        .unwrap_or("");
    if constant_time_eq(presented, expected) {
        Ok(())
    } else {
        Err(ServiceError::Unauthorized)
    }
}

async fn healthz(State(state): State<AppState>) -> impl IntoResponse {
    record_request("GET", "/healthz", StatusCode::OK);
    Json(HealthResponse {
        ok: true,
        service: "dd-music-rs",
        mode: "http",
        postgres_configured: state.config.database_url.is_some(),
        redis_configured: state.redis.is_some(),
        storage_provider: storage_provider_name(&state.config.storage).to_string(),
        generator_enabled: state.config.generator_enabled,
    })
}

async fn readyz(State(state): State<AppState>) -> impl IntoResponse {
    let storage_ready = storage_ready(&state.config.storage, state.s3.is_some());
    let internal_auth_ready =
        state.config.allow_unauthenticated_internal || state.config.server_auth_secret.is_some();
    let generation_ready = state.config.database_url.is_some()
        && storage_ready
        && state.config.vote_hash_salt_configured
        && internal_auth_ready;
    let status = StatusCode::OK;
    record_request("GET", "/readyz", status);
    (
        status,
        Json(json!({
            "ok": true,
            "generationReady": generation_ready,
            "degraded": !generation_ready,
            "postgresConfigured": state.config.database_url.is_some(),
            "storageProvider": storage_provider_name(&state.config.storage),
            "storageReady": storage_ready,
            "voteHashSaltConfigured": state.config.vote_hash_salt_configured,
            "internalAuthReady": internal_auth_ready
        })),
    )
}

async fn metrics() -> impl IntoResponse {
    record_request("GET", "/metrics", StatusCode::OK);
    UPTIME_SECONDS.set(STARTED_AT.elapsed().as_secs() as i64);
    let encoder = TextEncoder::new();
    let metric_families = prometheus::gather();
    let mut body = Vec::new();
    encoder
        .encode(&metric_families, &mut body)
        .expect("failed to encode prometheus metrics");
    (
        [(header::CONTENT_TYPE, encoder.format_type().to_string())],
        body,
    )
}

async fn api_docs_html() -> Html<&'static str> {
    record_request("GET", "/docs/api", StatusCode::OK);
    Html(include_str!("../generated/api-docs.html"))
}

async fn api_docs_json() -> impl IntoResponse {
    record_request("GET", "/api/docs.json", StatusCode::OK);
    (
        [(header::CONTENT_TYPE, "application/json; charset=utf-8")],
        include_str!("../generated/api-docs.json"),
    )
}

async fn home() -> Html<&'static str> {
    record_request("GET", "/", StatusCode::OK);
    Html(HOME_HTML)
}

async fn songs_shelf(
    State(state): State<AppState>,
    Query(query): Query<SongsQuery>,
) -> impl IntoResponse {
    let limit = query.limit.unwrap_or(36).clamp(1, MAX_LIST_LIMIT);
    let result = async {
        let client = connect_postgres(&state.config).await?;
        fetch_published_songs(&client, limit).await
    }
    .await;

    match result {
        Ok(songs) => {
            record_request("GET", "/songs/shelf", StatusCode::OK);
            (StatusCode::OK, Html(render_song_shelf(&songs))).into_response()
        }
        Err(error) => {
            eprintln!("dd-music-rs song shelf unavailable: {error:?}");
            record_request("GET", "/songs/shelf", StatusCode::OK);
            (StatusCode::OK, Html(render_shelf_error())).into_response()
        }
    }
}

async fn list_songs(
    State(state): State<AppState>,
    Query(query): Query<SongsQuery>,
) -> Result<Json<SongsResponse>, ServiceError> {
    let limit = query.limit.unwrap_or(24).clamp(1, MAX_LIST_LIMIT);
    let songs = match async {
        let client = connect_postgres(&state.config).await?;
        fetch_published_songs(&client, limit).await
    }
    .await
    {
        Ok(songs) => songs,
        Err(error) => {
            eprintln!("dd-music-rs song list unavailable: {error:?}");
            Vec::new()
        }
    };
    record_request("GET", "/songs", StatusCode::OK);
    Ok(Json(SongsResponse {
        ok: true,
        generated_at_ms: now_ms(),
        songs,
    }))
}

async fn get_song(
    State(state): State<AppState>,
    Path(song_id): Path<String>,
) -> Result<Json<SongRow>, ServiceError> {
    validate_song_id(&song_id)?;
    let client = connect_postgres(&state.config).await?;
    let song = fetch_song(&client, &song_id).await?;
    record_request("GET", "/songs/:song_id", StatusCode::OK);
    Ok(Json(song))
}

async fn song_audio(
    State(state): State<AppState>,
    Path(song_id): Path<String>,
) -> Result<Redirect, ServiceError> {
    validate_song_id(&song_id)?;
    let client = connect_postgres(&state.config).await?;
    let sql = format!(
        "update {songs}
            set play_count = play_count + 1, updated_at = now()
          where id = $1::uuid and status = 'published'
          returning audio_url",
        songs = pg_contract::MUSIC_SONGS_TABLE
    );
    let row = client
        .query_opt(&sql, &[&song_id])
        .await
        .map_err(db_error)?
        .ok_or_else(|| ServiceError::NotFound("song not found".to_string()))?;
    let audio_url: Option<String> = row.get("audio_url");
    let Some(audio_url) = audio_url else {
        return Err(ServiceError::NotFound("song has no audio URL".to_string()));
    };
    if !is_allowed_audio_url(&state.config.storage, &audio_url) {
        eprintln!("dd-music-rs blocked untrusted audio URL for song {song_id}");
        return Err(ServiceError::NotFound(
            "song audio URL is not available".to_string(),
        ));
    }
    record_request("GET", "/songs/:song_id/audio", StatusCode::FOUND);
    Ok(Redirect::temporary(&audio_url))
}

async fn vote_song(
    State(state): State<AppState>,
    Path(song_id): Path<String>,
    Query(query): Query<VoteQuery>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<Response, ServiceError> {
    validate_song_id(&song_id)?;
    let request = vote_request_from_parts(query, &headers, &body)?;
    if !matches!(request.value, -1 | 1) {
        return Err(ServiceError::BadRequest(
            "vote value must be 1 or -1".to_string(),
        ));
    }
    let visitor_hash = visitor_hash(&headers, &state.config.vote_hash_salt);
    throttle_vote(&state, &song_id, &visitor_hash).await?;
    let user_agent_hash = optional_header_hash(&headers, header::USER_AGENT.as_str());
    let client = connect_postgres(&state.config).await?;
    let song = upsert_vote(
        &client,
        &song_id,
        &visitor_hash,
        user_agent_hash.as_deref(),
        request.value,
    )
    .await?;
    SONG_VOTES
        .with_label_values(&[if request.value > 0 { "up" } else { "down" }])
        .inc();
    record_request("POST", "/songs/:song_id/votes", StatusCode::OK);
    if is_htmx_request(&headers) {
        Ok(Html(render_song_card(&song)).into_response())
    } else {
        Ok(Json(VoteResponse { ok: true, song }).into_response())
    }
}

async fn generate_internal(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<GenerateRequest>,
) -> Result<Json<GenerateResponse>, ServiceError> {
    require_server_auth(&headers, &state.config)?;
    let requested = request.count.unwrap_or(1).clamp(1, 5);
    let min_score = request
        .min_score
        .unwrap_or(state.config.min_listenability_score)
        .clamp(0.0, 1.0);
    let result = generate_and_publish_songs(&state, requested, min_score).await?;
    record_request("POST", "/internal/generate", StatusCode::OK);
    Ok(Json(result))
}

async fn fetch_published_songs(
    client: &tokio_postgres::Client,
    limit: i64,
) -> Result<Vec<SongRow>, ServiceError> {
    let sql = format!(
        "select
            id::text as id,
            title,
            slug,
            genre,
            status,
            audio_url,
            content_type,
            duration_millis,
            bpm_millis,
            listenability_score_micros,
            vote_score,
            up_votes,
            down_votes,
            play_count,
            summary,
            to_char(published_at at time zone 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') as published_at,
            to_char(created_at at time zone 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') as created_at
          from {songs}
          where status = 'published'
          order by published_at desc nulls last, created_at desc
          limit $1",
        songs = pg_contract::MUSIC_SONGS_TABLE
    );
    let rows = client.query(&sql, &[&limit]).await.map_err(db_error)?;
    Ok(rows.iter().map(song_from_row).collect())
}

async fn fetch_song(
    client: &tokio_postgres::Client,
    song_id: &str,
) -> Result<SongRow, ServiceError> {
    let sql = format!(
        "select
            id::text as id,
            title,
            slug,
            genre,
            status,
            audio_url,
            content_type,
            duration_millis,
            bpm_millis,
            listenability_score_micros,
            vote_score,
            up_votes,
            down_votes,
            play_count,
            summary,
            to_char(published_at at time zone 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') as published_at,
            to_char(created_at at time zone 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') as created_at
          from {songs}
          where id = $1::uuid",
        songs = pg_contract::MUSIC_SONGS_TABLE
    );
    let row = client
        .query_opt(&sql, &[&song_id])
        .await
        .map_err(db_error)?
        .ok_or_else(|| ServiceError::NotFound("song not found".to_string()))?;
    Ok(song_from_row(&row))
}

async fn upsert_vote(
    client: &tokio_postgres::Client,
    song_id: &str,
    visitor_hash: &str,
    user_agent_hash: Option<&str>,
    vote_value: i32,
) -> Result<SongRow, ServiceError> {
    let sql = format!(
        "with upserted as (
            insert into {votes} (song_id, visitor_hash, user_agent_hash, vote_value)
            values ($1::uuid, $2, $3, $4)
            on conflict (song_id, visitor_hash)
            do update set vote_value = excluded.vote_value, updated_at = now()
            returning song_id
          ),
          stats as (
            select
              song_id,
              count(*) filter (where vote_value = 1)::int as up_votes,
              count(*) filter (where vote_value = -1)::int as down_votes,
              coalesce(sum(vote_value), 0)::int as vote_score
            from {votes}
            where song_id = $1::uuid
            group by song_id
          )
          update {songs} songs
             set up_votes = stats.up_votes,
                 down_votes = stats.down_votes,
                 vote_score = stats.vote_score,
                 updated_at = now()
            from stats
           where songs.id = stats.song_id
           returning
            songs.id::text as id,
            songs.title,
            songs.slug,
            songs.genre,
            songs.status,
            songs.audio_url,
            songs.content_type,
            songs.duration_millis,
            songs.bpm_millis,
            songs.listenability_score_micros,
            songs.vote_score,
            songs.up_votes,
            songs.down_votes,
            songs.play_count,
            songs.summary,
            to_char(songs.published_at at time zone 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') as published_at,
            to_char(songs.created_at at time zone 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') as created_at",
        songs = pg_contract::MUSIC_SONGS_TABLE,
        votes = pg_contract::MUSIC_SONG_VOTES_TABLE
    );
    let params: &[&(dyn ToSql + Sync)] = &[&song_id, &visitor_hash, &user_agent_hash, &vote_value];
    let row = client
        .query_opt(&sql, params)
        .await
        .map_err(db_error)?
        .ok_or_else(|| ServiceError::NotFound("song not found".to_string()))?;
    Ok(song_from_row(&row))
}

async fn generate_and_publish_songs(
    state: &AppState,
    count: i64,
    min_score: f64,
) -> Result<GenerateResponse, ServiceError> {
    let client = connect_postgres(&state.config).await?;
    let mut published = Vec::new();
    let mut discarded = 0usize;
    let mut attempts = 0usize;
    let max_attempts = (count * state.config.generation_max_attempts).max(count) as usize;

    while published.len() < count as usize && attempts < max_attempts {
        attempts += 1;
        let seed = seed_for_attempt(attempts as u64);
        let song = generate_candidate(seed, state.config.song_duration_seconds);
        if song.listenability_score < min_score {
            discarded += 1;
            insert_discarded_song(&client, &song, "listenability_score_below_threshold").await?;
            SONG_GENERATIONS.with_label_values(&["discarded"]).inc();
            continue;
        }
        let stored = store_audio(state, &song).await?;
        let row = insert_published_song(&client, &song, &stored).await?;
        published.push(row);
        SONG_GENERATIONS.with_label_values(&["published"]).inc();
    }

    Ok(GenerateResponse {
        ok: true,
        requested: count,
        published: published.len(),
        discarded,
        attempts,
        songs: published,
    })
}

fn generate_candidate(seed: u32, duration_seconds: f64) -> GeneratedSong {
    let id = Uuid::new_v4().to_string();
    let genre = genre_for_seed(seed);
    let title = title_for_seed(seed);
    let slug = slug_for_title(&title, &id);
    let bpm = (genre.default_bpm() + ((seed >> 5) % 17) as f64 - 8.0).clamp(62.0, 190.0);
    let structure_plan =
        generate_track_structure_plan(title.clone(), genre, duration_seconds, seed);
    let render = generate_microtonal_song(SongSpec {
        title: title.clone(),
        genre,
        duration_seconds,
        sample_rate: DEFAULT_SAMPLE_RATE,
        bpm,
        seed,
        palette: if seed % 2 == 0 {
            StylePalette::RaveCollage
        } else {
            StylePalette::BrokenBeatDream
        },
        structure_plan: Some(structure_plan),
        ..Default::default()
    });
    let listenability_score = listenability_score(&render.summary);
    let summary_json = summary_to_json(&render.summary);
    let audio_bytes = wav16_bytes(&render.audio);
    GeneratedSong {
        id,
        title,
        slug,
        seed: seed as i64,
        genre: genre.as_str().to_string(),
        audio_bytes,
        summary: render.summary,
        summary_json,
        listenability_score,
    }
}

async fn store_audio(state: &AppState, song: &GeneratedSong) -> Result<StoredObject, ServiceError> {
    match &state.config.storage {
        StorageConfig::S3(config) => {
            if config.bucket.is_empty() || config.public_base_url.is_empty() {
                return Err(ServiceError::Unavailable(
                    "S3 storage needs MUSIC_S3_BUCKET and MUSIC_S3_PUBLIC_BASE_URL".to_string(),
                ));
            }
            let Some(client) = &state.s3 else {
                return Err(ServiceError::Unavailable(
                    "S3 client is not configured".to_string(),
                ));
            };
            let key = format!(
                "{}/{}/{}.wav",
                config.key_prefix.trim_matches('/'),
                Utc::now().format("%Y-%m-%d"),
                song.slug
            );
            client
                .put_object()
                .bucket(&config.bucket)
                .key(&key)
                .content_type("audio/wav")
                .server_side_encryption(ServerSideEncryption::Aes256)
                .body(ByteStream::from(song.audio_bytes.clone()))
                .send()
                .await
                .map_err(|error| {
                    eprintln!("dd-music-rs S3 upload failed: {error}");
                    ServiceError::Unavailable("S3 upload failed".to_string())
                })?;
            Ok(StoredObject {
                provider: "s3".to_string(),
                bucket: Some(config.bucket.clone()),
                url: join_url(&config.public_base_url, &key),
                key,
            })
        }
        StorageConfig::Local(config) => {
            let date = Utc::now().format("%Y-%m-%d").to_string();
            let key = format!("{date}/{}.wav", song.slug);
            let path = std::path::Path::new(&config.root).join(&key);
            if let Some(parent) = path.parent() {
                tokio::fs::create_dir_all(parent).await.map_err(|error| {
                    eprintln!("dd-music-rs local storage mkdir failed: {error}");
                    ServiceError::Unavailable("local storage mkdir failed".to_string())
                })?;
            }
            tokio::fs::write(&path, &song.audio_bytes)
                .await
                .map_err(|error| {
                    eprintln!("dd-music-rs local storage write failed: {error}");
                    ServiceError::Unavailable("local storage write failed".to_string())
                })?;
            Ok(StoredObject {
                provider: "local".to_string(),
                bucket: None,
                url: join_url(&config.public_base_url, &key),
                key,
            })
        }
    }
}

async fn insert_published_song(
    client: &tokio_postgres::Client,
    song: &GeneratedSong,
    stored: &StoredObject,
) -> Result<SongRow, ServiceError> {
    let sql = format!(
        "insert into {songs} (
            id,
            title,
            slug,
            status,
            seed,
            generation_date,
            storage_provider,
            storage_bucket,
            storage_key,
            audio_url,
            content_type,
            duration_millis,
            sample_rate,
            bpm_millis,
            genre,
            peak_micros,
            rms_micros,
            spectral_centroid_millihz,
            listenability_score_micros,
            summary,
            meta_data,
            published_at
          )
          values (
            $1::uuid, $2, $3, 'published', $4, to_char(current_date, 'YYYY-MM-DD'), $5, $6, $7, $8, 'audio/wav',
            $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, now()
          )
          returning
            id::text as id,
            title,
            slug,
            genre,
            status,
            audio_url,
            content_type,
            duration_millis,
            bpm_millis,
            listenability_score_micros,
            vote_score,
            up_votes,
            down_votes,
            play_count,
            summary,
            to_char(published_at at time zone 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') as published_at,
            to_char(created_at at time zone 'utc', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"') as created_at",
        songs = pg_contract::MUSIC_SONGS_TABLE
    );
    let meta = json!({
        "generator": "des_engine::des::general::music_production",
        "storageKey": stored.key,
        "audioBytes": song.audio_bytes.len(),
    });
    let sample_rate = DEFAULT_SAMPLE_RATE as i32;
    let duration_millis = millis_i32(song.summary.duration_seconds);
    let bpm_millis = millis_i32(song.summary.bpm);
    let peak_micros = micros_i32(song.summary.peak);
    let rms_micros = micros_i32(song.summary.rms);
    let spectral_centroid_millihz = millihz_i64(song.summary.spectral_centroid_hz);
    let listenability_score_micros = micros_i32(song.listenability_score);
    let params: &[&(dyn ToSql + Sync)] = &[
        &song.id,
        &song.title,
        &song.slug,
        &song.seed,
        &stored.provider,
        &stored.bucket,
        &stored.key,
        &stored.url,
        &duration_millis,
        &sample_rate,
        &bpm_millis,
        &song.genre,
        &peak_micros,
        &rms_micros,
        &spectral_centroid_millihz,
        &listenability_score_micros,
        &song.summary_json,
        &meta,
    ];
    let row = client.query_one(&sql, params).await.map_err(db_error)?;
    Ok(song_from_row(&row))
}

async fn insert_discarded_song(
    client: &tokio_postgres::Client,
    song: &GeneratedSong,
    reason: &str,
) -> Result<(), ServiceError> {
    let sql = format!(
        "insert into {songs} (
            id,
            title,
            slug,
            status,
            seed,
            generation_date,
            content_type,
            duration_millis,
            sample_rate,
            bpm_millis,
            genre,
            peak_micros,
            rms_micros,
            spectral_centroid_millihz,
            listenability_score_micros,
            summary,
            meta_data
          )
          values (
            $1::uuid, $2, $3, 'discarded', $4, to_char(current_date, 'YYYY-MM-DD'), 'audio/wav',
            $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
          )",
        songs = pg_contract::MUSIC_SONGS_TABLE
    );
    let meta = json!({
        "discardReason": reason,
        "generator": "des_engine::des::general::music_production"
    });
    let sample_rate = DEFAULT_SAMPLE_RATE as i32;
    let duration_millis = millis_i32(song.summary.duration_seconds);
    let bpm_millis = millis_i32(song.summary.bpm);
    let peak_micros = micros_i32(song.summary.peak);
    let rms_micros = micros_i32(song.summary.rms);
    let spectral_centroid_millihz = millihz_i64(song.summary.spectral_centroid_hz);
    let listenability_score_micros = micros_i32(song.listenability_score);
    let params: &[&(dyn ToSql + Sync)] = &[
        &song.id,
        &song.title,
        &song.slug,
        &song.seed,
        &duration_millis,
        &sample_rate,
        &bpm_millis,
        &song.genre,
        &peak_micros,
        &rms_micros,
        &spectral_centroid_millihz,
        &listenability_score_micros,
        &song.summary_json,
        &meta,
    ];
    client.execute(&sql, params).await.map_err(db_error)?;
    Ok(())
}

async fn throttle_vote(
    state: &AppState,
    song_id: &str,
    visitor_hash: &str,
) -> Result<(), ServiceError> {
    if state.config.vote_throttle_seconds == 0 || state.redis.is_none() {
        return Ok(());
    }
    let key = dd_redis_interfaces::music_song_visitor_vote_key(
        &state.config.redis_prefix,
        song_id,
        visitor_hash,
    );
    let mut connection = match state.redis_connection().await {
        Ok(connection) => connection,
        Err(error) => {
            eprintln!("dd-music-rs vote throttle unavailable: {error:?}");
            return Ok(());
        }
    };
    let response: redis::RedisResult<Option<String>> = redis::cmd("SET")
        .arg(&key)
        .arg("1")
        .arg("NX")
        .arg("EX")
        .arg(state.config.vote_throttle_seconds)
        .query_async(&mut connection)
        .await;
    let response = match response {
        Ok(response) => response,
        Err(error) => {
            eprintln!("dd-music-rs redis vote throttle failed: {error}");
            return Ok(());
        }
    };
    if response.is_none() {
        return Err(ServiceError::TooManyRequests(
            "vote accepted too recently; wait a moment before changing it".to_string(),
        ));
    }
    Ok(())
}

async fn run_generator_loop(state: AppState) {
    tokio::time::sleep(state.config.generator_initial_delay).await;
    loop {
        if let Err(error) = run_generator_sweep(&state).await {
            eprintln!("dd-music-rs generator sweep failed: {error:?}");
            SONG_GENERATIONS.with_label_values(&["failed"]).inc();
        }
        tokio::time::sleep(state.config.generator_interval).await;
    }
}

async fn run_generator_sweep(state: &AppState) -> Result<(), ServiceError> {
    let lock_token = Uuid::new_v4().to_string();
    if !acquire_generation_lock(state, &lock_token).await? {
        return Ok(());
    }
    let client = connect_postgres(&state.config).await?;
    let target = daily_target(state).await?;
    let published_today = published_today_count(&client).await?;
    let remaining = (target - published_today).max(0);
    if remaining == 0 {
        return Ok(());
    }
    let count = remaining.min(state.config.generator_max_per_sweep);
    let _ = generate_and_publish_songs(state, count, state.config.min_listenability_score).await?;
    Ok(())
}

async fn acquire_generation_lock(state: &AppState, token: &str) -> Result<bool, ServiceError> {
    let Some(_) = &state.redis else {
        return Ok(true);
    };
    let key = dd_redis_interfaces::music_generation_run_lock_key(&state.config.redis_prefix);
    let mut connection = state.redis_connection().await?;
    let response: Option<String> = redis::cmd("SET")
        .arg(&key)
        .arg(token)
        .arg("NX")
        .arg("EX")
        .arg(state.config.generator_interval.as_secs().max(60))
        .query_async(&mut connection)
        .await
        .map_err(|error| {
            eprintln!("dd-music-rs redis generation lock failed: {error}");
            ServiceError::Unavailable("redis generation lock failed".to_string())
        })?;
    Ok(response.is_some())
}

async fn daily_target(state: &AppState) -> Result<i64, ServiceError> {
    let today = Utc::now().format("%Y-%m-%d").to_string();
    if let Some(_) = &state.redis {
        let key = dd_redis_interfaces::music_daily_generation_target_key(
            &state.config.redis_prefix,
            &today,
        );
        if let Ok(mut connection) = state.redis_connection().await {
            let existing: Option<i64> = connection.get(&key).await.unwrap_or(None);
            if let Some(existing) = existing {
                return Ok(
                    existing.clamp(state.config.daily_target_min, state.config.daily_target_max)
                );
            }
            let target = deterministic_daily_target(
                &today,
                state.config.daily_target_min,
                state.config.daily_target_max,
            );
            let _: Result<(), _> = redis::cmd("SET")
                .arg(&key)
                .arg(target)
                .arg("EX")
                .arg(60 * 60 * 48)
                .query_async(&mut connection)
                .await;
            return Ok(target);
        }
    }
    Ok(deterministic_daily_target(
        &today,
        state.config.daily_target_min,
        state.config.daily_target_max,
    ))
}

async fn published_today_count(client: &tokio_postgres::Client) -> Result<i64, ServiceError> {
    let sql = format!(
        "select count(*)::bigint as count
           from {songs}
          where status = 'published'
            and generation_date = to_char(current_date, 'YYYY-MM-DD')",
        songs = pg_contract::MUSIC_SONGS_TABLE
    );
    let row = client.query_one(&sql, &[]).await.map_err(db_error)?;
    Ok(row.get("count"))
}

fn deterministic_daily_target(today: &str, min: i64, max: i64) -> i64 {
    let span = (max - min + 1).max(1);
    min + (hash32(today.as_bytes()) as i64 % span)
}

fn song_from_row(row: &tokio_postgres::Row) -> SongRow {
    let id: String = row.get("id");
    let duration_millis: i32 = row.get("duration_millis");
    let bpm_millis: i32 = row.get("bpm_millis");
    let listenability_score_micros: i32 = row.get("listenability_score_micros");
    SongRow {
        audio_url: row
            .get::<_, Option<String>>("audio_url")
            .map(|_| format!("songs/{id}/audio")),
        id,
        title: row.get("title"),
        slug: row.get("slug"),
        genre: row.get("genre"),
        status: row.get("status"),
        content_type: row.get("content_type"),
        duration_seconds: duration_millis as f64 / 1000.0,
        bpm: bpm_millis as f64 / 1000.0,
        listenability_score: listenability_score_micros as f64 / 1_000_000.0,
        vote_score: row.get("vote_score"),
        up_votes: row.get("up_votes"),
        down_votes: row.get("down_votes"),
        play_count: row.get("play_count"),
        summary: row.get("summary"),
        published_at: row.get("published_at"),
        created_at: row.get("created_at"),
    }
}

fn vote_request_from_parts(
    query: VoteQuery,
    headers: &HeaderMap,
    body: &[u8],
) -> Result<VoteRequest, ServiceError> {
    if let Some(value) = query.value {
        return Ok(VoteRequest { value });
    }
    if body.is_empty() {
        return Err(ServiceError::BadRequest(
            "vote value must be supplied".to_string(),
        ));
    }

    let content_type = headers
        .get(header::CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .unwrap_or("");
    if content_type.starts_with("application/x-www-form-urlencoded") {
        if let Some(value) = form_vote_value(body) {
            return Ok(VoteRequest { value });
        }
    }

    serde_json::from_slice::<VoteRequest>(body)
        .map_err(|_| ServiceError::BadRequest("vote value must be supplied".to_string()))
}

fn form_vote_value(body: &[u8]) -> Option<i32> {
    let text = std::str::from_utf8(body).ok()?;
    for pair in text.split('&') {
        let mut parts = pair.splitn(2, '=');
        if parts.next()? == "value" {
            return parts.next()?.parse::<i32>().ok();
        }
    }
    None
}

fn is_htmx_request(headers: &HeaderMap) -> bool {
    headers
        .get("HX-Request")
        .and_then(|value| value.to_str().ok())
        .map(|value| value.eq_ignore_ascii_case("true"))
        .unwrap_or(false)
}

fn render_song_shelf(songs: &[SongRow]) -> String {
    let mut html = String::new();
    let _ = write!(
        html,
        r##"<div class="shelf-head">
  <div>
    <p class="eyebrow">Latest transmissions</p>
    <h2>Generated today and recently</h2>
  </div>
  <div class="shelf-actions">
    <span>{} published tracks</span>
    <button type="button" hx-get="songs/shelf?limit=36" hx-target="#shelf" hx-swap="innerHTML">Refresh</button>
  </div>
</div>"##,
        songs.len()
    );

    if songs.is_empty() {
        html.push_str(
            r#"<div class="empty">No published songs yet. The generator will fill this shelf once Postgres and storage are ready.</div>"#,
        );
        return html;
    }

    html.push_str(r#"<div class="grid">"#);
    for song in songs {
        html.push_str(&render_song_card(song));
    }
    html.push_str("</div>");
    html
}

fn render_shelf_error() -> String {
    r##"<div class="shelf-head">
  <div>
    <p class="eyebrow">Latest transmissions</p>
    <h2>Generated today and recently</h2>
  </div>
  <div class="shelf-actions">
    <span>Offline</span>
    <button type="button" hx-get="songs/shelf?limit=36" hx-target="#shelf" hx-swap="innerHTML">Retry</button>
  </div>
</div>
<div class="empty error">Songs are unavailable right now.</div>"##
        .to_string()
}

fn render_song_card(song: &SongRow) -> String {
    let id = escape_html(&song.id);
    let title = escape_html(&song.title);
    let genre = escape_html(&song.genre);
    let duration = format!("{:.0}s", song.duration_seconds);
    let bpm = format!("{:.1} bpm", song.bpm);
    let quality = format!("{:.2}", song.listenability_score);
    let rms = format!("{:.3}", summary_number(&song.summary, "rms"));
    let centroid = format!(
        "{:.0} Hz",
        summary_number(&song.summary, "spectralCentroidHz")
    );
    let published = song
        .published_at
        .as_deref()
        .map(escape_html)
        .unwrap_or_else(|| "recent".to_string());
    let audio = song
        .audio_url
        .as_deref()
        .map(|url| {
            format!(
                r#"<audio controls preload="none" src="{}"></audio>"#,
                escape_html(url)
            )
        })
        .unwrap_or_else(|| r#"<div class="empty mini">Audio not available</div>"#.to_string());

    format!(
        r##"<article id="song-{id}" class="song">
  <div>
    <h3>{title}</h3>
    <div class="meta">
      <span class="pill">{genre}</span>
      <span class="pill">{duration}</span>
      <span class="pill">{bpm}</span>
    </div>
  </div>
  {audio}
  <div class="quality">
    <span>quality {quality}</span>
    <span>plays {plays}</span>
    <span>rms {rms}</span>
    <span>centroid {centroid}</span>
  </div>
  <div class="votes">
    <button type="button" hx-post="songs/{id}/votes?value=1" hx-target="#song-{id}" hx-swap="outerHTML" aria-label="Upvote {title}">Up</button>
    <strong class="score">{score}</strong>
    <button type="button" hx-post="songs/{id}/votes?value=-1" hx-target="#song-{id}" hx-swap="outerHTML" aria-label="Downvote {title}">Down</button>
    <span class="sub">{up} up / {down} down</span>
  </div>
  <p class="published">Published {published}</p>
</article>"##,
        plays = song.play_count,
        score = song.vote_score,
        up = song.up_votes,
        down = song.down_votes
    )
}

fn summary_number(summary: &Value, key: &str) -> f64 {
    summary.get(key).and_then(Value::as_f64).unwrap_or(0.0)
}

fn escape_html(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&#39;"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

fn client_ip_for_hash(headers: &HeaderMap) -> String {
    if let Some(real_ip) = headers
        .get("X-Real-IP")
        .and_then(|value| value.to_str().ok())
        .map(str::trim)
        .filter(|value| !value.is_empty())
    {
        return real_ip.to_string();
    }
    headers
        .get("X-Forwarded-For")
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.split(',').next_back())
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or("unknown")
        .to_string()
}

fn visitor_hash(headers: &HeaderMap, salt: &str) -> String {
    let forwarded = client_ip_for_hash(headers);
    let user_agent = headers
        .get(header::USER_AGENT)
        .and_then(|value| value.to_str().ok())
        .unwrap_or("unknown");
    hex_sha256(format!("{salt}\0{forwarded}\0{user_agent}").as_bytes())
}

fn optional_header_hash(headers: &HeaderMap, name: &str) -> Option<String> {
    headers
        .get(name)
        .and_then(|value| value.to_str().ok())
        .map(|value| hex_sha256(value.as_bytes()))
}

fn seed_for_attempt(attempt: u64) -> u32 {
    let material = format!(
        "dd-music-rs:{}:{attempt}:{}",
        Utc::now().to_rfc3339(),
        Uuid::new_v4()
    );
    hash32(material.as_bytes())
}

fn genre_for_seed(seed: u32) -> MusicGenre {
    const GENRES: &[MusicGenre] = &[
        MusicGenre::DrumAndBass,
        MusicGenre::House,
        MusicGenre::Breakbeat,
        MusicGenre::FutureGarage,
        MusicGenre::DubTechno,
        MusicGenre::TripHop,
        MusicGenre::GlitchHop,
        MusicGenre::AmbientTechno,
        MusicGenre::Jungle,
        MusicGenre::Electronica,
        MusicGenre::Downtempo,
        MusicGenre::Techno,
    ];
    GENRES[(seed as usize) % GENRES.len()]
}

fn title_for_seed(seed: u32) -> String {
    const LEFT: &[&str] = &[
        "Signal", "Violet", "Glass", "Metro", "Lattice", "Drift", "Amber", "Night", "Circuit",
        "River", "Static", "Pulse",
    ];
    const RIGHT: &[&str] = &[
        "Index", "Bloom", "Run", "Sketch", "Engine", "Room", "Field", "Trace", "Arc", "Thread",
        "Map", "Window",
    ];
    let left = LEFT[(seed as usize) % LEFT.len()];
    let right = RIGHT[((seed >> 8) as usize) % RIGHT.len()];
    format!("{left} {right}")
}

fn slug_for_title(title: &str, id: &str) -> String {
    let mut slug = String::new();
    for ch in title.chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch.to_ascii_lowercase());
        } else if !slug.ends_with('-') {
            slug.push('-');
        }
    }
    let slug = slug.trim_matches('-');
    let suffix = id.get(0..8).unwrap_or("song");
    format!("{slug}-{suffix}")
}

fn listenability_score(summary: &ArrangementSummary) -> f64 {
    let mut score: f64 = 0.0;
    if (0.025..=0.42).contains(&summary.rms) {
        score += 0.30;
    }
    if (0.35..=1.05).contains(&summary.peak) {
        score += 0.20;
    }
    if (120.0..=8_500.0).contains(&summary.spectral_centroid_hz) {
        score += 0.20;
    }
    if summary.rendered_events as f64 >= summary.duration_seconds.max(1.0) * 0.75 {
        score += 0.15;
    }
    if summary.drum_variation.variation_ratio()
        >= summary.drum_variation.repetition_reduction_target * 0.5
    {
        score += 0.15;
    }
    score.min(1.0)
}

fn summary_to_json(summary: &ArrangementSummary) -> Value {
    json!({
        "title": &summary.title,
        "genre": summary.genre.as_str(),
        "durationSeconds": summary.duration_seconds,
        "bpm": summary.bpm,
        "scaleName": &summary.scale_name,
        "sections": summary.sections.iter().map(|section| json!({
            "name": &section.name,
            "startSeconds": section.start_seconds,
            "endSeconds": section.end_seconds,
        })).collect::<Vec<_>>(),
        "parts": summary.parts.iter().map(|part| json!({
            "name": &part.name,
            "role": format!("{:?}", part.role),
            "instrument": &part.instrument,
            "events": part.events,
        })).collect::<Vec<_>>(),
        "instruments": &summary.instruments,
        "keyChangeCount": summary.key_changes.len(),
        "timeSignatureChangeCount": summary.time_signature_changes.len(),
        "pauseCount": summary.pauses.len(),
        "italianFeatures": &summary.italian_features,
        "drumVariation": {
            "patternNames": &summary.drum_variation.pattern_names,
            "drumSteps": summary.drum_variation.drum_steps,
            "fills": summary.drum_variation.fills,
            "ghostHits": summary.drum_variation.ghost_hits,
            "syncopations": summary.drum_variation.syncopations,
            "variationRatio": summary.drum_variation.variation_ratio(),
            "repetitionReductionTarget": summary.drum_variation.repetition_reduction_target,
        },
        "renderedEvents": summary.rendered_events,
        "peak": summary.peak,
        "rms": summary.rms,
        "spectralCentroidHz": summary.spectral_centroid_hz,
    })
}

fn wav16_bytes(audio: &AudioBuffer) -> Vec<u8> {
    let data_bytes = (audio.samples.len() * 2) as u32;
    let riff_size = 36u32 + data_bytes;
    let mut out = Vec::with_capacity(44 + data_bytes as usize);
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&riff_size.to_le_bytes());
    out.extend_from_slice(b"WAVE");
    out.extend_from_slice(b"fmt ");
    out.extend_from_slice(&16u32.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes());
    out.extend_from_slice(&audio.sample_rate.to_le_bytes());
    out.extend_from_slice(&(audio.sample_rate * 2).to_le_bytes());
    out.extend_from_slice(&2u16.to_le_bytes());
    out.extend_from_slice(&16u16.to_le_bytes());
    out.extend_from_slice(b"data");
    out.extend_from_slice(&data_bytes.to_le_bytes());
    for sample in &audio.samples {
        let pcm = (sample.clamp(-1.0, 1.0) * i16::MAX as f64).round() as i16;
        out.extend_from_slice(&pcm.to_le_bytes());
    }
    out
}

fn hash32(bytes: &[u8]) -> u32 {
    let digest = Sha256::digest(bytes);
    u32::from_le_bytes([digest[0], digest[1], digest[2], digest[3]])
}

fn hex_sha256(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn join_url(base: &str, key: &str) -> String {
    format!(
        "{}/{}",
        base.trim_end_matches('/'),
        key.trim_start_matches('/')
    )
}

fn validate_song_id(song_id: &str) -> Result<(), ServiceError> {
    Uuid::parse_str(song_id)
        .map(|_| ())
        .map_err(|_| ServiceError::BadRequest("song id must be a UUID".to_string()))
}

fn storage_ready(storage: &StorageConfig, s3_client_configured: bool) -> bool {
    match storage {
        StorageConfig::S3(config) => {
            !config.bucket.is_empty() && !config.public_base_url.is_empty() && s3_client_configured
        }
        StorageConfig::Local(config) => {
            !config.root.is_empty() && !config.public_base_url.is_empty()
        }
    }
}

fn is_allowed_audio_url(storage: &StorageConfig, audio_url: &str) -> bool {
    let base = match storage {
        StorageConfig::S3(config) => config.public_base_url.as_str(),
        StorageConfig::Local(config) => config.public_base_url.as_str(),
    }
    .trim_end_matches('/');
    !base.is_empty() && (audio_url == base || audio_url.starts_with(&format!("{base}/")))
}

fn constant_time_eq(left: &str, right: &str) -> bool {
    let left = left.as_bytes();
    let right = right.as_bytes();
    let max_len = left.len().max(right.len());
    let mut diff = left.len() ^ right.len();
    for index in 0..max_len {
        let left_byte = left.get(index).copied().unwrap_or(0);
        let right_byte = right.get(index).copied().unwrap_or(0);
        diff |= (left_byte ^ right_byte) as usize;
    }
    diff == 0
}

fn millis_i32(value: f64) -> i32 {
    (value.max(0.0) * 1000.0)
        .round()
        .clamp(0.0, i32::MAX as f64) as i32
}

fn micros_i32(value: f64) -> i32 {
    (value.max(0.0) * 1_000_000.0)
        .round()
        .clamp(0.0, i32::MAX as f64) as i32
}

fn millihz_i64(value: f64) -> i64 {
    (value.max(0.0) * 1000.0)
        .round()
        .clamp(0.0, i64::MAX as f64) as i64
}

fn storage_provider_name(storage: &StorageConfig) -> &'static str {
    match storage {
        StorageConfig::S3(_) => "s3",
        StorageConfig::Local(_) => "local",
    }
}

fn db_error(error: tokio_postgres::Error) -> ServiceError {
    eprintln!("dd-music-rs postgres query failed: {error}");
    ServiceError::Internal("postgres query failed".to_string())
}

fn app(state: AppState) -> Router {
    Router::new()
        .route("/", get(home))
        .route("/songs", get(list_songs))
        .route("/songs/shelf", get(songs_shelf))
        .route("/songs/:song_id", get(get_song))
        .route("/songs/:song_id/audio", get(song_audio))
        .route("/songs/:song_id/votes", post(vote_song))
        .route("/internal/generate", post(generate_internal))
        .route("/healthz", get(healthz))
        .route("/readyz", get(readyz))
        .route("/metrics", get(metrics))
        .route("/docs/api", get(api_docs_html))
        .route("/api/docs", get(api_docs_html))
        .route("/api/docs.json", get(api_docs_json))
        .with_state(state)
}

#[tokio::main]
async fn main() {
    rustls::crypto::ring::default_provider()
        .install_default()
        .ok();

    let config = config_from_env();
    let host = first_env(&["HOST"]).unwrap_or_else(|| "0.0.0.0".to_string());
    let port = env_u64("PORT", 8115) as u16;
    let state = state_from_config(config)
        .await
        .expect("failed to initialize dd-music-rs state");

    if state.config.generator_enabled
        && state.config.database_url.is_some()
        && storage_ready(&state.config.storage, state.s3.is_some())
    {
        tokio::spawn(run_generator_loop(state.clone()));
    } else if state.config.generator_enabled {
        eprintln!("dd-music-rs generator disabled until postgres and storage are configured");
    }

    let addr: SocketAddr = format!("{host}:{port}")
        .parse()
        .expect("HOST/PORT must form a socket address");
    let listener = tokio::net::TcpListener::bind(addr)
        .await
        .expect("failed to bind dd-music-rs");
    println!("dd-music-rs listening on http://{addr}");
    axum::serve(listener, app(state))
        .with_graceful_shutdown(shutdown_signal())
        .await
        .expect("axum server crashed");
}

async fn shutdown_signal() {
    let _ = tokio::signal::ctrl_c().await;
}

const HOME_HTML: &str = r##"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>dd music</title>
  <script src="https://unpkg.com/htmx.org@2.0.4/dist/htmx.min.js"></script>
  <style>
    :root {
      color-scheme: light;
      --bg:#f6f7f4;
      --ink:#14181c;
      --muted:#5d6972;
      --panel:#ffffff;
      --line:#d6ddd6;
      --green:#236b4b;
      --coral:#b4463a;
      --blue:#285f8f;
      --amber:#906b1f;
      --night:#17212a;
      --mint:#dceee4;
    }
    * { box-sizing:border-box; }
    html { scroll-behavior:smooth; }
    body {
      margin:0;
      background:var(--bg);
      color:var(--ink);
      font:14px/1.5 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }
    a { color:inherit; text-decoration:none; }
    button, .button {
      border:1px solid var(--line);
      background:var(--panel);
      color:var(--ink);
      min-height:36px;
      padding:7px 11px;
      border-radius:6px;
      cursor:pointer;
      font:inherit;
      display:inline-flex;
      align-items:center;
      justify-content:center;
      gap:8px;
    }
    button:hover, .button:hover { border-color:#9fafaa; }
    .page-nav, .hero-inner, .section-inner { width:min(1160px, calc(100% - 28px)); margin:0 auto; }
    .page-nav {
      height:64px;
      display:flex;
      align-items:center;
      justify-content:space-between;
      gap:14px;
      border-bottom:1px solid var(--line);
    }
    .brand { font-weight:800; font-size:18px; letter-spacing:0; }
    .nav-links { display:flex; align-items:center; gap:12px; color:var(--muted); font-size:13px; }
    .hero {
      min-height:calc(100svh - 64px);
      display:flex;
      align-items:center;
      overflow:hidden;
      background:#eef3ed;
      border-bottom:1px solid var(--line);
    }
    .hero-inner {
      min-height:calc(100svh - 64px);
      display:grid;
      grid-template-columns:minmax(0, 1fr) minmax(340px, 0.8fr);
      align-items:center;
      gap:32px;
      padding:34px 0 44px;
    }
    .eyebrow {
      margin:0 0 8px;
      color:var(--green);
      font-weight:800;
      text-transform:uppercase;
      font-size:12px;
      letter-spacing:0;
    }
    h1 {
      margin:0;
      font-size:clamp(52px, 9vw, 112px);
      line-height:0.9;
      letter-spacing:0;
    }
    h2 { margin:0; font-size:28px; line-height:1.1; letter-spacing:0; }
    h3 { margin:0; font-size:18px; line-height:1.2; letter-spacing:0; }
    .lede { margin:18px 0 0; color:#34404a; max-width:58ch; font-size:18px; line-height:1.55; }
    .hero-actions { display:flex; flex-wrap:wrap; gap:10px; margin-top:24px; }
    .button.primary { background:var(--night); border-color:var(--night); color:#fff; }
    .stats { display:grid; grid-template-columns:repeat(3, minmax(0, 1fr)); gap:10px; margin-top:28px; max-width:680px; }
    .stat {
      border:1px solid rgba(20,24,28,0.14);
      background:rgba(255,255,255,0.58);
      border-radius:8px;
      padding:12px;
      min-height:78px;
    }
    .stat strong { display:block; font-size:22px; color:var(--blue); }
    .stat span { color:var(--muted); font-size:12px; }
    .visual {
      min-height:440px;
      position:relative;
      display:grid;
      align-items:center;
      overflow:hidden;
      border-left:1px solid rgba(20,24,28,0.10);
      padding-left:26px;
    }
    .wave {
      display:grid;
      grid-template-columns:repeat(24, 1fr);
      align-items:center;
      gap:7px;
      min-height:300px;
    }
    .bar {
      min-height:24px;
      border-radius:999px;
      background:linear-gradient(180deg, var(--blue), var(--green));
      opacity:0.82;
      box-shadow:0 20px 40px rgba(23,33,42,0.12);
    }
    .bar:nth-child(3n) { background:linear-gradient(180deg, var(--coral), var(--amber)); }
    .bar:nth-child(4n) { background:linear-gradient(180deg, var(--green), #7aa18d); }
    .bar:nth-child(1) { height:74px; } .bar:nth-child(2) { height:126px; }
    .bar:nth-child(3) { height:210px; } .bar:nth-child(4) { height:154px; }
    .bar:nth-child(5) { height:260px; } .bar:nth-child(6) { height:132px; }
    .bar:nth-child(7) { height:90px; } .bar:nth-child(8) { height:226px; }
    .bar:nth-child(9) { height:172px; } .bar:nth-child(10) { height:288px; }
    .bar:nth-child(11) { height:124px; } .bar:nth-child(12) { height:76px; }
    .bar:nth-child(13) { height:194px; } .bar:nth-child(14) { height:246px; }
    .bar:nth-child(15) { height:112px; } .bar:nth-child(16) { height:272px; }
    .bar:nth-child(17) { height:148px; } .bar:nth-child(18) { height:84px; }
    .bar:nth-child(19) { height:236px; } .bar:nth-child(20) { height:166px; }
    .bar:nth-child(21) { height:292px; } .bar:nth-child(22) { height:118px; }
    .bar:nth-child(23) { height:202px; } .bar:nth-child(24) { height:96px; }
    .visual-caption {
      color:var(--muted);
      font-size:12px;
      display:flex;
      justify-content:space-between;
      gap:12px;
      border-top:1px solid rgba(20,24,28,0.12);
      padding-top:12px;
    }
    main { padding:26px 0 42px; }
    .shelf-band { scroll-margin-top:24px; }
    #shelf.htmx-request { opacity:0.72; }
    .shelf-head {
      display:flex;
      justify-content:space-between;
      align-items:flex-end;
      gap:16px;
      margin-bottom:14px;
    }
    .shelf-actions { display:flex; align-items:center; gap:10px; color:var(--muted); white-space:nowrap; }
    .grid { display:grid; grid-template-columns:repeat(auto-fill, minmax(280px, 1fr)); gap:12px; }
    .song {
      background:var(--panel);
      border:1px solid var(--line);
      border-radius:8px;
      padding:13px;
      display:flex;
      flex-direction:column;
      gap:10px;
      min-height:288px;
    }
    .meta { display:flex; flex-wrap:wrap; gap:6px; color:var(--muted); font-size:12px; margin-top:8px; }
    .pill { border:1px solid var(--line); border-radius:6px; padding:2px 6px; background:#fbfcfa; }
    audio { width:100%; height:42px; }
    .votes { display:flex; align-items:center; gap:8px; margin-top:auto; flex-wrap:wrap; }
    .score { min-width:42px; text-align:center; font-weight:800; color:var(--blue); }
    .quality { color:var(--muted); font-size:12px; display:grid; grid-template-columns:1fr 1fr; gap:4px 10px; }
    .sub, .published { color:var(--muted); }
    .published { margin:0; font-size:12px; }
    .empty { border:1px dashed var(--line); border-radius:8px; padding:24px; color:var(--muted); background:#fff; }
    .empty.mini { padding:12px; }
    .error { color:var(--coral); }
    @media (max-width: 860px) {
      .hero-inner { grid-template-columns:1fr; align-items:start; }
      .hero { min-height:auto; }
      .hero-inner { min-height:auto; }
      .visual { min-height:260px; border-left:0; padding-left:0; }
      .wave { min-height:190px; gap:5px; }
      .stats { grid-template-columns:1fr; }
    }
    @media (max-width: 620px) {
      .nav-links a:not(.button) { display:none; }
      .shelf-head { align-items:flex-start; flex-direction:column; }
      .shelf-actions { white-space:normal; }
      h1 { font-size:52px; }
    }
  </style>
</head>
<body>
  <nav class="page-nav" aria-label="Primary">
    <a class="brand" href=".">dd music</a>
    <div class="nav-links">
      <a href="#shelf-section">Tracks</a>
      <a class="button" href="#shelf-section">Listen</a>
    </div>
  </nav>
  <header class="hero">
    <div class="hero-inner">
      <div>
        <p class="eyebrow">Rust generated music server</p>
        <h1>dd music</h1>
        <p class="lede">Microtonal tracks from the DES music engine, published as a daily shelf with native browser playback and anonymous voting.</p>
        <div class="hero-actions">
          <a class="button primary" href="#shelf-section">Listen now</a>
          <button type="button" hx-get="songs/shelf?limit=36" hx-target="#shelf" hx-swap="innerHTML">Refresh shelf</button>
        </div>
        <div class="stats" aria-label="Service profile">
          <div class="stat"><strong>3-5</strong><span>new tracks targeted per day</span></div>
          <div class="stat"><strong>DES</strong><span>in-process Rust generation</span></div>
          <div class="stat"><strong>S3</strong><span>encrypted published audio</span></div>
        </div>
      </div>
      <div class="visual" aria-hidden="true">
        <div class="wave">
          <span class="bar"></span><span class="bar"></span><span class="bar"></span><span class="bar"></span>
          <span class="bar"></span><span class="bar"></span><span class="bar"></span><span class="bar"></span>
          <span class="bar"></span><span class="bar"></span><span class="bar"></span><span class="bar"></span>
          <span class="bar"></span><span class="bar"></span><span class="bar"></span><span class="bar"></span>
          <span class="bar"></span><span class="bar"></span><span class="bar"></span><span class="bar"></span>
          <span class="bar"></span><span class="bar"></span><span class="bar"></span><span class="bar"></span>
        </div>
        <div class="visual-caption"><span>daily generator</span><span>vote-shaped shelf</span></div>
      </div>
    </div>
  </header>
  <main>
    <section id="shelf-section" class="shelf-band">
      <div class="section-inner">
        <div id="shelf" hx-get="songs/shelf?limit=36" hx-trigger="load, every 120s" hx-swap="innerHTML">
          <div class="shelf-head">
            <div>
              <p class="eyebrow">Latest transmissions</p>
              <h2>Generated today and recently</h2>
            </div>
            <div class="shelf-actions"><span>Loading</span></div>
          </div>
          <div class="empty">Loading songs.</div>
        </div>
      </div>
    </section>
  </main>
</body>
</html>
"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deterministic_daily_target_stays_in_range() {
        for day in ["2026-06-07", "2026-06-08", "2026-06-09"] {
            let target = deterministic_daily_target(day, 3, 5);
            assert!((3..=5).contains(&target));
        }
    }

    #[test]
    fn wav_bytes_has_riff_header() {
        let audio = AudioBuffer::silence(44_100, 0.01);
        let bytes = wav16_bytes(&audio);
        assert!(bytes.starts_with(b"RIFF"));
        assert_eq!(&bytes[8..12], b"WAVE");
    }

    #[test]
    fn slug_includes_short_uuid() {
        let slug = slug_for_title("Signal Bloom", "12345678-aaaa-bbbb-cccc-123456789abc");
        assert_eq!(slug, "signal-bloom-12345678");
    }

    #[test]
    fn client_ip_for_hash_prefers_real_ip() {
        let mut headers = HeaderMap::new();
        headers.insert(
            "X-Forwarded-For",
            "198.51.100.4, 203.0.113.9".parse().unwrap(),
        );
        headers.insert("X-Real-IP", "192.0.2.10".parse().unwrap());
        assert_eq!(client_ip_for_hash(&headers), "192.0.2.10");
    }

    #[test]
    fn client_ip_for_hash_uses_gateway_appended_forwarded_for() {
        let mut headers = HeaderMap::new();
        headers.insert(
            "X-Forwarded-For",
            "198.51.100.4, 203.0.113.9".parse().unwrap(),
        );
        assert_eq!(client_ip_for_hash(&headers), "203.0.113.9");
    }

    #[test]
    fn validate_song_id_rejects_invalid_uuid() {
        assert!(validate_song_id("not-a-song-id").is_err());
        assert!(validate_song_id("12345678-aaaa-bbbb-cccc-123456789abc").is_ok());
    }

    #[test]
    fn allowed_audio_url_stays_under_storage_base() {
        let storage = StorageConfig::S3(S3StorageConfig {
            bucket: "dd-music".to_string(),
            public_base_url: "https://cdn.example.test/music".to_string(),
            key_prefix: "generated".to_string(),
        });
        assert!(is_allowed_audio_url(
            &storage,
            "https://cdn.example.test/music/2026-06-07/song.wav"
        ));
        assert!(!is_allowed_audio_url(
            &storage,
            "https://cdn.example.test/music.evil/song.wav"
        ));
        assert!(!is_allowed_audio_url(
            &storage,
            "https://evil.example.test/music/song.wav"
        ));
    }

    #[test]
    fn constant_time_eq_matches_expected() {
        assert!(constant_time_eq("secret", "secret"));
        assert!(!constant_time_eq("secret", "secrex"));
        assert!(!constant_time_eq("secret", "secret-longer"));
    }

    #[test]
    fn vote_request_accepts_query_and_json_body() {
        let headers = HeaderMap::new();
        let query_request = vote_request_from_parts(
            VoteQuery { value: Some(1) },
            &headers,
            Bytes::new().as_ref(),
        )
        .unwrap();
        assert_eq!(query_request.value, 1);

        let mut headers = HeaderMap::new();
        headers.insert(header::CONTENT_TYPE, "application/json".parse().unwrap());
        let json_request = vote_request_from_parts(
            VoteQuery { value: None },
            &headers,
            Bytes::from_static(br#"{"value":-1}"#).as_ref(),
        )
        .unwrap();
        assert_eq!(json_request.value, -1);
    }

    #[test]
    fn render_song_card_escapes_content_and_uses_htmx_votes() {
        let id = "12345678-aaaa-bbbb-cccc-123456789abc".to_string();
        let song = SongRow {
            id: id.clone(),
            title: "Signal <Bloom>".to_string(),
            slug: "signal-bloom".to_string(),
            genre: "House & Bass".to_string(),
            status: "published".to_string(),
            audio_url: Some(format!("songs/{id}/audio")),
            content_type: Some("audio/wav".to_string()),
            duration_seconds: 180.0,
            bpm: 128.0,
            listenability_score: 0.82,
            vote_score: 3,
            up_votes: 4,
            down_votes: 1,
            play_count: 9,
            summary: json!({
                "rms": 0.12345,
                "spectralCentroidHz": 4321.0
            }),
            published_at: Some("2026-06-07T12:00:00Z".to_string()),
            created_at: "2026-06-07T12:00:00Z".to_string(),
        };

        let html = render_song_card(&song);
        assert!(html.contains("Signal &lt;Bloom&gt;"));
        assert!(html.contains("House &amp; Bass"));
        assert!(html.contains(&format!(r##"hx-post="songs/{id}/votes?value=1""##)));
        assert!(html.contains(&format!(r##"hx-target="#song-{id}""##)));
    }
}
