apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dd-akka-ws-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ORESoftware/k8s-cluster.git
    targetRevision: dev
    path: remote/akka-ws-server/k8s/ec2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
