apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dd-mlflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: dd-ai-ml-platform
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.8.1
    helm:
      skipTests: true
      values: |
        replicaCount: 1
        serviceAccount:
          automount: false
        extraPodLabels:
          dd-mlflow-postgresql-client: 'true'
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        auth:
          enabled: true
          existingAdminSecret:
            name: dd-mlflow-auth
            usernameKey: username
            passwordKey: password
          postgres:
            enabled: true
            host: dd-mlflow-postgresql
            port: 5432
            database: mlflow
            existingSecret:
              name: dd-mlflow-postgresql
              usernameKey: username
              passwordKey: password
        backendStore:
          postgres:
            enabled: true
            host: dd-mlflow-postgresql
            port: 5432
            database: mlflow
          existingDatabaseSecret:
            name: dd-mlflow-postgresql
            usernameKey: username
            passwordKey: password
        postgresql:
          enabled: false
        artifactRoot:
          defaultArtifactsDestination: /mlflow/artifacts
        extraEnvVars:
          HOME: /tmp/mlflow-home
          XDG_CACHE_HOME: /tmp/mlflow-cache
          TMPDIR: /tmp
        extraVolumes:
          - name: mlflow-tmp
            emptyDir:
              sizeLimit: 1Gi
          - name: mlflow-artifacts
            persistentVolumeClaim:
              claimName: dd-mlflow-artifacts
        extraVolumeMounts:
          - name: mlflow-tmp
            mountPath: /tmp
          - name: mlflow-artifacts
            mountPath: /mlflow/artifacts
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 2Gi
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-ml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
