apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dd-ws-loadtest-rs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:dancing-dragons/dd-next-1.git
    targetRevision: dev
    path: remote/ws-loadtest-rs/k8s/ec2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
