apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nats.configmap.yaml
  - nats.deployment.yaml
  - nats.service.yaml
  - nats.networkpolicy.yaml
  - nats.pdb.yaml
  - nats-bridge.configmap.yaml
  - nats-bridge.externalsecret.yaml
  - nats-bridge.deployment.yaml
  - nats-bridge.service.yaml
  - nats-bridge.networkpolicy.yaml
