apiVersion: v1
kind: ConfigMap
metadata:
  name: dd-nats-config
  namespace: messaging
data:
  nats.conf: |
    server_name: dd-nats
    port: 4222
    http: 8222

    max_payload: 8MB
    ping_interval: "20s"
    write_deadline: "10s"

    jetstream {
      store_dir: "/data/jetstream"
      max_mem_store: 1GB
      max_file_store: 20GB
    }
