apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: dd-cluster-secrets
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    dd.dev/cloud-provider: gcp
    dd.dev/secret-backend: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: dd-remote-dev
