apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root
  namespace: big-data
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: minio-root
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: minio
          app.kubernetes.io/component: credentials
  data:
    - secretKey: username
      remoteRef:
        key: dd/remote-dev/big-data-secrets
        property: MINIO_ROOT_USER
    - secretKey: password
      remoteRef:
        key: dd/remote-dev/big-data-secrets
        property: MINIO_ROOT_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-admin
  namespace: big-data
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: airflow-admin
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: airflow
          app.kubernetes.io/component: credentials
  data:
    - secretKey: username
      remoteRef:
        key: dd/remote-dev/big-data-secrets
        property: AIRFLOW_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: dd/remote-dev/big-data-secrets
        property: AIRFLOW_ADMIN_PASSWORD
