apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - external-secrets.yaml
  - networkpolicy.yaml
  - resource-controls.yaml
  - availability.yaml
  - spark.yaml
  - airflow.yaml
  - minio.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: des-big-data
    includeSelectors: true
