#!/usr/bin/env bash
# =============================================================================
# new-tenant.sh — generate the per-org tenant scaffold from the templates.
#
# This is the "templating beats a custom operator" answer from
# docs/crossplane-and-custom-operators.md §3.1. Registering an org today means
# hand-copying three files per the threefa/daedalus/zed precedent; this emits
# them from remote/argocd/projects/_*.template.yaml so the copies cannot drift
# from the templates or from each other.
#
# It writes FILES ONLY. Nothing is applied to any cluster, matching the house
# convention that tenant scaffolding stays inert until a human applies it with
# eyes on (see remote/argocd/projects/README.md).
#
# Usage:
#   scripts/new-tenant.sh <tenant> <app>=<repo-url> [<app>=<repo-url> ...]
#
# Example (reproduces the zed registration):
#   scripts/new-tenant.sh zed \
#     api-server=https://github.com/zed-pkg/zed-api-server.rs.git \
#     web-server=https://github.com/zed-pkg/zed-web-server.rs.git
#
# Flags:
#   --force        overwrite existing files (default: refuse, exit 3)
#   --path <dir>   Application source path inside each app repo (default: k8s)
#   --revision <r> Application targetRevision (default: main)
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECTS_DIR="${REPO_ROOT}/remote/argocd/projects"
APPS_DIR="${REPO_ROOT}/remote/argocd/apps"

FORCE=0
APP_PATH="k8s"
REVISION="main"
TENANT=""
APPS=()

die() { echo "ERROR: $*" >&2; exit 1; }
usage() { sed -n '3,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 64; }

while [ $# -gt 0 ]; do
  case "$1" in
    --force)    FORCE=1; shift ;;
    --path)     APP_PATH="${2:?--path needs a value}"; shift 2 ;;
    --revision) REVISION="${2:?--revision needs a value}"; shift 2 ;;
    -h|--help)  usage ;;
    -*)         die "unknown flag: $1" ;;
    *)
      if [ -z "${TENANT}" ]; then TENANT="$1"; else APPS+=("$1"); fi
      shift ;;
  esac
done

[ -n "${TENANT}" ] || usage
[ ${#APPS[@]} -gt 0 ] || die "at least one <app>=<repo-url> is required"

# Tenant name becomes a Namespace and an AppProject name — enforce DNS-1123 label
# rules up front rather than letting the API server reject it after the copy/paste.
[[ "${TENANT}" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] \
  || die "tenant '${TENANT}' is not a valid DNS-1123 label (lowercase alphanumeric and '-')"

[ -d "${PROJECTS_DIR}" ] || die "missing ${PROJECTS_DIR}"
[ -d "${APPS_DIR}" ]     || die "missing ${APPS_DIR}"

TENANT_TEMPLATE="${PROJECTS_DIR}/_tenant-scaffold.template.yaml"
PROJECT_TEMPLATE="${PROJECTS_DIR}/_template.appproject.yaml"
[ -f "${TENANT_TEMPLATE}" ]  || die "missing template ${TENANT_TEMPLATE}"
[ -f "${PROJECT_TEMPLATE}" ] || die "missing template ${PROJECT_TEMPLATE}"

TENANT_OUT="${PROJECTS_DIR}/${TENANT}.tenant.yaml"
PROJECT_OUT="${PROJECTS_DIR}/${TENANT}.appproject.yaml"
APPS_OUT="${APPS_DIR}/${TENANT}.applications.yaml"

for f in "${TENANT_OUT}" "${PROJECT_OUT}" "${APPS_OUT}"; do
  if [ -e "${f}" ] && [ "${FORCE}" -ne 1 ]; then
    die "${f#${REPO_ROOT}/} already exists (pass --force to overwrite)"
  fi
done

# Parse <app>=<repo-url> pairs once, up front, so a typo fails before any file is
# written rather than leaving a half-generated tenant behind.
APP_NAMES=()
APP_REPOS=()
for spec in "${APPS[@]}"; do
  case "${spec}" in
    *=*) ;;
    *) die "app spec '${spec}' must be <app>=<repo-url>" ;;
  esac
  name="${spec%%=*}"
  repo="${spec#*=}"
  [ -n "${name}" ] || die "app spec '${spec}' has an empty app name"
  [ -n "${repo}" ] || die "app spec '${spec}' has an empty repo URL"
  [[ "${name}" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] \
    || die "app name '${name}' is not a valid DNS-1123 label"
  APP_NAMES+=("${name}")
  APP_REPOS+=("${repo}")
done

# Drop a template's leading comment header (its "TEMPLATE — copy per app" preamble is
# wrong on a generated file) while preserving every comment further down, which explains
# the individual objects and is worth keeping.
strip_header() {
  local line started=0
  while IFS= read -r line; do
    if [ "${started}" -eq 0 ]; then
      case "${line}" in
        '#'*|'') continue ;;
        *) started=1 ;;
      esac
    fi
    printf '%s\n' "${line}"
  done < "$1"
}

# ---- 1. tenant scaffold: Namespace + ResourceQuota + LimitRange + default-deny ----
{
  cat <<HEADER
# GENERATED by scripts/new-tenant.sh from _tenant-scaffold.template.yaml — edit freely
# afterwards; this is a starting point, not a managed file.
#
# Layer-1 tenancy objects the PLATFORM owns for the ${TENANT} tenant. Paired with
# ${TENANT}.appproject.yaml, which forbids the app repos from creating these
# themselves. INERT until applied:
#   kubectl apply -f remote/argocd/projects/${TENANT}.tenant.yaml
---
HEADER
  strip_header "${TENANT_TEMPLATE}" | sed -e "s/<app>/${TENANT}/g"
} > "${TENANT_OUT}"

# ---- 2. AppProject: the enforced namespace/repo boundary ----
# Swap the template's single placeholder sourceRepos entry for this tenant's real repo
# list. Done as a line filter rather than a YAML edit to keep the script dependency-free
# (no yq) — the template is ours, so its shape is known.
{
  cat <<HEADER
# GENERATED by scripts/new-tenant.sh from _template.appproject.yaml.
#
# The enforced boundary for the ${TENANT} tenant: Applications under this project can
# only write to the ${TENANT} namespace, only from the repos listed below, and can
# create NO cluster-scoped resources. INERT until applied:
#   kubectl apply -f remote/argocd/projects/${TENANT}.appproject.yaml
HEADER
  in_repos=0
  strip_header "${PROJECT_TEMPLATE}" | sed -e "s/<app>/${TENANT}/g" \
  | while IFS= read -r line; do
      if [ "${in_repos}" -eq 1 ]; then
        # Swallow the template's placeholder entries; anything else ends the list.
        case "${line}" in
          '    - '*) continue ;;
          *) in_repos=0 ;;
        esac
      fi
      printf '%s\n' "${line}"
      if [ "${line}" = "  sourceRepos:" ]; then
        in_repos=1
        for repo in "${APP_REPOS[@]}"; do
          printf '    - "%s"\n' "${repo}"
        done
      fi
    done
} > "${PROJECT_OUT}"

# ---- 3. Applications: one per app repo, all in the tenant project/namespace ----
{
  cat <<HEADER
# GENERATED by scripts/new-tenant.sh — one Application per ${TENANT} service.
#
# repoURL is the PER-APP repo, not an org monorepo: monorepo apps/* are submodules
# (mode 160000) and repo-server runs with reposerver.enable.git.submodule=false, so an
# Application pointed at a monorepo renders EMPTY. Manifests live in each app repo at
# \`${APP_PATH}/\`. See docs/app-deploy-contract.md.
#
# PREREQS before applying (left inert until then, per the threefa/daedalus precedent):
#   1. apply remote/argocd/projects/${TENANT}.tenant.yaml     (Namespace + quota + default-deny)
#   2. apply remote/argocd/projects/${TENANT}.appproject.yaml (the enforced boundary)
#   3. commit + push each app repo's ${APP_PATH}/ dir to its ${REVISION}
#   4. publish each app's image (+ imagePullSecret if the registry is private)
#   5. seed the AWS Secrets Manager path the app's ExternalSecrets read
#   6. run any one-time DB migration (apps do not auto-migrate in-cluster)
#
# Promotion knob: flip targetRevision from \`${REVISION}\` to a pinned tag/sha per the contract.
HEADER
  first=1
  for i in "${!APP_NAMES[@]}"; do
    [ "${first}" -eq 1 ] || echo "---"
    first=0
    cat <<APP
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dd-${TENANT}-${APP_NAMES[$i]}
  namespace: argocd
spec:
  project: ${TENANT}
  source:
    repoURL: ${APP_REPOS[$i]}
    targetRevision: ${REVISION}
    path: ${APP_PATH}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${TENANT}
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ServerSideApply=true
APP
  done
} > "${APPS_OUT}"

echo "Generated (inert — nothing applied):"
for f in "${TENANT_OUT}" "${PROJECT_OUT}" "${APPS_OUT}"; do
  echo "  ${f#${REPO_ROOT}/}"
done
cat <<NEXT

Next, by hand and with eyes on the cluster:
  1. Review the generated quota/limits — the template defaults are deliberately small.
  2. Add the org's monorepo as an inventory submodule and note it in SUBMODULES.md.
  3. Work the PREREQS list at the top of ${APPS_OUT#${REPO_ROOT}/}.
  4. kubectl apply the tenant, then the appproject, then the applications — in that order.
NEXT
