// IMPORTANT FOR CODING AGENTS:
// - schema/schema.sql is the final source of truth for database shape.
// - Generated ORM/client files are adapters only; never treat them as migration authority.
// - Never run or apply migrations automatically. Generate SQL for human review and wait for
//   explicit user approval before any database write.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadSqlContract } from './sql-contract.mjs';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

async function main() {
  const { contract: schema, sourceSql } = await loadSqlContract(packageRoot);
  const args = new Set(process.argv.slice(2));

  if (args.has('--print-sql')) {
    process.stdout.write(sourceSql.endsWith('\n') ? sourceSql : `${sourceSql}\n`);
    return;
  }

  const outputs = renderOutputs(schema);

  if (args.has('--check')) {
    const stale = [];
    for (const [relativePath, contents] of outputs) {
      const absolutePath = path.join(packageRoot, relativePath);
      let existing = '';
      try {
        existing = await readFile(absolutePath, 'utf8');
      } catch {
        stale.push(relativePath);
        continue;
      }
      if (existing !== contents) {
        stale.push(relativePath);
      }
    }

    if (stale.length > 0) {
      console.error(
        `pg-defs generated outputs are stale:\n${stale.map((file) => `  - ${file}`).join('\n')}`,
      );
      process.exitCode = 1;
      return;
    }

    console.log('pg-defs generated outputs are up to date.');
    return;
  }

  for (const [relativePath, contents] of outputs) {
    const absolutePath = path.join(packageRoot, relativePath);
    await mkdir(path.dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, contents);
  }

  console.log(`Generated ${outputs.size} pg-defs adapter files.`);
}

function renderOutputs(schema) {
  return new Map([
    ['generated/typescript/index.ts', renderTypeScriptIndex()],
    ['generated/typescript/drizzle.ts', renderDrizzleTypeScript(schema)],
    ['generated/typescript/typeorm.ts', renderTypeOrmTypeScript(schema)],
    ['generated/prisma/schema.prisma', renderPrisma(schema)],
    ['generated/rust/Cargo.toml', renderRustCargo()],
    ['generated/rust/src/lib.rs', renderRust(schema)],
    ['generated/rust/diesel/Cargo.toml', renderDieselCargo()],
    ['generated/rust/diesel/src/lib.rs', renderDieselRust(schema)],
    ['generated/rust/sea-orm/Cargo.toml', renderSeaOrmCargo()],
    ['generated/rust/sea-orm/src/lib.rs', renderSeaOrmRust(schema)],
    ['generated/gleam/gleam.toml', renderGleamToml()],
    ['generated/gleam/src/pg_defs.gleam', renderGleam(schema)],
    ['generated/erlang/src/pg_defs.erl', renderErlang(schema)],
  ]);
}

function generatedNotice(prefix) {
  return [
    `${prefix} Generated by @dd/pg-defs. Do not edit by hand.`,
    `${prefix} SOURCE OF TRUTH: ../../schema/schema.sql defines the database contract.`,
    `${prefix} Generated ORM/client code is an adapter only; do not infer migrations from it.`,
    `${prefix} MIGRATION SAFETY: never run or apply migrations automatically. Require explicit human review and approval before any database write.`,
  ];
}

function renderTypeScriptIndex() {
  return `${[
    ...generatedNotice('//'),
    '// Import explicit adapters to avoid forcing every Node service to install every ORM peer.',
    '// Available files: ./drizzle.js and ./typeorm.js. Prisma is generated at ../prisma/schema.prisma.',
  ].join('\n')}\n`;
}

function renderDrizzleTypeScript(contract) {
  const lines = [
    ...generatedNotice('//'),
    'import { sql } from "drizzle-orm";',
    'import { boolean, check, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";',
    'import { z } from "zod";',
    '',
    'const textEncoder = new TextEncoder();',
    'const byteLength = (value: string) => textEncoder.encode(value).length;',
    'const jsonObjectSchema = z.record(z.string(), z.unknown());',
    'const jsonArraySchema = z.array(z.unknown());',
    '',
  ];

  for (const table of contract.tables) {
    const tableVar = table.names?.typescript ?? camel(table.name);
    const baseName = table.names?.rust ?? pascal(table.name);
    const enumColumns = table.columns.filter((column) => column.kind === 'enum');
    const literalColumns = table.columns.filter((column) => column.validation?.literal);

    for (const column of enumColumns) {
      const schemaName = `${camel(baseName)}${pascal(column.name)}Schema`;
      const valuesName = `${camel(baseName)}${pascal(column.name)}Values`;
      lines.push(`export const ${valuesName} = ${JSON.stringify(column.enumValues)} as const;`);
      lines.push(`export const ${schemaName} = z.enum(${valuesName});`);
      lines.push(`export type ${baseName}${pascal(column.name)} = z.infer<typeof ${schemaName}>;`);
      lines.push('');
    }

    for (const column of literalColumns) {
      const constantName = `${screaming(table.name)}_${screaming(column.name)}_DEFAULT`;
      lines.push(`export const ${constantName} = ${JSON.stringify(column.validation.literal)};`);
    }
    if (literalColumns.length > 0) {
      lines.push('');
    }

    lines.push(`export const ${tableVar} = pgTable(`);
    lines.push(`  ${JSON.stringify(table.name)},`);
    lines.push('  {');
    for (const column of table.columns) {
      lines.push(`    ${camel(column.name)}: ${drizzleColumn(column)},`);
    }
    lines.push('  },');
    lines.push('  (table) => ({');
    for (const checkConstraint of table.checks ?? []) {
      lines.push(
        `    ${camel(checkConstraint.name)}: check(${JSON.stringify(checkConstraint.name)}, sql.raw(${JSON.stringify(checkConstraint.sql)})),`,
      );
    }
    for (const tableIndex of table.indexes ?? []) {
      lines.push(`    ${camel(tableIndex.name)}: ${drizzleIndex(tableIndex)},`);
    }
    lines.push('  }),');
    lines.push(');');
    lines.push('');

    lines.push(`export const ${camel(baseName)}RowSchema = z.object({`);
    for (const column of table.columns) {
      lines.push(`  ${camel(column.name)}: ${zodColumn(table, column, { insert: false })},`);
    }
    lines.push('});');
    lines.push('');

    lines.push(`export const ${camel(baseName)}InsertSchema = z.object({`);
    for (const column of table.columns) {
      lines.push(`  ${camel(column.name)}: ${zodColumn(table, column, { insert: true })},`);
    }
    lines.push('});');
    lines.push('');
    lines.push(
      `export const ${camel(baseName)}UpdateSchema = ${camel(baseName)}InsertSchema.partial();`,
    );
    lines.push(`export type ${baseName}Row = z.infer<typeof ${camel(baseName)}RowSchema>;`);
    lines.push(`export type ${baseName}Insert = z.infer<typeof ${camel(baseName)}InsertSchema>;`);
    lines.push(`export type ${baseName}Update = z.infer<typeof ${camel(baseName)}UpdateSchema>;`);
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderTypeOrmTypeScript(contract) {
  const lines = [
    ...generatedNotice('//'),
    'import { Column, Entity, Index, PrimaryColumn, PrimaryGeneratedColumn } from "typeorm";',
    '',
  ];

  for (const table of contract.tables) {
    const entityName = `${table.names?.rust ?? pascal(table.name)}Entity`;

    for (const tableIndex of table.indexes ?? []) {
      if (tableIndex.method || tableIndex.columns.some((column) => typeof column !== 'string' && column.order)) {
        lines.push(
          `// ${tableIndex.name} lives in schema.sql because TypeORM decorators cannot fully model its method/order.`,
        );
        continue;
      }
      const properties = tableIndex.columns
        .map((column) => JSON.stringify(camel(typeof column === 'string' ? column : column.name)))
        .join(', ');
      const options = [];
      if (tableIndex.unique) {
        options.push('unique: true');
      }
      if (tableIndex.where) {
        options.push(`where: ${JSON.stringify(tableIndex.where)}`);
      }
      const optionsSql = options.length > 0 ? `, { ${options.join(', ')} }` : '';
      lines.push(`@Index(${JSON.stringify(tableIndex.name)}, [${properties}]${optionsSql})`);
    }

    lines.push(`@Entity({ name: ${JSON.stringify(table.name)} })`);
    lines.push(`export class ${entityName} {`);
    for (const column of table.columns) {
      lines.push(`  ${typeOrmDecorator(column)}`);
      lines.push(`  ${camel(column.name)}!: ${typeScriptType(column)};`);
      lines.push('');
    }
    lines.push('}');
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderPrisma(contract) {
  const lines = [
    ...generatedNotice('//'),
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    '  provider = "postgresql"',
    '  url      = env("DATABASE_URL")',
    '}',
    '',
  ];

  for (const table of contract.tables) {
    const modelName = table.names?.rust ?? pascal(table.name);
    lines.push(`model ${modelName} {`);
    for (const column of table.columns) {
      lines.push(`  ${prismaField(column)}`);
    }

    for (const tableIndex of table.indexes ?? []) {
      if (tableIndex.where || tableIndex.method) {
        lines.push(
          `  // ${tableIndex.name} is defined in schema.sql because Prisma cannot fully model ${tableIndex.method ? `${tableIndex.method} ` : ''}partial/expression indexes.`,
        );
        continue;
      }
      const fields = tableIndex.columns
        .map((column) => camel(typeof column === 'string' ? column : column.name))
        .join(', ');
      const indexKind = tableIndex.unique ? '@@unique' : '@@index';
      lines.push(`  ${indexKind}([${fields}], map: ${JSON.stringify(tableIndex.name)})`);
    }

    if ((table.checks ?? []).length > 0) {
      lines.push(
        '  // Check constraints live in schema.sql and must be migrated from the SQL contract.',
      );
    }
    lines.push(`  @@map(${JSON.stringify(table.name)})`);
    lines.push('}');
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function typeOrmDecorator(column) {
  if (column.primaryKey && column.defaultSql === 'gen_random_uuid()') {
    return `@PrimaryGeneratedColumn("uuid", { name: ${JSON.stringify(column.name)} })`;
  }
  if (column.primaryKey) {
    return `@PrimaryColumn(${typeOrmOptions(column)})`;
  }
  return `@Column(${typeOrmOptions(column)})`;
}

function typeOrmOptions(column) {
  const options = [
    `name: ${JSON.stringify(column.name)}`,
    `type: ${JSON.stringify(typeOrmColumnType(column))}`,
  ];
  if (column.maxLength) {
    options.push(`length: ${column.maxLength}`);
  }
  if (!column.notNull) {
    options.push('nullable: true');
  }
  if (column.defaultSql && !column.primaryKey) {
    options.push(`default: () => ${JSON.stringify(column.defaultSql)}`);
  }
  return `{ ${options.join(', ')} }`;
}

function typeOrmColumnType(column) {
  if (column.sqlType === 'timestamptz') {
    return 'timestamptz';
  }
  return column.sqlType;
}

function typeScriptType(column) {
  let baseType;
  switch (column.kind) {
    case 'integer':
      baseType = 'number';
      break;
    case 'boolean':
      baseType = 'boolean';
      break;
    case 'jsonObject':
      baseType = 'Record<string, unknown>';
      break;
    case 'jsonArray':
      baseType = 'unknown[]';
      break;
    case 'timestamp':
      baseType = 'Date';
      break;
    default:
      baseType = 'string';
      break;
  }
  return column.notNull ? baseType : `${baseType} | null`;
}

function prismaField(column) {
  const fieldName = camel(column.name);
  const attributes = [];
  if (fieldName !== column.name) {
    attributes.push(`@map(${JSON.stringify(column.name)})`);
  }
  if (column.primaryKey) {
    attributes.push('@id');
  }
  const defaultAttribute = prismaDefault(column);
  if (defaultAttribute) {
    attributes.push(defaultAttribute);
  }
  const dbAttribute = prismaDbAttribute(column);
  if (dbAttribute) {
    attributes.push(dbAttribute);
  }
  return `${fieldName} ${prismaType(column)} ${attributes.join(' ')}`.trimEnd();
}

function prismaType(column) {
  let baseType;
  switch (column.kind) {
    case 'integer':
      baseType = 'Int';
      break;
    case 'boolean':
      baseType = 'Boolean';
      break;
    case 'jsonObject':
    case 'jsonArray':
      baseType = 'Json';
      break;
    case 'timestamp':
      baseType = 'DateTime';
      break;
    default:
      baseType = 'String';
      break;
  }
  return column.notNull ? baseType : `${baseType}?`;
}

function prismaDbAttribute(column) {
  if (column.sqlType === 'uuid') {
    return '@db.Uuid';
  }
  if (column.sqlType === 'varchar') {
    return `@db.VarChar(${column.maxLength})`;
  }
  if (column.sqlType === 'text') {
    return '@db.Text';
  }
  if (column.sqlType === 'timestamptz') {
    return '@db.Timestamptz(6)';
  }
  return undefined;
}

function prismaDefault(column) {
  if (!column.defaultSql) {
    return undefined;
  }
  if (column.defaultSql === 'gen_random_uuid()') {
    return '@default(dbgenerated("gen_random_uuid()"))';
  }
  if (column.defaultSql === 'now()') {
    return '@default(now())';
  }
  if (column.kind === 'jsonObject') {
    return '@default("{}")';
  }
  if (column.kind === 'jsonArray') {
    return '@default("[]")';
  }
  if (typeof column.defaultValue === 'string') {
    return `@default(${JSON.stringify(column.defaultValue)})`;
  }
  if (typeof column.defaultValue === 'number' || typeof column.defaultValue === 'boolean') {
    return `@default(${column.defaultValue})`;
  }
  return `@default(dbgenerated(${JSON.stringify(column.defaultSql)}))`;
}

function drizzleColumn(column) {
  let builder;
  switch (column.sqlType) {
    case 'uuid':
      builder = `uuid(${JSON.stringify(column.name)})`;
      break;
    case 'varchar':
      builder = `varchar(${JSON.stringify(column.name)}, { length: ${column.maxLength} })`;
      break;
    case 'text':
      builder = `text(${JSON.stringify(column.name)})`;
      break;
    case 'integer':
      builder = `integer(${JSON.stringify(column.name)})`;
      break;
    case 'boolean':
      builder = `boolean(${JSON.stringify(column.name)})`;
      break;
    case 'jsonb':
      builder = `jsonb(${JSON.stringify(column.name)})`;
      break;
    case 'timestamptz':
      builder = `timestamp(${JSON.stringify(column.name)}, { withTimezone: true, mode: "string" })`;
      break;
    default:
      throw new Error(`Unsupported SQL type for Drizzle: ${column.sqlType}`);
  }

  if (column.defaultSql) {
    builder += `.default(sql\`${escapeTemplate(column.defaultSql)}\`)`;
  }
  if (column.primaryKey) {
    builder += '.primaryKey()';
  }
  if (column.notNull && !column.primaryKey) {
    builder += '.notNull()';
  }
  return builder;
}

function drizzleIndex(tableIndex) {
  const factory = tableIndex.unique ? 'uniqueIndex' : 'index';
  const parts = [`${factory}(${JSON.stringify(tableIndex.name)})`];
  const columns = tableIndex.columns.map((column) => {
    if (typeof column === 'string') {
      return `table.${camel(column)}`;
    }
    const base = `table.${camel(column.name)}`;
    return column.order === 'desc' ? `${base}.desc()` : base;
  });

  if (tableIndex.method) {
    parts.push(`using(${JSON.stringify(tableIndex.method)}, ${columns.join(', ')})`);
  } else {
    parts.push(`on(${columns.join(', ')})`);
  }

  if (tableIndex.where) {
    parts.push(`where(sql.raw(${JSON.stringify(tableIndex.where)}))`);
  }

  return parts.join('.');
}

function zodColumn(table, column, options) {
  let schemaExpression;
  switch (column.kind) {
    case 'uuid':
      schemaExpression = 'z.string().uuid()';
      break;
    case 'string':
      schemaExpression = 'z.string()';
      break;
    case 'enum':
      schemaExpression = `${camel(table.names?.rust ?? pascal(table.name))}${pascal(column.name)}Schema`;
      break;
    case 'integer':
      schemaExpression = 'z.number().int()';
      break;
    case 'boolean':
      schemaExpression = 'z.boolean()';
      break;
    case 'jsonObject':
      schemaExpression = 'jsonObjectSchema';
      break;
    case 'jsonArray':
      schemaExpression = 'jsonArraySchema';
      break;
    case 'timestamp':
      schemaExpression = 'z.string().datetime()';
      break;
    default:
      throw new Error(`Unsupported validation kind: ${column.kind}`);
  }

  const validation = column.validation ?? {};
  if (validation.literal) {
    schemaExpression = `z.literal(${screaming(table.name)}_${screaming(column.name)}_DEFAULT)`;
  } else {
    if (column.kind === 'string' && validation.minLength) {
      schemaExpression += `.min(${validation.minLength})`;
    }
    if (column.kind === 'string' && validation.maxLength) {
      schemaExpression += `.max(${validation.maxLength})`;
    }
    if (column.kind === 'string' && validation.regex) {
      schemaExpression += `.regex(/${validation.regex}/)`;
    }
    if (column.kind === 'string' && validation.maxBytes) {
      schemaExpression += `.refine((value) => byteLength(value) <= ${validation.maxBytes}, "Must be at most ${validation.maxBytes} bytes")`;
    }
    if (validation.min !== undefined) {
      schemaExpression += `.min(${validation.min})`;
    }
    if (validation.max !== undefined) {
      schemaExpression += `.max(${validation.max})`;
    }
  }

  if (!column.notNull) {
    schemaExpression += '.nullable()';
  }

  if (options.insert && (column.generated || column.defaultSql || !column.notNull)) {
    schemaExpression += '.optional()';
  }

  if (options.insert && column.defaultValue !== undefined && column.notNull) {
    schemaExpression += `.default(${JSON.stringify(column.defaultValue)})`;
  }

  return schemaExpression;
}

function renderRustCargo() {
  return `${[
    '[package]',
    'name = "dd-pg-defs"',
    'version = "0.1.0"',
    'edition = "2021"',
    '',
    '[dependencies]',
    'serde = { version = "1", features = ["derive"] }',
    'serde_json = "1"',
    'sqlx = { version = "0.8", default-features = false, features = ["postgres", "runtime-tokio-rustls", "json"], optional = true }',
    '',
    '[features]',
    'default = []',
    'sqlx = ["dep:sqlx"]',
  ].join('\n')}\n`;
}

function renderRust(contract) {
  const lines = [
    ...generatedNotice('//'),
    'use serde::{Deserialize, Serialize};',
    'use serde_json::Value;',
    '',
  ];

  for (const table of contract.tables) {
    const baseName = table.names?.rust ?? pascal(table.name);
    const tableConst = `${screaming(table.name)}_TABLE`;
    const selectConst = `${screaming(table.name)}_SELECT_SQL`;
    const columnsConst = `${screaming(table.name)}_COLUMNS`;

    lines.push(`pub const ${tableConst}: &str = ${JSON.stringify(table.name)};`);
    lines.push(
      `pub const ${columnsConst}: &[&str] = &[${table.columns.map((column) => JSON.stringify(column.name)).join(', ')}];`,
    );
    lines.push(`pub const ${selectConst}: &str = ${rustRawString(renderSelectSql(table))};`);
    lines.push('');

    for (const column of table.columns.filter((item) => item.kind === 'enum')) {
      lines.push(...renderRustEnum(baseName, column));
      lines.push('');
    }

    lines.push('#[derive(Clone, Debug, Serialize, Deserialize)]');
    lines.push('#[cfg_attr(feature = "sqlx", derive(sqlx::FromRow))]');
    lines.push('#[serde(rename_all = "camelCase")]');
    lines.push(`pub struct ${baseName}Row {`);
    for (const column of table.columns) {
      lines.push(`    pub ${column.name}: ${rustType(column)},`);
    }
    lines.push('}');
    lines.push('');

    lines.push('#[derive(Clone, Debug, Default, Serialize, Deserialize)]');
    lines.push('#[serde(rename_all = "camelCase")]');
    lines.push(`pub struct ${baseName}Insert {`);
    for (const column of table.columns) {
      lines.push(`    pub ${column.name}: ${rustInsertType(column)},`);
    }
    lines.push('}');
    lines.push('');

    lines.push(
      `pub fn validate_${table.name}_row(value: &${baseName}Row) -> Result<(), String> {`,
    );
    lines.push(...renderRustValidationStatements(table, 'value', false));
    lines.push('    Ok(())');
    lines.push('}');
    lines.push('');

    lines.push(
      `pub fn validate_${table.name}_insert(value: &${baseName}Insert) -> Result<(), String> {`,
    );
    lines.push(...renderRustValidationStatements(table, 'value', true));
    lines.push('    Ok(())');
    lines.push('}');
    lines.push('');
  }

  lines.push(
    'fn validate_string_length(field: &str, value: &str, min: Option<usize>, max: Option<usize>) -> Result<(), String> {',
  );
  lines.push('    let count = value.chars().count();');
  lines.push('    if let Some(min) = min {');
  lines.push('        if count < min {');
  lines.push('            return Err(format!("{field} must be at least {min} characters"));');
  lines.push('        }');
  lines.push('    }');
  lines.push('    if let Some(max) = max {');
  lines.push('        if count > max {');
  lines.push('            return Err(format!("{field} must be at most {max} characters"));');
  lines.push('        }');
  lines.push('    }');
  lines.push('    Ok(())');
  lines.push('}');
  lines.push('');
  lines.push('fn validate_slug(field: &str, value: &str) -> Result<(), String> {');
  lines.push('    let bytes = value.as_bytes();');
  lines.push('    if bytes.len() < 3 || bytes.len() > 120 {');
  lines.push('        return Err(format!("{field} must be 3-120 bytes"));');
  lines.push('    }');
  lines.push(
    '    let Some(first) = bytes.first() else { return Err(format!("{field} is required")); };',
  );
  lines.push(
    '    let Some(last) = bytes.last() else { return Err(format!("{field} is required")); };',
  );
  lines.push('    if !first.is_ascii_lowercase() && !first.is_ascii_digit() {');
  lines.push(
    '        return Err(format!("{field} must start with a lowercase letter or digit"));',
  );
  lines.push('    }');
  lines.push('    if !last.is_ascii_lowercase() && !last.is_ascii_digit() {');
  lines.push('        return Err(format!("{field} must end with a lowercase letter or digit"));');
  lines.push('    }');
  lines.push(
    "    if bytes.iter().any(|byte| !byte.is_ascii_lowercase() && !byte.is_ascii_digit() && *byte != b'-') {",
  );
  lines.push(
    '        return Err(format!("{field} may contain only lowercase letters, digits, and dashes"));',
  );
  lines.push('    }');
  lines.push('    Ok(())');
  lines.push('}');

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderRustEnum(baseName, column) {
  const enumName = `${baseName}${pascal(column.name)}`;
  const lines = [
    '#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]',
    '#[serde(rename_all = "lowercase")]',
    `pub enum ${enumName} {`,
  ];
  for (const value of column.enumValues) {
    lines.push(`    ${pascal(value)},`);
  }
  lines.push('}');
  lines.push('');
  lines.push(`impl ${enumName} {`);
  lines.push(
    `    pub const VALUES: &'static [&'static str] = &[${column.enumValues.map((value) => JSON.stringify(value)).join(', ')}];`,
  );
  lines.push('');
  lines.push("    pub fn as_str(self) -> &'static str {");
  lines.push('        match self {');
  for (const value of column.enumValues) {
    lines.push(`            Self::${pascal(value)} => ${JSON.stringify(value)},`);
  }
  lines.push('        }');
  lines.push('    }');
  lines.push('}');
  lines.push('');
  lines.push(`impl TryFrom<&str> for ${enumName} {`);
  lines.push('    type Error = String;');
  lines.push('');
  lines.push('    fn try_from(value: &str) -> Result<Self, Self::Error> {');
  lines.push('        match value {');
  for (const value of column.enumValues) {
    lines.push(`            ${JSON.stringify(value)} => Ok(Self::${pascal(value)}),`);
  }
  lines.push(`            _ => Err(format!("unsupported ${column.name}: {value}")),`);
  lines.push('        }');
  lines.push('    }');
  lines.push('}');
  return lines;
}

function rustType(column) {
  const baseType = rustBaseType(column);
  return column.notNull ? baseType : `Option<${baseType}>`;
}

function rustInsertType(column) {
  return `Option<${rustBaseType(column)}>`;
}

function rustBaseType(column) {
  switch (column.kind) {
    case 'integer':
      return 'i32';
    case 'boolean':
      return 'bool';
    case 'jsonObject':
    case 'jsonArray':
      return 'Value';
    default:
      return 'String';
  }
}

function renderRustValidationStatements(table, binding, insertMode) {
  const lines = [];
  for (const column of table.columns) {
    const validation = column.validation ?? {};
    const field = `${binding}.${column.name}`;
    const fieldName = `${table.name}.${column.name}`;
    const validationLines = rustValidationForColumn(column, validation, fieldName, 'value');

    if (insertMode) {
      if (validationLines.length === 0) {
        continue;
      }
      lines.push(`    if let Some(value) = &${field} {`);
      lines.push(...validationLines.map((line) => `        ${line}`));
      lines.push('    }');
      continue;
    }

    if (!column.notNull) {
      if (validationLines.length === 0) {
        continue;
      }
      lines.push(`    if let Some(value) = &${field} {`);
      lines.push(...validationLines.map((line) => `        ${line}`));
      lines.push('    }');
    } else {
      const requiredValidationLines = rustValidationForColumn(
        column,
        validation,
        fieldName,
        `&${field}`,
      );
      lines.push(...requiredValidationLines.map((line) => `    ${line}`));
    }
  }
  return lines;
}

function rustValidationForColumn(column, validation, fieldName, valueExpression) {
  const lines = [];

  if (validation.regex?.startsWith('^[a-z0-9]')) {
    lines.push(`validate_slug(${JSON.stringify(fieldName)}, ${valueExpression})?;`);
  } else if (column.kind === 'string') {
    const min = validation.minLength === undefined ? 'None' : `Some(${validation.minLength})`;
    const max = validation.maxLength === undefined ? 'None' : `Some(${validation.maxLength})`;
    if (validation.minLength !== undefined || validation.maxLength !== undefined) {
      lines.push(
        `validate_string_length(${JSON.stringify(fieldName)}, ${valueExpression}, ${min}, ${max})?;`,
      );
    }
  }

  if (validation.literal) {
    lines.push(
      `if (${valueExpression}).as_str() != ${JSON.stringify(validation.literal)} { return Err(${JSON.stringify(`${fieldName} must use the managed value`)}.to_string()); }`,
    );
  }
  if (validation.maxBytes) {
    lines.push(
      `if (${valueExpression}).as_bytes().len() > ${validation.maxBytes} { return Err(${JSON.stringify(`${fieldName} exceeds ${validation.maxBytes} bytes`)}.to_string()); }`,
    );
  }
  if (column.kind === 'enum') {
    lines.push(
      `if ![${column.enumValues.map((value) => JSON.stringify(value)).join(', ')}].contains(&(${valueExpression}).as_str()) { return Err(format!("unsupported ${fieldName}: {}", ${valueExpression})); }`,
    );
  }
  if (column.kind === 'integer') {
    if (validation.min !== undefined) {
      lines.push(
        `if *(${valueExpression}) < ${validation.min} { return Err(${JSON.stringify(`${fieldName} is below the minimum`)}.to_string()); }`,
      );
    }
    if (validation.max !== undefined) {
      lines.push(
        `if *(${valueExpression}) > ${validation.max} { return Err(${JSON.stringify(`${fieldName} is above the maximum`)}.to_string()); }`,
      );
    }
  }
  if (column.kind === 'jsonObject') {
    lines.push(
      `if !(${valueExpression}).is_object() { return Err(${JSON.stringify(`${fieldName} must be a JSON object`)}.to_string()); }`,
    );
  }
  if (column.kind === 'jsonArray') {
    lines.push(
      `if !(${valueExpression}).is_array() { return Err(${JSON.stringify(`${fieldName} must be a JSON array`)}.to_string()); }`,
    );
  }

  return lines;
}

function renderDieselCargo() {
  return `${[
    '[package]',
    'name = "dd-pg-defs-diesel"',
    'version = "0.1.0"',
    'edition = "2021"',
    '',
    '[dependencies]',
    'chrono = { version = "0.4", features = ["serde"] }',
    'diesel = { version = "2", features = ["postgres", "uuid", "serde_json", "chrono"] }',
    'serde = { version = "1", features = ["derive"] }',
    'serde_json = "1"',
    'uuid = { version = "1", features = ["serde"] }',
  ].join('\n')}\n`;
}

function renderDieselRust(contract) {
  const lines = [
    ...generatedNotice('//'),
    'use chrono::{DateTime, Utc};',
    'use diesel::prelude::*;',
    'use serde::{Deserialize, Serialize};',
    'use serde_json::Value;',
    'use uuid::Uuid;',
    '',
  ];

  for (const table of contract.tables) {
    const baseName = table.names?.rust ?? pascal(table.name);
    lines.push('diesel::table! {');
    lines.push('    use diesel::sql_types::*;');
    lines.push(`    ${table.name} (id) {`);
    for (const column of table.columns) {
      lines.push(`        ${column.name} -> ${dieselSqlType(column)},`);
    }
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('#[derive(Clone, Debug, Queryable, Selectable, Serialize, Deserialize)]');
    lines.push(`#[diesel(table_name = ${table.name})]`);
    lines.push(`pub struct ${baseName}DieselRow {`);
    for (const column of table.columns) {
      lines.push(`    pub ${column.name}: ${dieselRustType(column)},`);
    }
    lines.push('}');
    lines.push('');
    lines.push('#[derive(Clone, Debug, Insertable, AsChangeset, Serialize, Deserialize)]');
    lines.push(`#[diesel(table_name = ${table.name})]`);
    lines.push(`pub struct ${baseName}DieselInsert {`);
    for (const column of table.columns.filter((column) => !column.generated)) {
      lines.push(`    pub ${column.name}: ${dieselInsertRustType(column)},`);
    }
    lines.push('}');
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderSeaOrmCargo() {
  return `${[
    '[package]',
    'name = "dd-pg-defs-sea-orm"',
    'version = "0.1.0"',
    'edition = "2021"',
    '',
    '[dependencies]',
    'sea-orm = { version = "1", features = ["macros", "with-uuid", "with-json", "with-chrono"] }',
    'serde = { version = "1", features = ["derive"] }',
  ].join('\n')}\n`;
}

function renderSeaOrmRust(contract) {
  const lines = [
    ...generatedNotice('//'),
    'use sea_orm::entity::prelude::*;',
    'use serde::{Deserialize, Serialize};',
    '',
  ];

  for (const table of contract.tables) {
    lines.push('#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]');
    lines.push(`#[sea_orm(table_name = ${JSON.stringify(table.name)})]`);
    lines.push('pub struct Model {');
    for (const column of table.columns) {
      const attrs = [];
      if (column.primaryKey) {
        attrs.push('primary_key');
        if (column.sqlType === 'uuid') {
          attrs.push('auto_increment = false');
        }
      }
      if (column.name !== camel(column.name)) {
        attrs.push(`column_name = ${JSON.stringify(column.name)}`);
      }
      if (attrs.length > 0) {
        lines.push(`    #[sea_orm(${attrs.join(', ')})]`);
      }
      lines.push(`    pub ${column.name}: ${seaOrmRustType(column)},`);
    }
    lines.push('}');
    lines.push('');
    lines.push('#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]');
    lines.push('pub enum Relation {}');
    lines.push('');
    lines.push('impl ActiveModelBehavior for ActiveModel {}');
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function dieselSqlType(column) {
  const nullable = !column.notNull;
  let baseType;
  switch (column.sqlType) {
    case 'uuid':
      baseType = 'Uuid';
      break;
    case 'varchar':
      baseType = 'Varchar';
      break;
    case 'text':
      baseType = 'Text';
      break;
    case 'integer':
      baseType = 'Int4';
      break;
    case 'boolean':
      baseType = 'Bool';
      break;
    case 'jsonb':
      baseType = 'Jsonb';
      break;
    case 'timestamptz':
      baseType = 'Timestamptz';
      break;
    default:
      baseType = 'Text';
      break;
  }
  return nullable ? `Nullable<${baseType}>` : baseType;
}

function dieselRustType(column) {
  const baseType = rustDbType(column);
  return column.notNull ? baseType : `Option<${baseType}>`;
}

function dieselInsertRustType(column) {
  return `Option<${rustDbType(column)}>`;
}

function seaOrmRustType(column) {
  let baseType;
  switch (column.kind) {
    case 'uuid':
      baseType = 'Uuid';
      break;
    case 'integer':
      baseType = 'i32';
      break;
    case 'boolean':
      baseType = 'bool';
      break;
    case 'jsonObject':
    case 'jsonArray':
      baseType = 'Json';
      break;
    case 'timestamp':
      baseType = 'DateTimeWithTimeZone';
      break;
    default:
      baseType = 'String';
      break;
  }
  return column.notNull ? baseType : `Option<${baseType}>`;
}

function rustDbType(column) {
  switch (column.kind) {
    case 'uuid':
      return 'Uuid';
    case 'integer':
      return 'i32';
    case 'boolean':
      return 'bool';
    case 'jsonObject':
    case 'jsonArray':
      return 'Value';
    case 'timestamp':
      return 'DateTime<Utc>';
    default:
      return 'String';
  }
}

function renderGleamToml() {
  return `${[
    'name = "dd_pg_defs"',
    'version = "0.1.0"',
    'target = "erlang"',
    '',
    '[dependencies]',
    'gleam_stdlib = ">= 0.68.0 and < 2.0.0"',
    'pog = ">= 4.1.0 and < 5.0.0"',
  ].join('\n')}\n`;
}

function renderGleam(contract) {
  const lines = [
    ...generatedNotice('////'),
    'import gleam/list',
    'import gleam/option.{type Option}',
    'import gleam/string',
    '',
  ];

  for (const table of contract.tables) {
    const baseName = table.names?.gleam ?? pascal(table.name);
    lines.push(`pub const ${table.name}_table = ${JSON.stringify(table.name)}`);
    lines.push(
      `pub const ${table.name}_select_sql = ${JSON.stringify(renderSelectSql(table, { jsonAsText: true }))}`,
    );
    lines.push('');

    for (const column of table.columns.filter((item) => item.kind === 'enum')) {
      const typeName = `${baseName}${pascal(column.name)}`;
      lines.push(`pub type ${typeName} {`);
      for (const value of column.enumValues) {
        lines.push(`  ${pascal(value)}`);
      }
      lines.push('}');
      lines.push('');
      lines.push(`pub fn ${table.name}_${column.name}_to_string(value: ${typeName}) -> String {`);
      lines.push('  case value {');
      for (const value of column.enumValues) {
        lines.push(`    ${pascal(value)} -> ${JSON.stringify(value)}`);
      }
      lines.push('  }');
      lines.push('}');
      lines.push('');
      lines.push(
        `pub fn parse_${table.name}_${column.name}(value: String) -> Result(${typeName}, String) {`,
      );
      lines.push('  case value {');
      for (const value of column.enumValues) {
        lines.push(`    ${JSON.stringify(value)} -> Ok(${pascal(value)})`);
      }
      lines.push(`    _ -> Error("unsupported ${table.name}.${column.name}: " <> value)`);
      lines.push('  }');
      lines.push('}');
      lines.push('');
    }

    lines.push(`pub type ${baseName}Row {`);
    lines.push(`  ${baseName}Row(`);
    for (const column of table.columns) {
      lines.push(`    ${gleamFieldName(column)}: ${gleamType(column)},`);
    }
    lines.push('  )');
    lines.push('}');
    lines.push('');

    lines.push(`pub fn validate_${table.name}_slug(value: String) -> Result(String, String) {`);
    lines.push('  let length = string.length(value)');
    lines.push('  case length >= 3 && length <= 120 && is_slug_text(value) {');
    lines.push('    True -> Ok(value)');
    lines.push(
      `    False -> Error("${table.name}.slug must be a lowercase slug 3-120 characters long")`,
    );
    lines.push('  }');
    lines.push('}');
    lines.push('');

    for (const column of table.columns.filter((item) => item.kind === 'enum')) {
      lines.push(
        `pub fn validate_${table.name}_${column.name}(value: String) -> Result(String, String) {`,
      );
      lines.push(
        `  case list.contains([${column.enumValues.map((value) => JSON.stringify(value)).join(', ')}], value) {`,
      );
      lines.push('    True -> Ok(value)');
      lines.push(`    False -> Error("unsupported ${table.name}.${column.name}: " <> value)`);
      lines.push('  }');
      lines.push('}');
      lines.push('');
    }
  }

  lines.push('fn is_slug_text(value: String) -> Bool {');
  lines.push('  let chars = string.to_graphemes(value)');
  lines.push('  case chars {');
  lines.push('    [] -> False');
  lines.push('    [first, ..rest] -> {');
  lines.push('      let last_ok = case list.last(chars) {');
  lines.push('        Ok(last) -> is_slug_edge(last)');
  lines.push('        Error(_) -> False');
  lines.push('      }');
  lines.push(
    '      is_slug_edge(first) && list.all(rest, fn(item) { is_slug_char(item) }) && last_ok',
  );
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('fn is_slug_edge(value: String) -> Bool {');
  lines.push('  is_lower_ascii(value) || is_digit(value)');
  lines.push('}');
  lines.push('');
  lines.push('fn is_slug_char(value: String) -> Bool {');
  lines.push('  is_slug_edge(value) || value == "-"');
  lines.push('}');
  lines.push('');
  lines.push('fn is_lower_ascii(value: String) -> Bool {');
  lines.push(
    '  list.contains(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"], value)',
  );
  lines.push('}');
  lines.push('');
  lines.push('fn is_digit(value: String) -> Bool {');
  lines.push('  list.contains(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"], value)');
  lines.push('}');

  return `${lines.join('\n').trimEnd()}\n`;
}

function gleamType(column) {
  let baseType;
  switch (column.kind) {
    case 'integer':
      baseType = 'Int';
      break;
    case 'boolean':
      baseType = 'Bool';
      break;
    default:
      baseType = 'String';
      break;
  }
  return column.notNull ? baseType : `Option(${baseType})`;
}

function gleamFieldName(column) {
  if (column.kind === 'jsonObject' || column.kind === 'jsonArray') {
    return `${column.name}_json`;
  }
  return column.name;
}

function renderErlang(contract) {
  const exports = [];
  const functions = [];

  for (const table of contract.tables) {
    exports.push(`${table.name}_table/0`);
    exports.push(`${table.name}_columns/0`);
    exports.push(`${table.name}_select_sql/0`);
    functions.push(`${table.name}_table() -> ${erlangBinary(table.name)}.`);
    functions.push('');
    functions.push(
      `${table.name}_columns() -> [${table.columns.map((column) => erlangBinary(column.name)).join(', ')}].`,
    );
    functions.push('');
    functions.push(
      `${table.name}_select_sql() -> ${erlangBinary(renderSelectSql(table, { jsonAsText: true }))}.`,
    );
    functions.push('');

    for (const column of table.columns.filter((item) => item.kind === 'enum')) {
      exports.push(`${table.name}_${column.name}_values/0`);
      exports.push(`validate_${table.name}_${column.name}/1`);
      functions.push(
        `${table.name}_${column.name}_values() -> [${column.enumValues.map(erlangBinary).join(', ')}].`,
      );
      functions.push('');
      functions.push(`validate_${table.name}_${column.name}(Value) when is_binary(Value) ->`);
      functions.push(`    case lists:member(Value, ${table.name}_${column.name}_values()) of`);
      functions.push('        true -> ok;');
      functions.push(
        `        false -> {error, <<\"unsupported ${table.name}.${column.name}: \"/binary, Value/binary>>}`,
      );
      functions.push('    end;');
      functions.push(`validate_${table.name}_${column.name}(Value) when is_list(Value) ->`);
      functions.push(
        `    validate_${table.name}_${column.name}(unicode:characters_to_binary(Value)).`,
      );
      functions.push('');
    }
  }

  return `${[
    ...generatedNotice('%'),
    '-module(pg_defs).',
    `-export([${exports.join(', ')}]).`,
    '',
    ...functions,
  ]
    .join('\n')
    .trimEnd()}\n`;
}

function renderDdl(contract) {
  const blocks = [];
  for (const table of contract.tables) {
    blocks.push(renderCreateTable(table));
    for (const tableIndex of table.indexes ?? []) {
      blocks.push(renderCreateIndex(table, tableIndex));
    }
  }
  return `${blocks.join('\n\n')}\n`;
}

function renderCreateTable(table) {
  const definitions = [];
  for (const column of table.columns) {
    definitions.push(
      `  ${column.name} ${columnTypeSql(column)}${column.primaryKey ? ' primary key' : ''}${column.defaultSql ? ` default ${column.defaultSql}` : ''}${column.notNull && !column.primaryKey ? ' not null' : ''}`,
    );
  }
  for (const checkConstraint of table.checks ?? []) {
    definitions.push(`  constraint ${checkConstraint.name}\n    check (${checkConstraint.sql})`);
  }
  return `create table if not exists ${table.name} (\n${definitions.join(',\n')}\n);`;
}

function renderCreateIndex(table, tableIndex) {
  const unique = tableIndex.unique ? 'unique ' : '';
  const method = tableIndex.method ? ` using ${tableIndex.method}` : '';
  const columns = tableIndex.columns.map((column) => {
    if (typeof column === 'string') {
      return column;
    }
    return `${column.name}${column.order ? ` ${column.order}` : ''}`;
  });
  const where = tableIndex.where ? `\n  where ${tableIndex.where}` : '';
  return `create ${unique}index if not exists ${tableIndex.name}\n  on ${table.name}${method} (${columns.join(', ')})${where};`;
}

function columnTypeSql(column) {
  if (column.sqlType === 'varchar') {
    return `varchar(${column.maxLength})`;
  }
  return column.sqlType;
}

function renderSelectSql(table, options = {}) {
  const columns = table.columns
    .map((column) => `      ${selectExpression(column, options)}`)
    .join(',\n');
  return `select\n${columns}\n    from ${table.name}`;
}

function selectExpression(column, options = {}) {
  if (column.kind === 'uuid') {
    return `${column.name}::text as ${column.name}`;
  }
  if (column.kind === 'timestamp') {
    return `to_char(${column.name} at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') as ${column.name}`;
  }
  if (column.kind === 'jsonObject' || column.kind === 'jsonArray') {
    if (options.jsonAsText) {
      return `${column.name}::text as ${column.name}_json`;
    }
    return `${column.name}`;
  }
  return column.name;
}

function camel(value) {
  const pascalValue = pascal(value);
  return `${pascalValue.charAt(0).toLowerCase()}${pascalValue.slice(1)}`;
}

function pascal(value) {
  return value
    .split(/[_-]/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');
}

function screaming(value) {
  return value
    .replace(/-/g, '_')
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .toUpperCase();
}

function escapeTemplate(value) {
  return value.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function rustRawString(value) {
  return `r###"${value}"###`;
}

function erlangBinary(value) {
  return `<<"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}">>`;
}

await main();
