apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: benefactor-ghcr
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-cluster-secrets
  target:
    name: benefactor-ghcr
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: dd/benefactor/ghcr-pull
        property: dockerconfigjson
