apiVersion: v1
kind: Service
metadata:
  name: dd-contract-service
  namespace: default
  labels:
    app: dd-contract-service
spec:
  selector:
    app: dd-contract-service
  ports:
    - name: http
      port: 8101
      targetPort: http
