apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dd-dataset-labeling
  namespace: default
  labels:
    app: dd-dataset-labeling
spec:
  podSelector:
    matchLabels:
      app: dd-dataset-labeling
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: dd-remote-gateway
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - dd-prometheus
                  - dd-otel-collector
      ports:
        - protocol: TCP
          port: 8138
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: messaging
          podSelector:
            matchLabels:
              app: dd-nats
      ports:
        - protocol: TCP
          port: 4222
