apiVersion: v1
kind: Service
metadata:
  name: dd-des-simulator
  namespace: default
  labels:
    app: dd-des-simulator
spec:
  selector:
    app: dd-des-simulator
  ports:
    - name: http
      port: 8099
      targetPort: http
