apiVersion: v1
kind: Service
metadata:
  name: dd-public-data-server
  namespace: default
  labels:
    app: dd-public-data-server
spec:
  selector:
    app: dd-public-data-server
  ports:
    - name: http
      port: 8115
      targetPort: http
