apiVersion: v1
kind: Service
metadata:
  name: dd-remote-auth
  namespace: default
  labels:
    app: dd-remote-auth
spec:
  type: ClusterIP
  selector:
    app: dd-remote-auth
  ports:
    - name: http
      port: 8083
      targetPort: 8083
