apiVersion: v1
kind: Service
metadata:
  name: dd-remote-rest-api
  namespace: default
  labels:
    app: dd-remote-rest-api
spec:
  type: ClusterIP
  selector:
    app: dd-remote-rest-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082
