apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dd-sound-recorder-rs
  namespace: default
  labels:
    app: dd-sound-recorder-rs
spec:
  podSelector:
    matchLabels:
      app: dd-sound-recorder-rs
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: dd-remote-gateway
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - dd-prometheus
                  - dd-otel-collector
      ports:
        - protocol: TCP
          port: 8126
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 172.16.0.0/12
        - ipBlock:
            cidr: 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 5432
