apiVersion: v1
kind: Service
metadata:
  name: usacc-rest-api-backend-rs
  namespace: default
  labels:
    app: usacc-rest-api-backend-rs
spec:
  selector:
    app: usacc-rest-api-backend-rs
  ports:
    - name: http
      port: 8121
      targetPort: http
