apiVersion: v1
kind: Service
metadata:
  name: gcs-mongodb-headless
  namespace: default
  labels:
    app: gcs-mongodb
    role: headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: gcs-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
