//! Named FDM printer models the service explicitly supports.
//!
//! The default fleet and most planning flows describe machines structurally
//! (kind, controller, envelope). This catalog pins the vendor models we commit
//! to supporting so callers can reference them by name ("creality-k1") and the
//! FDM printer catalog can advertise their real envelopes and limits.

use serde_json::{json, Value};

pub(crate) struct FdmPrinterModelSpec {
    /// Normalized model token (`normalize_token` form), e.g. "creality-k1".
    pub(crate) model: &'static str,
    pub(crate) vendor: &'static str,
    pub(crate) display_name: &'static str,
    /// Extra normalized tokens that resolve to this model.
    pub(crate) aliases: &'static [&'static str],
    /// Canonical machine kind the model maps to in fleet/profile terms.
    pub(crate) machine_kind: &'static str,
    pub(crate) controller: &'static str,
    pub(crate) kinematics: &'static str,
    pub(crate) work_envelope_mm: [f64; 3],
    pub(crate) max_print_speed_mm_s: f64,
    pub(crate) max_acceleration_mm_s2: f64,
    pub(crate) max_nozzle_temp_c: f64,
    pub(crate) max_bed_temp_c: f64,
    pub(crate) max_volumetric_flow_mm3_s: f64,
    pub(crate) enclosed: bool,
    pub(crate) max_materials: u16,
    pub(crate) materials: &'static [&'static str],
    pub(crate) operations: &'static [&'static str],
    pub(crate) notes: &'static str,
}

pub(crate) const FDM_PRINTER_MODEL_SPECS: &[FdmPrinterModelSpec] = &[
    FdmPrinterModelSpec {
        model: "creality-k1",
        vendor: "Creality",
        display_name: "Creality K1",
        aliases: &["k1"],
        machine_kind: "fdm-printer",
        controller: "klipper",
        kinematics: "corexy",
        work_envelope_mm: [220.0, 220.0, 250.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 32.0,
        enclosed: true,
        max_materials: 1,
        materials: &["pla", "petg", "abs", "tpu"],
        operations: &["additive-print"],
        notes: "High-speed enclosed CoreXY running Creality OS (Klipper-based); \
                accepts klipper-flavored G-code.",
    },
    FdmPrinterModelSpec {
        model: "creality-k2",
        vendor: "Creality",
        display_name: "Creality K2",
        aliases: &["k2"],
        machine_kind: "fdm-printer",
        controller: "klipper",
        kinematics: "corexy",
        work_envelope_mm: [260.0, 260.0, 260.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 32.0,
        enclosed: true,
        max_materials: 1,
        materials: &["pla", "petg", "abs", "asa", "tpu"],
        operations: &[
            "additive-print",
            "corexy-print",
            "high-speed-fdm-print",
            "direct-drive-extrusion",
            "input-shaping",
            "smart-auto-leveling",
            "filament-runout-detection",
            "power-loss-recovery",
            "creality-print-slicer",
            "lan-or-wifi-print",
            "cfs-ready",
        ],
        notes: "Base enclosed CoreXY running Creality OS (Klipper-based); \
                accepts klipper-flavored G-code and is CFS-ready, but this \
                profile does not assume the optional CFS is installed.",
    },
    FdmPrinterModelSpec {
        model: "creality-k2-cfs",
        vendor: "Creality",
        display_name: "Creality K2 with CFS",
        aliases: &[
            "creality-k2-with-cfs",
            "creality-k2-combo",
            "k2-combo",
            "k2-cfs",
        ],
        machine_kind: "multi-material-fdm-printer",
        controller: "klipper",
        kinematics: "corexy",
        work_envelope_mm: [260.0, 260.0, 260.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 32.0,
        enclosed: true,
        max_materials: 16,
        materials: &[
            "pla",
            "petg",
            "abs",
            "asa",
            "tpu",
            "pva",
            "hips",
            "support-material",
        ],
        operations: &[
            "additive-print",
            "multi-material-fdm-print",
            "ams-mmu-print",
            "material-map",
            "purge-tower",
            "wipe-tower",
            "filament-change-automation",
            "creality-filament-system-print",
            "automatic-filament-backup",
        ],
        notes: "Enclosed CoreXY running Creality OS (Klipper-based) with the \
                optional CFS installed; supports multi-material printing from \
                up to 16 spools when four CFS units are chained.",
    },
    FdmPrinterModelSpec {
        model: "bambu-a1",
        vendor: "Bambu Lab",
        display_name: "Bambu Lab A1",
        aliases: &["a1", "bambu-lab-a1"],
        machine_kind: "fdm-printer",
        controller: "bambu",
        kinematics: "cartesian",
        work_envelope_mm: [256.0, 256.0, 256.0],
        max_print_speed_mm_s: 500.0,
        max_acceleration_mm_s2: 10_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 28.0,
        enclosed: false,
        max_materials: 1,
        materials: &["pla", "petg", "tpu"],
        operations: &["additive-print"],
        notes: "Open-frame Cartesian bed-slinger running Bambu firmware; accepts \
                Bambu-flavored G-code from Bambu Studio / OrcaSlicer. The open frame \
                is validated for PLA/PETG/TPU, not ABS/ASA.",
    },
    FdmPrinterModelSpec {
        model: "bambu-a1-combo",
        vendor: "Bambu Lab",
        display_name: "Bambu Lab A1 Combo",
        aliases: &[
            "a1-combo",
            "bambu-lab-a1-combo",
            "a1-ams-lite",
            "bambu-a1-ams",
        ],
        machine_kind: "multi-material-fdm-printer",
        controller: "bambu",
        kinematics: "cartesian",
        work_envelope_mm: [256.0, 256.0, 256.0],
        max_print_speed_mm_s: 500.0,
        max_acceleration_mm_s2: 10_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 28.0,
        enclosed: false,
        max_materials: 4,
        materials: &["pla", "petg", "tpu", "pva", "support-material"],
        operations: &[
            "additive-print",
            "multi-material-fdm-print",
            "ams-mmu-print",
            "material-map",
            "purge-tower",
            "wipe-tower",
            "filament-change-automation",
        ],
        notes: "A1 with a single AMS Lite (4-slot, not chainable) for multi-material; \
                open-frame Cartesian bed-slinger running Bambu firmware/G-code. The open \
                frame limits it to PLA/PETG/TPU plus PVA/support interfaces.",
    },
    FdmPrinterModelSpec {
        model: "bambu-a1-mini",
        vendor: "Bambu Lab",
        display_name: "Bambu Lab A1 mini",
        aliases: &["a1-mini", "bambu-lab-a1-mini"],
        machine_kind: "fdm-printer",
        controller: "bambu",
        kinematics: "cartesian",
        work_envelope_mm: [180.0, 180.0, 180.0],
        max_print_speed_mm_s: 500.0,
        max_acceleration_mm_s2: 10_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 80.0,
        max_volumetric_flow_mm3_s: 28.0,
        enclosed: false,
        max_materials: 1,
        materials: &["pla", "petg", "tpu"],
        operations: &["additive-print"],
        notes: "Compact open-frame Cartesian bed-slinger (180 mm cube, bed to 80 °C) \
                running Bambu firmware; accepts Bambu-flavored G-code.",
    },
    FdmPrinterModelSpec {
        model: "bambu-a1-mini-combo",
        vendor: "Bambu Lab",
        display_name: "Bambu Lab A1 mini Combo",
        aliases: &["a1-mini-combo", "bambu-lab-a1-mini-combo"],
        machine_kind: "multi-material-fdm-printer",
        controller: "bambu",
        kinematics: "cartesian",
        work_envelope_mm: [180.0, 180.0, 180.0],
        max_print_speed_mm_s: 500.0,
        max_acceleration_mm_s2: 10_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 80.0,
        max_volumetric_flow_mm3_s: 28.0,
        enclosed: false,
        max_materials: 4,
        materials: &["pla", "petg", "tpu", "pva", "support-material"],
        operations: &[
            "additive-print",
            "multi-material-fdm-print",
            "ams-mmu-print",
            "material-map",
            "purge-tower",
            "wipe-tower",
            "filament-change-automation",
        ],
        notes: "A1 mini with a single AMS Lite (4-slot) for multi-material; compact \
                open-frame Cartesian bed-slinger running Bambu firmware/G-code.",
    },
    FdmPrinterModelSpec {
        model: "bambu-p1s",
        vendor: "Bambu Lab",
        display_name: "Bambu Lab P1S",
        aliases: &["p1s", "bambu-lab-p1s", "p1s-combo", "bambu-p1s-combo"],
        machine_kind: "multi-material-fdm-printer",
        controller: "bambu",
        kinematics: "corexy",
        work_envelope_mm: [256.0, 256.0, 256.0],
        max_print_speed_mm_s: 500.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 32.0,
        enclosed: true,
        max_materials: 16,
        materials: &[
            "pla",
            "petg",
            "abs",
            "asa",
            "tpu",
            "pva",
            "hips",
            "pc",
            "support-material",
        ],
        operations: &[
            "additive-print",
            "multi-material-fdm-print",
            "ams-mmu-print",
            "material-map",
            "purge-tower",
            "wipe-tower",
            "filament-change-automation",
        ],
        notes: "Enclosed CoreXY running Bambu firmware; AMS multi-material up to 16 \
                spools when four AMS units are chained. The enclosure enables ABS/ASA/PC. \
                Accepts Bambu-flavored G-code.",
    },
    FdmPrinterModelSpec {
        model: "bambu-x1-carbon",
        vendor: "Bambu Lab",
        display_name: "Bambu Lab X1 Carbon",
        aliases: &[
            "x1-carbon",
            "x1c",
            "bambu-x1c",
            "bambu-lab-x1-carbon",
            "x1-carbon-combo",
        ],
        machine_kind: "multi-material-fdm-printer",
        controller: "bambu",
        kinematics: "corexy",
        work_envelope_mm: [256.0, 256.0, 256.0],
        max_print_speed_mm_s: 500.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 110.0,
        max_volumetric_flow_mm3_s: 32.0,
        enclosed: true,
        max_materials: 16,
        materials: &[
            "pla",
            "petg",
            "abs",
            "asa",
            "tpu",
            "pva",
            "hips",
            "pc",
            "pa",
            "support-material",
        ],
        operations: &[
            "additive-print",
            "multi-material-fdm-print",
            "ams-mmu-print",
            "material-map",
            "purge-tower",
            "wipe-tower",
            "filament-change-automation",
        ],
        notes: "Enclosed CoreXY flagship (lidar + AMS) running Bambu firmware; AMS \
                multi-material up to 16 spools; hardened-nozzle option for abrasive \
                PA/PC composites; bed to 110 °C. Accepts Bambu-flavored G-code.",
    },
    // --- Popular post-2024 releases ---
    FdmPrinterModelSpec {
        model: "bambu-h2d",
        vendor: "Bambu Lab",
        display_name: "Bambu Lab H2D",
        aliases: &["h2d", "bambu-lab-h2d", "h2d-combo", "bambu-h2d-combo"],
        machine_kind: "multi-material-fdm-printer",
        controller: "bambu",
        kinematics: "corexy",
        // Single-nozzle build volume; dual-nozzle mode trades some X.
        work_envelope_mm: [325.0, 320.0, 325.0],
        max_print_speed_mm_s: 1000.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 350.0,
        max_bed_temp_c: 120.0,
        max_volumetric_flow_mm3_s: 40.0,
        enclosed: true,
        max_materials: 16,
        materials: &[
            "pla",
            "petg",
            "abs",
            "asa",
            "tpu",
            "pva",
            "hips",
            "pc",
            "pa",
            "carbon-fiber",
            "glass-fiber",
            "support-material",
        ],
        operations: &[
            "additive-print",
            "dual-nozzle-print",
            "multi-material-fdm-print",
            "ams-mmu-print",
            "material-map",
            "purge-tower",
            "wipe-tower",
            "filament-change-automation",
        ],
        notes: "2025 dual-nozzle enclosed CoreXY flagship: two independent hotends \
                (soluble support or two materials in one layer), 65 °C active chamber, \
                350 °C hotend for CF/GF composites, AMS multi-material up to 16 spools. \
                Runs Bambu firmware; accepts Bambu-flavored G-code.",
    },
    FdmPrinterModelSpec {
        model: "prusa-core-one",
        vendor: "Prusa Research",
        display_name: "Prusa CORE One",
        aliases: &[
            "core-one",
            "coreone",
            "prusa-core-one-plus",
            "core-one-plus",
        ],
        machine_kind: "fdm-printer",
        // Prusa Buddy firmware is Marlin-derived and consumes Marlin/RepRap G-code.
        controller: "marlin",
        kinematics: "corexy",
        work_envelope_mm: [250.0, 220.0, 270.0],
        max_print_speed_mm_s: 500.0,
        max_acceleration_mm_s2: 10_000.0,
        max_nozzle_temp_c: 290.0,
        max_bed_temp_c: 120.0,
        max_volumetric_flow_mm3_s: 24.0,
        enclosed: true,
        max_materials: 1,
        materials: &[
            "pla",
            "petg",
            "abs",
            "asa",
            "tpu",
            "pc",
            "pa",
            "support-material",
        ],
        operations: &["additive-print"],
        notes: "Prusa's first fully-enclosed CoreXY (shipping 2025): active chamber \
                control to ~55 °C, 290 °C nozzle, 120 °C bed. Runs Prusa Buddy firmware \
                (Marlin-based) and consumes Marlin/RepRap-flavored G-code. Base unit is \
                single-material; MMU3 (5) or INDX (8) add multi-material.",
    },
    FdmPrinterModelSpec {
        model: "creality-k1c",
        vendor: "Creality",
        display_name: "Creality K1C",
        aliases: &["k1c"],
        machine_kind: "fdm-printer",
        controller: "klipper",
        kinematics: "corexy",
        work_envelope_mm: [220.0, 220.0, 250.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 32.0,
        enclosed: true,
        max_materials: 1,
        materials: &["pla", "petg", "abs", "asa", "tpu", "pa", "carbon-fiber"],
        operations: &["additive-print"],
        notes: "2024 carbon-capable K1: hardened steel nozzle and tri-metal heatbreak \
                for CF/PA out of the box, enclosed CoreXY, Creality OS (Klipper-based); \
                accepts klipper-flavored G-code.",
    },
    FdmPrinterModelSpec {
        model: "elegoo-centauri-carbon",
        vendor: "Elegoo",
        display_name: "Elegoo Centauri Carbon",
        aliases: &["centauri-carbon", "elegoo-centauri", "centauri"],
        machine_kind: "fdm-printer",
        controller: "klipper",
        kinematics: "corexy",
        work_envelope_mm: [256.0, 256.0, 256.0],
        max_print_speed_mm_s: 500.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 320.0,
        max_bed_temp_c: 110.0,
        max_volumetric_flow_mm3_s: 25.0,
        enclosed: true,
        max_materials: 1,
        materials: &["pla", "petg", "abs", "asa", "tpu", "pa", "carbon-fiber"],
        operations: &["additive-print"],
        notes: "2025 affordable fully-enclosed CoreXY: 320 °C hardened nozzle for \
                carbon-fiber, 110 °C bed, runs a Klipper fork (Fluidd UI); accepts \
                klipper-flavored G-code.",
    },
    // --- Additional mainstream FDM makes ---
    FdmPrinterModelSpec {
        model: "anycubic-kobra-3-combo",
        vendor: "Anycubic",
        display_name: "Anycubic Kobra 3 Combo",
        aliases: &["kobra-3-combo", "kobra3-combo", "anycubic-kobra3-combo"],
        machine_kind: "multi-material-fdm-printer",
        controller: "klipper",
        kinematics: "cartesian",
        work_envelope_mm: [250.0, 250.0, 260.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 300.0,
        max_bed_temp_c: 110.0,
        max_volumetric_flow_mm3_s: 18.0,
        enclosed: false,
        max_materials: 8,
        materials: &["pla", "petg", "tpu", "support-material"],
        operations: &[
            "additive-print",
            "multi-material-fdm-print",
            "ams-mmu-print",
            "material-map",
            "purge-tower",
            "wipe-tower",
            "filament-change-automation",
        ],
        notes: "Open-frame Cartesian Kobra OS (GoKlipper-family) printer with ACE Pro: \
                four-color with one ACE Pro or eight-color with two units. TPU is supported \
                only from the printer's direct spool path, not through ACE Pro. Accepts \
                klipper-flavored G-code.",
    },
    FdmPrinterModelSpec {
        model: "anycubic-kobra-s1-combo",
        vendor: "Anycubic",
        display_name: "Anycubic Kobra S1 Combo",
        aliases: &["kobra-s1-combo", "kobras1-combo", "anycubic-kobras1-combo"],
        machine_kind: "multi-material-fdm-printer",
        controller: "klipper",
        kinematics: "corexy",
        work_envelope_mm: [250.0, 250.0, 250.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 320.0,
        max_bed_temp_c: 120.0,
        max_volumetric_flow_mm3_s: 18.0,
        enclosed: true,
        max_materials: 8,
        materials: &["pla", "petg", "abs", "asa", "tpu", "support-material"],
        operations: &[
            "additive-print",
            "multi-material-fdm-print",
            "ams-mmu-print",
            "material-map",
            "purge-tower",
            "wipe-tower",
            "filament-change-automation",
        ],
        notes: "Fully-enclosed CoreXY running Kobra OS (GoKlipper-family), with one \
                ACE Pro for four-color or two units for eight-color printing. The 320 °C \
                quick-swap hotend and 120 °C bed support ABS/ASA; TPU bypasses ACE Pro. \
                Accepts klipper-flavored G-code.",
    },
    FdmPrinterModelSpec {
        model: "qidi-q1-pro",
        vendor: "QIDI Tech",
        display_name: "QIDI Q1 Pro",
        aliases: &["q1-pro", "qidi-q1", "qidi-tech-q1-pro"],
        machine_kind: "fdm-printer",
        controller: "klipper",
        kinematics: "corexy",
        work_envelope_mm: [245.0, 245.0, 240.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 350.0,
        max_bed_temp_c: 120.0,
        max_volumetric_flow_mm3_s: 24.0,
        enclosed: true,
        max_materials: 1,
        materials: &[
            "pla",
            "petg",
            "abs",
            "asa",
            "tpu",
            "pc",
            "pa",
            "carbon-fiber",
            "glass-fiber",
        ],
        operations: &["additive-print"],
        notes: "Enclosed CoreXY with a 60 °C independently heated chamber, 350 °C \
                bimetal hotend, hardened drive gears, and open-source Klipper controller. \
                The profile uses a conservative 24 mm³/s preflight flow ceiling.",
    },
    FdmPrinterModelSpec {
        model: "qidi-plus4",
        vendor: "QIDI Tech",
        display_name: "QIDI Plus4",
        aliases: &["plus4", "plus-4", "qidi-plus-4", "qidi-tech-plus4"],
        machine_kind: "fdm-printer",
        controller: "klipper",
        kinematics: "corexy",
        work_envelope_mm: [305.0, 305.0, 280.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 370.0,
        max_bed_temp_c: 120.0,
        max_volumetric_flow_mm3_s: 24.0,
        enclosed: true,
        max_materials: 1,
        materials: &[
            "pla",
            "petg",
            "abs",
            "asa",
            "tpu",
            "pc",
            "pa",
            "carbon-fiber",
            "glass-fiber",
        ],
        operations: &["additive-print"],
        notes: "Large enclosed CoreXY with a 65 °C independently heated chamber, \
                370 °C bimetal hotend, hardened drive gears, and open-source Klipper \
                0.12. QIDI Box is optional; this base-machine profile remains \
                single-material and uses a conservative 24 mm³/s flow ceiling.",
    },
    FdmPrinterModelSpec {
        model: "flashforge-adventurer-5m",
        vendor: "FlashForge",
        display_name: "FlashForge Adventurer 5M",
        aliases: &["adventurer-5m", "ad5m", "flashforge-ad5m"],
        machine_kind: "fdm-printer",
        controller: "flashforge",
        kinematics: "corexy",
        work_envelope_mm: [220.0, 220.0, 220.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 280.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 28.0,
        enclosed: false,
        max_materials: 1,
        materials: &["pla", "petg", "tpu", "carbon-fiber"],
        operations: &["additive-print"],
        notes: "Open-frame all-metal CoreXY with quick-release 280 °C nozzles. \
                Carbon-filled PLA/PETG and TPU require the vendor-recommended 0.6 mm \
                nozzle. Accepts FlashPrint and Orca-Flashforge G-code.",
    },
    FdmPrinterModelSpec {
        model: "flashforge-adventurer-5m-pro",
        vendor: "FlashForge",
        display_name: "FlashForge Adventurer 5M Pro",
        aliases: &[
            "adventurer-5m-pro",
            "ad5m-pro",
            "ad5mp",
            "flashforge-ad5m-pro",
        ],
        machine_kind: "fdm-printer",
        controller: "flashforge",
        kinematics: "corexy",
        work_envelope_mm: [220.0, 220.0, 220.0],
        max_print_speed_mm_s: 600.0,
        max_acceleration_mm_s2: 20_000.0,
        max_nozzle_temp_c: 280.0,
        max_bed_temp_c: 100.0,
        max_volumetric_flow_mm3_s: 32.0,
        enclosed: true,
        max_materials: 1,
        materials: &["pla", "petg", "abs", "asa", "tpu", "carbon-fiber"],
        operations: &["additive-print"],
        notes: "Enclosed all-metal CoreXY with 32 mm³/s hotend flow, quick-release \
                280 °C nozzles, camera, and HEPA/carbon recirculation. The enclosure \
                supports ABS/ASA; accepts FlashPrint and Orca-Flashforge G-code.",
    },
];

/// Resolve a machine kind or model reference to a supported printer model.
/// Accepts raw input; matching is on the normalized token.
pub(crate) fn fdm_printer_model_for_token(value: &str) -> Option<&'static FdmPrinterModelSpec> {
    let token = super::normalize_token(value);
    FDM_PRINTER_MODEL_SPECS
        .iter()
        .find(|spec| spec.model == token || spec.aliases.iter().any(|alias| *alias == token))
}

pub(super) fn fdm_printer_models_json() -> Value {
    Value::Array(
        FDM_PRINTER_MODEL_SPECS
            .iter()
            .map(|spec| {
                json!({
                    "model": spec.model,
                    "vendor": spec.vendor,
                    "displayName": spec.display_name,
                    "aliases": spec.aliases,
                    "machineKind": spec.machine_kind,
                    "fleetMachineId": format!("{}-1", spec.model),
                    "controller": spec.controller,
                    "kinematics": spec.kinematics,
                    "workEnvelopeMm": spec.work_envelope_mm,
                    "maxPrintSpeedMmS": spec.max_print_speed_mm_s,
                    "maxAccelerationMmS2": spec.max_acceleration_mm_s2,
                    "maxNozzleTempC": spec.max_nozzle_temp_c,
                    "maxBedTempC": spec.max_bed_temp_c,
                    "maxVolumetricFlowMm3S": spec.max_volumetric_flow_mm3_s,
                    "enclosed": spec.enclosed,
                    "maxMaterials": spec.max_materials,
                    "materials": spec.materials,
                    "operations": spec.operations,
                    "notes": spec.notes,
                })
            })
            .collect(),
    )
}
