apiVersion: v1
kind: Service
metadata:
  name: dd-git-rs
  namespace: default
  labels:
    app: dd-git-rs
spec:
  selector:
    app: dd-git-rs
  ports:
    - name: http
      port: 8137
      targetPort: http
